.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching func_80000400_1000, 0x38

glabel func_80000400_1000
    /* 1000 80000400 3C08800B */  lui        $t0, %hi(D_800B0B50_B1750)
    /* 1004 80000404 3C090005 */  lui        $t1, (0x54E50 >> 16)
    /* 1008 80000408 25080B50 */  addiu      $t0, $t0, %lo(D_800B0B50_B1750)
    /* 100C 8000040C 35294E50 */  ori        $t1, $t1, (0x54E50 & 0xFFFF)
  .L80000410_1010:
    /* 1010 80000410 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1014 80000414 AD000000 */  sw         $zero, 0x0($t0)
    /* 1018 80000418 AD000004 */  sw         $zero, 0x4($t0)
    /* 101C 8000041C 1520FFFC */  bnez       $t1, .L80000410_1010
    /* 1020 80000420 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1024 80000424 3C0A8004 */  lui        $t2, %hi(boot)
    /* 1028 80000428 3C1D8010 */  lui        $sp, %hi(cameraActorArray)
    /* 102C 8000042C 254AF500 */  addiu      $t2, $t2, %lo(boot)
    /* 1030 80000430 01400008 */  jr         $t2
    /* 1034 80000434 27BDA4D0 */   addiu     $sp, $sp, %lo(cameraActorArray)
endlabel func_80000400_1000
    /* 1038 80000438 00000000 */  nop
    /* 103C 8000043C 00000000 */  nop
    /* 1040 80000440 00000000 */  nop
    /* 1044 80000444 00000000 */  nop
    /* 1048 80000448 00000000 */  nop
    /* 104C 8000044C 00000000 */  nop
