.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .rodata

dlabel gzip_border
.byte 16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15

dlabel gzip_cplens
.half 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115, 131, 163, 195, 227, 258, 0, 0

dlabel gzip_cplext
.byte 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0, 99, 99

dlabel gzip_cpdist
.half 1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577

dlabel gzip_cpdext
.byte 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13

dlabel gzip_mask_bits
.half 0x0000, 0x0001, 0x0003, 0x0007, 0x000f, 0x001f, 0x003f, 0x007f, 0x00ff, 0x01ff, 0x03ff, 0x07ff, 0x0fff, 0x1fff, 0x3fff, 0x7fff, 0xffff

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

glabel inflate_block
    lui        $t3, %hi(rzip_num_bits)
    lw         $t3, %lo(rzip_num_bits)($t3)
    lui        $at, %hi(rzip_hufts)
    sw         $zero, %lo(rzip_hufts)($at)
    addiu      $t0, $zero, 0x1
    addiu      $sp, $sp, -0x20
    lui        $t4, %hi(rzip_inflate_input)
    lui        $t2, %hi(rzip_bit_buffer)
    sltu       $at, $t3, $t0
    sw         $ra, 0x1C($sp)
    sw         $s0, 0x18($sp)
    lw         $t4, %lo(rzip_inflate_input)($t4)
    beqz       $at, .L800733C4
     lw        $t2, %lo(rzip_bit_buffer)($t2)
  .L800733A8:
    lbu        $v0, 0x0($t4)
    addiu      $t4, $t4, 0x1
    sllv       $v0, $v0, $t3
    addiu      $t3, $t3, 0x8
    slt        $at, $t3, $t0
    bnez       $at, .L800733A8
     or        $t2, $t2, $v0
  .L800733C4:
    andi       $s0, $t2, 0x1
    srlv       $t2, $t2, $t0
    sub        $t3, $t3, $t0
    addiu      $t0, $zero, 0x2
    sltu       $at, $t3, $t0
    beqz       $at, .L800733FC
     nop
  .L800733E0:
    lbu        $v0, 0x0($t4)
    addiu      $t4, $t4, 0x1
    sllv       $v0, $v0, $t3
    addiu      $t3, $t3, 0x8
    slt        $at, $t3, $t0
    bnez       $at, .L800733E0
     or        $t2, $t2, $v0
  .L800733FC:
    lui        $at, %hi(rzip_inflate_input)
    andi       $t1, $t2, 0x3
    sw         $t4, %lo(rzip_inflate_input)($at)
    srlv       $t2, $t2, $t0
    lui        $at, %hi(rzip_bit_buffer)
    sw         $t2, %lo(rzip_bit_buffer)($at)
    sub        $t3, $t3, $t0
    lui        $at, %hi(rzip_num_bits)
    sw         $t3, %lo(rzip_num_bits)($at)
    addiu      $at, $zero, 0x2
    beq        $t1, $at, .L80073454
     addiu     $at, $zero, 0x1
    beq        $t1, $at, .L80073444
     nop
    jal        inflate_stored
     nop
    j          func_8007345C
     nop
  .L80073444:
    jal        inflate_fixed
     nop
    j          func_8007345C
     nop
  .L80073454:
    jal        inflate_dynamic
     nop
  alabel func_8007345C
    lw         $ra, 0x1C($sp)
    addiu      $v0, $zero, 0x1
    sub        $v0, $v0, $s0
    lw         $s0, 0x18($sp)
    jr         $ra
     addiu     $sp, $sp, 0x20
endlabel inflate_block

/* Handwritten function */
glabel inflate_dynamic
    addiu      $sp, $sp, -0x540
    sw         $s3, 0x28($sp)
    lui        $s3, %hi(rzip_num_bits)
    lw         $s3, %lo(rzip_num_bits)($s3)
    sw         $s4, 0x2C($sp)
    sw         $s2, 0x24($sp)
    addiu      $t0, $zero, 0x5
    lui        $s4, %hi(rzip_inflate_input)
    lui        $s2, %hi(rzip_bit_buffer)
    sltu       $at, $s3, $t0
    sw         $ra, 0x30($sp)
    sw         $s1, 0x20($sp)
    sw         $s0, 0x1C($sp)
    lw         $s4, %lo(rzip_inflate_input)($s4)
    beqz       $at, .L800734D0
     lw        $s2, %lo(rzip_bit_buffer)($s2)
  .L800734B4:
    lbu        $v0, 0x0($s4)
    addiu      $s4, $s4, 0x1
    sllv       $v0, $v0, $s3
    addiu      $s3, $s3, 0x8
    slt        $at, $s3, $t0
    bnez       $at, .L800734B4
     or        $s2, $s2, $v0
  .L800734D0:
    sub        $s3, $s3, $t0
    andi       $s1, $s2, 0x1F
    sltu       $at, $s3, $t0
    addiu      $s1, $s1, 0x101
    beqz       $at, .L80073504
     srlv      $s2, $s2, $t0
  .L800734E8:
    lbu        $v0, 0x0($s4)
    addiu      $s4, $s4, 0x1
    sllv       $v0, $v0, $s3
    addiu      $s3, $s3, 0x8
    slt        $at, $s3, $t0
    bnez       $at, .L800734E8
     or        $s2, $s2, $v0
  .L80073504:
    andi       $s0, $s2, 0x1F
    srlv       $s2, $s2, $t0
    sub        $s3, $s3, $t0
    addiu      $t0, $zero, 0x4
    sltu       $at, $s3, $t0
    beqz       $at, .L8007353C
     addiu     $s0, $s0, 0x1
  .L80073520:
    lbu        $v0, 0x0($s4)
    addiu      $s4, $s4, 0x1
    sllv       $v0, $v0, $s3
    addiu      $s3, $s3, 0x8
    slt        $at, $s3, $t0
    bnez       $at, .L80073520
     or        $s2, $s2, $v0
  .L8007353C:
    andi       $t2, $s2, 0xF
    addiu      $t2, $t2, 0x4
    lui        $t9, %hi(gzip_border)
    srlv       $s2, $s2, $t0
    sub        $s3, $s3, $t0
    or         $t1, $zero, $t2
    addiu      $t9, $t9, %lo(gzip_border)
    beqz       $t2, .L800735C0
     addi      $t7, $sp, 0x44
  .L80073560:
    addiu      $t0, $zero, 0x3
    sltu       $at, $s3, $t0
    beql       $at, $zero, .L80073590
     lbu       $v1, 0x0($t9)
  .L80073570:
    lbu        $v0, 0x0($s4)
    addiu      $s4, $s4, 0x1
    sllv       $v0, $v0, $s3
    addiu      $s3, $s3, 0x8
    slt        $at, $s3, $t0
    bnez       $at, .L80073570
     or        $s2, $s2, $v0
    lbu        $v1, 0x0($t9)
  .L80073590:
    andi       $v0, $s2, 0x7
    addiu      $t2, $t2, -0x1
    sll        $v1, $v1, 2
    addu       $v1, $v1, $t7
    sw         $v0, 0x0($v1)
    srlv       $s2, $s2, $t0
    sub        $s3, $s3, $t0
    bnez       $t2, .L80073560
     addiu     $t9, $t9, 0x1
    sltiu      $at, $t1, 0x13
    beql       $at, $zero, .L800735E4
     addiu     $t5, $zero, 0x7
  .L800735C0:
    lbu        $v1, 0x0($t9)
    addiu      $t1, $t1, 0x1
    slti       $at, $t1, 0x13
    sll        $v1, $v1, 2
    addu       $v1, $v1, $t7
    sw         $zero, 0x0($v1)
    bnez       $at, .L800735C0
     addiu     $t9, $t9, 0x1
    addiu      $t5, $zero, 0x7
  .L800735E4:
    addi       $t0, $sp, 0x34
    addi       $t1, $sp, 0x38
    sw         $t5, 0x38($sp)
    addi       $a0, $sp, 0x44
    addiu      $a1, $zero, 0x13
    addiu      $a2, $zero, 0x13
    addiu      $a3, $zero, 0x0
    sw         $zero, 0x10($sp)
    sw         $t0, 0x14($sp)
    jal        huft_build
     sw        $t1, 0x18($sp)
    addi       $t1, $sp, 0x38
    lw         $t5, 0x0($t1)
    lui        $v0, %hi(gzip_mask_bits)
    addiu      $v0, $v0, %lo(gzip_mask_bits)
    sll        $v1, $t5, 1
    addi       $t0, $sp, 0x34
    add        $v0, $v0, $v1
    lw         $t6, 0x0($t0)
    add        $t9, $s1, $s0
    lh         $t8, 0x0($v0)
    addi       $t7, $sp, 0x44
    addiu      $t2, $zero, 0x0
  alabel func_80073640
    beqz       $t9, .L800737C0
     sltu      $at, $s3, $t5
    beql       $at, $zero, .L80073670
     and       $v0, $s2, $t8
  .L80073650:
    lbu        $v0, 0x0($s4)
    addiu      $s4, $s4, 0x1
    sllv       $v0, $v0, $s3
    addiu      $s3, $s3, 0x8
    slt        $at, $s3, $t5
    bnez       $at, .L80073650
     or        $s2, $s2, $v0
    and        $v0, $s2, $t8
  .L80073670:
    sll        $v0, $v0, 3
    addu       $t1, $t6, $v0
    lhu        $t0, 0x4($t1)
    lbu        $v0, 0x1($t1)
    slti       $at, $t0, 0x10
    srlv       $s2, $s2, $v0
    bnez       $at, .L800736FC
     sub       $s3, $s3, $v0
    addiu      $at, $zero, 0x10
    beq        $t0, $at, .L80073710
     addiu     $at, $zero, 0x11
    beql       $t0, $at, .L8007376C
     addiu     $t0, $zero, 0x3
    addiu      $t0, $zero, 0x7
    sltu       $at, $s3, $t0
    beql       $at, $zero, .L800736D4
     andi      $t1, $s2, 0x7F
  .L800736B4:
    lbu        $v0, 0x0($s4)
    addiu      $s4, $s4, 0x1
    sllv       $v0, $v0, $s3
    addiu      $s3, $s3, 0x8
    slt        $at, $s3, $t0
    bnez       $at, .L800736B4
     or        $s2, $s2, $v0
    andi       $t1, $s2, 0x7F
  .L800736D4:
    addiu      $t1, $t1, 0xB
    srlv       $s2, $s2, $t0
    sub        $s3, $s3, $t0
    subu       $t9, $t9, $t1
  .L800736E4:
    addiu      $t1, $t1, -0x1
    sw         $zero, 0x0($t7)
    bnez       $t1, .L800736E4
     addiu     $t7, $t7, 0x4
    j          func_80073640
     addiu     $t2, $zero, 0x0
  .L800736FC:
    sw         $t0, 0x0($t7)
    addiu      $t7, $t7, 0x4
    addiu      $t9, $t9, -0x1
    j          func_80073640
     or        $t2, $zero, $t0
  .L80073710:
    addiu      $t0, $zero, 0x2
    sltu       $at, $s3, $t0
    beql       $at, $zero, .L80073740
     andi      $t1, $s2, 0x3
  .L80073720:
    lbu        $v0, 0x0($s4)
    addiu      $s4, $s4, 0x1
    sllv       $v0, $v0, $s3
    addiu      $s3, $s3, 0x8
    slt        $at, $s3, $t0
    bnez       $at, .L80073720
     or        $s2, $s2, $v0
    andi       $t1, $s2, 0x3
  .L80073740:
    addi       $t1, $t1, 0x3
    srlv       $s2, $s2, $t0
    sub        $s3, $s3, $t0
    subu       $t9, $t9, $t1
  .L80073750:
    addiu      $t1, $t1, -0x1
    sw         $t2, 0x0($t7)
    bnez       $t1, .L80073750
     addiu     $t7, $t7, 0x4
    j          func_80073640
     nop
    addiu      $t0, $zero, 0x3
  .L8007376C:
    sltu       $at, $s3, $t0
    beql       $at, $zero, .L80073798
     andi      $t1, $s2, 0x7
  .L80073778:
    lbu        $v0, 0x0($s4)
    addiu      $s4, $s4, 0x1
    sllv       $v0, $v0, $s3
    addiu      $s3, $s3, 0x8
    slt        $at, $s3, $t0
    bnez       $at, .L80073778
     or        $s2, $s2, $v0
    andi       $t1, $s2, 0x7
  .L80073798:
    addi       $t1, $t1, 0x3
    srlv       $s2, $s2, $t0
    sub        $s3, $s3, $t0
    subu       $t9, $t9, $t1
  .L800737A8:
    addiu      $t1, $t1, -0x1
    sw         $zero, 0x0($t7)
    bnez       $t1, .L800737A8
     addiu     $t7, $t7, 0x4
    j          func_80073640
     addiu     $t2, $zero, 0x0
  .L800737C0:
    lui        $at, %hi(rzip_inflate_input)
    sw         $s4, %lo(rzip_inflate_input)($at)
    lui        $at, %hi(rzip_bit_buffer)
    addiu      $t0, $zero, 0x9
    sw         $s2, %lo(rzip_bit_buffer)($at)
    sw         $t0, 0x38($sp)
    lui        $v0, %hi(gzip_cplext)
    lui        $at, %hi(rzip_num_bits)
    lui        $a3, %hi(gzip_cplens)
    addiu      $v0, $v0, %lo(gzip_cplext)
    addi       $v1, $sp, 0x34
    addi       $t0, $sp, 0x38
    sw         $s3, %lo(rzip_num_bits)($at)
    addi       $a0, $sp, 0x44
    or         $a1, $zero, $s1
    addiu      $a2, $zero, 0x101
    addiu      $a3, $a3, %lo(gzip_cplens)
    sw         $v0, 0x10($sp)
    sw         $v1, 0x14($sp)
    jal        huft_build
     sw        $t0, 0x18($sp)
    addi       $a0, $sp, 0x44
    sll        $v0, $s1, 2
    addiu      $t0, $zero, 0x6
    addu       $a0, $a0, $v0
    sw         $t0, 0x40($sp)
    lui        $v0, %hi(gzip_cpdext)
    lui        $a3, %hi(gzip_cpdist)
    addiu      $v0, $v0, %lo(gzip_cpdext)
    addi       $v1, $sp, 0x3C
    addi       $t0, $sp, 0x40
    or         $a1, $zero, $s0
    addiu      $a2, $zero, 0x0
    addiu      $a3, $a3, %lo(gzip_cpdist)
    sw         $v0, 0x10($sp)
    sw         $v1, 0x14($sp)
    jal        huft_build
     sw        $t0, 0x18($sp)
    lw         $a0, 0x34($sp)
    lw         $a1, 0x3C($sp)
    lw         $a2, 0x38($sp)
    jal        inflate_codes
     lw        $a3, 0x40($sp)
    lw         $ra, 0x30($sp)
    lw         $s4, 0x2C($sp)
    lw         $s3, 0x28($sp)
    lw         $s2, 0x24($sp)
    lw         $s1, 0x20($sp)
    lw         $s0, 0x1C($sp)
    jr         $ra
     addiu     $sp, $sp, 0x540
endlabel inflate_dynamic

glabel inflate_fixed
    addiu      $sp, $sp, -0x530
    sw         $ra, 0x1C($sp)
    addi       $t3, $sp, 0x44
    addiu      $t0, $zero, 0x24
    addiu      $t1, $zero, 0x8
  .L800738A0:
    addiu      $t0, $t0, -0x1
    sw         $t1, 0x0($t3)
    sw         $t1, 0x4($t3)
    sw         $t1, 0x8($t3)
    sw         $t1, 0xC($t3)
    bnez       $t0, .L800738A0
     addiu     $t3, $t3, 0x10
    addiu      $t0, $zero, 0x1C
    addiu      $t1, $zero, 0x9
  .L800738C4:
    addiu      $t0, $t0, -0x1
    sw         $t1, 0x0($t3)
    sw         $t1, 0x4($t3)
    sw         $t1, 0x8($t3)
    sw         $t1, 0xC($t3)
    bnez       $t0, .L800738C4
     addiu     $t3, $t3, 0x10
    addiu      $t0, $zero, 0x6
    addiu      $t1, $zero, 0x7
  .L800738E8:
    addiu      $t0, $t0, -0x1
    sw         $t1, 0x0($t3)
    sw         $t1, 0x4($t3)
    sw         $t1, 0x8($t3)
    sw         $t1, 0xC($t3)
    bnez       $t0, .L800738E8
     addiu     $t3, $t3, 0x10
    addiu      $t1, $zero, 0x8
    sw         $t1, 0x0($t3)
    sw         $t1, 0x4($t3)
    sw         $t1, 0x8($t3)
    sw         $t1, 0xC($t3)
    sw         $t1, 0x10($t3)
    sw         $t1, 0x14($t3)
    sw         $t1, 0x18($t3)
    sw         $t1, 0x1C($t3)
    addiu      $t0, $zero, 0x7
    sw         $t0, 0x38($sp)
    lui        $v0, %hi(gzip_cplext)
    lui        $a3, %hi(gzip_cplens)
    addiu      $v0, $v0, %lo(gzip_cplext)
    addi       $v1, $sp, 0x20
    addi       $t0, $sp, 0x24
    addi       $a0, $sp, 0x44
    addiu      $a1, $zero, 0x120
    addiu      $a2, $zero, 0x101
    addiu      $a3, $a3, %lo(gzip_cplens)
    sw         $v0, 0x10($sp)
    sw         $v1, 0x14($sp)
    jal        huft_build
     sw        $t0, 0x18($sp)
    addi       $t3, $sp, 0x44
    addiu      $t0, $zero, 0xA
    addiu      $t1, $zero, 0x5
  .L80073970:
    addiu      $t0, $t0, -0x1
    sw         $t1, 0x0($t3)
    sw         $t1, 0x4($t3)
    sw         $t1, 0x8($t3)
    bnez       $t0, .L80073970
     addiu     $t3, $t3, 0xC
    lui        $v0, %hi(gzip_cpdext)
    lui        $a3, %hi(gzip_cpdist)
    addiu      $v0, $v0, %lo(gzip_cpdext)
    addi       $v1, $sp, 0x28
    addi       $t0, $sp, 0x2C
    sw         $t1, 0x40($sp)
    addi       $a0, $sp, 0x44
    addiu      $a1, $zero, 0x1E
    addiu      $a2, $zero, 0x0
    addiu      $a3, $a3, %lo(gzip_cpdist)
    sw         $v0, 0x10($sp)
    sw         $v1, 0x14($sp)
    jal        huft_build
     sw        $t0, 0x18($sp)
    lw         $a0, 0x20($sp)
    lw         $a1, 0x28($sp)
    lw         $a2, 0x24($sp)
    jal        inflate_codes
     lw        $a3, 0x2C($sp)
    lw         $ra, 0x1C($sp)
    addiu      $sp, $sp, 0x530
    jr         $ra
     nop
endlabel inflate_fixed

glabel inflate_stored
    lui        $t5, %hi(rzip_num_bits)
    lw         $t5, %lo(rzip_num_bits)($t5)
    lui        $t4, %hi(rzip_bit_buffer)
    lw         $t4, %lo(rzip_bit_buffer)($t4)
    andi       $t0, $t5, 0x7
    sub        $t5, $t5, $t0
    srlv       $t4, $t4, $t0
    addiu      $t0, $zero, 0x10
    lui        $t7, %hi(rzip_inflate_input)
    lui        $t6, %hi(rzip_inflate_output)
    sltu       $at, $t5, $t0
    lw         $t7, %lo(rzip_inflate_input)($t7)
    beqz       $at, .L80073A38
     lw        $t6, %lo(rzip_inflate_output)($t6)
  .L80073A1C:
    lbu        $v0, 0x0($t7)
    addiu      $t7, $t7, 0x1
    sllv       $v0, $v0, $t5
    addiu      $t5, $t5, 0x8
    slt        $at, $t5, $t0
    bnez       $at, .L80073A1C
     or        $t4, $t4, $v0
  .L80073A38:
    sub        $t5, $t5, $t0
    andi       $t1, $t4, 0xFFFF
    sltu       $at, $t5, $t0
    beqz       $at, .L80073A68
     srlv      $t4, $t4, $t0
  .L80073A4C:
    lbu        $v0, 0x0($t7)
    addiu      $t7, $t7, 0x1
    sllv       $v0, $v0, $t5
    addiu      $t5, $t5, 0x8
    slt        $at, $t5, $t0
    bnez       $at, .L80073A4C
     or        $t4, $t4, $v0
  .L80073A68:
    andi       $v0, $t1, 0x3
    srlv       $t4, $t4, $t0
    beqz       $v0, .L80073A9C
     sub       $t5, $t5, $t0
    sub        $t1, $t1, $v0
  .L80073A7C:
    lbu        $t2, 0x0($t7)
    addi       $v0, $v0, -0x1
    addi       $t7, $t7, 0x1
    addi       $t6, $t6, 0x1
    bnez       $v0, .L80073A7C
     sb        $t2, -0x1($t6)
    beqz       $t1, .L80073ACC
     nop
  .L80073A9C:
    lbu        $v0, 0x0($t7)
    addiu      $t1, $t1, -0x4
    addiu      $t7, $t7, 0x4
    sb         $v0, 0x0($t6)
    lbu        $v1, -0x3($t7)
    addiu      $t6, $t6, 0x4
    sb         $v1, -0x3($t6)
    lbu        $t2, -0x2($t7)
    sb         $t2, -0x2($t6)
    lbu        $t3, -0x1($t7)
    bnez       $t1, .L80073A9C
     sb        $t3, -0x1($t6)
  .L80073ACC:
    lui        $at, %hi(rzip_inflate_input)
    sw         $t7, %lo(rzip_inflate_input)($at)
    lui        $at, %hi(rzip_inflate_output)
    sw         $t6, %lo(rzip_inflate_output)($at)
    lui        $at, %hi(rzip_bit_buffer)
    sw         $t4, %lo(rzip_bit_buffer)($at)
    lui        $at, %hi(rzip_num_bits)
    jr         $ra
     sw        $t5, %lo(rzip_num_bits)($at)
endlabel inflate_stored

/* Handwritten function */
glabel inflate_codes
    addiu      $sp, $sp, -0x10
    lui        $t3, %hi(gzip_mask_bits)
    sw         $s2, 0x8($sp)
    sw         $s1, 0x4($sp)
    sw         $s0, 0x0($sp)
    addiu      $t3, $t3, %lo(gzip_mask_bits)
    sll        $v0, $a2, 1
    sll        $t0, $a3, 1
    lui        $s2, %hi(rzip_inflate_input)
    lui        $s1, %hi(rzip_inflate_output)
    lui        $t9, %hi(rzip_bit_buffer)
    lui        $s0, %hi(rzip_num_bits)
    addu       $v1, $t3, $v0
    addu       $t1, $t3, $t0
    lw         $s2, %lo(rzip_inflate_input)($s2)
    lw         $s1, %lo(rzip_inflate_output)($s1)
    lw         $t9, %lo(rzip_bit_buffer)($t9)
    lw         $s0, %lo(rzip_num_bits)($s0)
    lhu        $t5, 0x0($v1)
    lhu        $t4, 0x0($t1)
  alabel func_80073B40
    sltu       $at, $s0, $a2
  .L80073B44:
    beql       $at, $zero, .L80073B6C
     and       $v0, $t9, $t5
  .L80073B4C:
    lbu        $v0, 0x0($s2)
    addiu      $s2, $s2, 0x1
    sllv       $v0, $v0, $s0
    addiu      $s0, $s0, 0x8
    slt        $at, $s0, $a2
    bnez       $at, .L80073B4C
     or        $t9, $t9, $v0
    and        $v0, $t9, $t5
  .L80073B6C:
    sll        $v0, $v0, 3
    addu       $t7, $a0, $v0
    lbu        $t8, 0x0($t7)
    slti       $at, $t8, 0x11
    bnel       $at, $zero, .L80073BE8
     lbu       $v0, 0x1($t7)
    lb         $v1, 0x1($t7)
  .L80073B88:
    addi       $t8, $t8, -0x10
    sub        $s0, $s0, $v1
    sltu       $at, $s0, $t8
    beqz       $at, .L80073BB8
     srlv      $t9, $t9, $v1
  .L80073B9C:
    lbu        $v0, 0x0($s2)
    addiu      $s2, $s2, 0x1
    sllv       $v0, $v0, $s0
    addiu      $s0, $s0, 0x8
    slt        $at, $s0, $t8
    bnez       $at, .L80073B9C
     or        $t9, $t9, $v0
  .L80073BB8:
    sll        $v0, $t8, 1
    addu       $v0, $v0, $t3
    lhu        $t1, 0x0($v0)
    lw         $t0, 0x4($t7)
    and        $t1, $t1, $t9
    sll        $t1, $t1, 3
    add        $t7, $t0, $t1
    lbu        $t8, 0x0($t7)
    sltiu      $at, $t8, 0x11
    beql       $at, $zero, .L80073B88
     lb        $v1, 0x1($t7)
    lbu        $v0, 0x1($t7)
  .L80073BE8:
    addiu      $at, $zero, 0x10
    srlv       $t9, $t9, $v0
    bne        $t8, $at, .L80073C08
     sub       $s0, $s0, $v0
    lhu        $v0, 0x4($t7)
    addiu      $s1, $s1, 0x1
    j          func_80073B40
     sb        $v0, -0x1($s1)
  .L80073C08:
    addiu      $at, $zero, 0xF
    beq        $t8, $at, .L80073DB0
     sltu      $at, $s0, $t8
    beql       $at, $zero, .L80073C3C
     sll       $v0, $t8, 1
  .L80073C1C:
    lbu        $v0, 0x0($s2)
    addiu      $s2, $s2, 0x1
    sllv       $v0, $v0, $s0
    addiu      $s0, $s0, 0x8
    slt        $at, $s0, $t8
    bnez       $at, .L80073C1C
     or        $t9, $t9, $v0
    sll        $v0, $t8, 1
  .L80073C3C:
    addu       $v0, $v0, $t3
    lhu        $t1, 0x0($v0)
    lhu        $t0, 0x4($t7)
    sub        $s0, $s0, $t8
    sltu       $at, $s0, $a3
    and        $t1, $t1, $t9
    srlv       $t9, $t9, $t8
    beqz       $at, .L80073C7C
     addu      $t6, $t0, $t1
  .L80073C60:
    lbu        $v0, 0x0($s2)
    addiu      $s2, $s2, 0x1
    sllv       $v0, $v0, $s0
    addiu      $s0, $s0, 0x8
    slt        $at, $s0, $a3
    bnez       $at, .L80073C60
     or        $t9, $t9, $v0
  .L80073C7C:
    and        $v0, $t4, $t9
    sll        $v0, $v0, 3
    addu       $t7, $a1, $v0
    lbu        $t8, 0x0($t7)
    slti       $at, $t8, 0x11
    bnel       $at, $zero, .L80073CFC
     lbu       $v0, 0x1($t7)
    lbu        $t0, 0x1($t7)
  .L80073C9C:
    addi       $t8, $t8, -0x10
    sub        $s0, $s0, $t0
    sltu       $at, $s0, $t8
    beqz       $at, .L80073CCC
     srlv      $t9, $t9, $t0
  .L80073CB0:
    lbu        $v0, 0x0($s2)
    addiu      $s2, $s2, 0x1
    sllv       $v0, $v0, $s0
    addiu      $s0, $s0, 0x8
    slt        $at, $s0, $t8
    bnez       $at, .L80073CB0
     or        $t9, $t9, $v0
  .L80073CCC:
    sll        $v0, $t8, 1
    addu       $v0, $v0, $t3
    lhu        $t1, 0x0($v0)
    lw         $t0, 0x4($t7)
    and        $t1, $t1, $t9
    sll        $t1, $t1, 3
    addu       $t7, $t0, $t1
    lbu        $t8, 0x0($t7)
    sltiu      $at, $t8, 0x11
    beql       $at, $zero, .L80073C9C
     lbu       $t0, 0x1($t7)
    lbu        $v0, 0x1($t7)
  .L80073CFC:
    sub        $s0, $s0, $v0
    sltu       $at, $s0, $t8
    beqz       $at, .L80073D28
     srlv      $t9, $t9, $v0
  .L80073D0C:
    lbu        $v0, 0x0($s2)
    addiu      $s2, $s2, 0x1
    sllv       $v0, $v0, $s0
    addiu      $s0, $s0, 0x8
    slt        $at, $s0, $t8
    bnez       $at, .L80073D0C
     or        $t9, $t9, $v0
  .L80073D28:
    sll        $v0, $t8, 1
    addu       $v0, $v0, $t3
    lhu        $t1, 0x0($v0)
    lhu        $v1, 0x4($t7)
    andi       $v0, $t6, 0x3
    and        $t1, $t1, $t9
    sub        $t0, $s1, $v1
    sub        $t0, $t0, $t1
    srlv       $t9, $t9, $t8
    beqz       $v0, .L80073D78
     sub       $s0, $s0, $t8
    sub        $t6, $t6, $v0
  .L80073D58:
    lbu        $t2, 0x0($t0)
    addi       $v0, $v0, -0x1
    addi       $t0, $t0, 0x1
    addi       $s1, $s1, 0x1
    bnez       $v0, .L80073D58
     sb        $t2, -0x1($s1)
    beql       $t6, $zero, .L80073B44
     sltu      $at, $s0, $a2
  .L80073D78:
    lbu        $v0, 0x0($t0)
    addiu      $t6, $t6, -0x4
    addiu      $t0, $t0, 0x4
    sb         $v0, 0x0($s1)
    lbu        $v1, -0x3($t0)
    addiu      $s1, $s1, 0x4
    sb         $v1, -0x3($s1)
    lbu        $t1, -0x2($t0)
    sb         $t1, -0x2($s1)
    lbu        $t2, -0x1($t0)
    bnez       $t6, .L80073D78
     sb        $t2, -0x1($s1)
    j          func_80073B40
     nop
  .L80073DB0:
    lui        $at, %hi(rzip_inflate_input)
    sw         $s2, %lo(rzip_inflate_input)($at)
    lui        $at, %hi(rzip_inflate_output)
    sw         $s1, %lo(rzip_inflate_output)($at)
    lui        $at, %hi(rzip_bit_buffer)
    sw         $t9, %lo(rzip_bit_buffer)($at)
    lui        $at, %hi(rzip_num_bits)
    sw         $s0, %lo(rzip_num_bits)($at)
    lw         $s2, 0x8($sp)
    lw         $s1, 0x4($sp)
    lw         $s0, 0x0($sp)
    jr         $ra
     addiu     $sp, $sp, 0x10
endlabel inflate_codes
