.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching osGetCount, 0xC

glabel osGetCount
    /* 94100 80093500 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* 94104 80093504 03E00008 */  jr         $ra
    /* 94108 80093508 00000000 */   nop
endlabel osGetCount
