.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching __osGetSR, 0xC

glabel __osGetSR
    /* 9B680 8009AA80 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 9B684 8009AA84 03E00008 */  jr         $ra
    /* 9B688 8009AA88 00000000 */   nop
endlabel __osGetSR
    /* 9B68C 8009AA8C 00000000 */  nop
