.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching osMapTLBRdb, 0x58

glabel osMapTLBRdb
    /* 9B790 8009AB90 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 9B794 8009AB94 2409001F */  addiu      $t1, $zero, 0x1F
    /* 9B798 8009AB98 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 9B79C 8009AB9C 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* 9B7A0 8009ABA0 240A0017 */  addiu      $t2, $zero, 0x17
    /* 9B7A4 8009ABA4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* 9B7A8 8009ABA8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 9B7AC 8009ABAC 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* 9B7B0 8009ABB0 00095982 */  srl        $t3, $t1, 6
    /* 9B7B4 8009ABB4 016A5825 */  or         $t3, $t3, $t2
    /* 9B7B8 8009ABB8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* 9B7BC 8009ABBC 24090001 */  addiu      $t1, $zero, 0x1
    /* 9B7C0 8009ABC0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* 9B7C4 8009ABC4 00000000 */  nop
    /* 9B7C8 8009ABC8 42000002 */  tlbwi /* handwritten instruction */
    /* 9B7CC 8009ABCC 00000000 */  nop
    /* 9B7D0 8009ABD0 00000000 */  nop
    /* 9B7D4 8009ABD4 00000000 */  nop
    /* 9B7D8 8009ABD8 00000000 */  nop
    /* 9B7DC 8009ABDC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 9B7E0 8009ABE0 03E00008 */  jr         $ra
    /* 9B7E4 8009ABE4 00000000 */   nop
endlabel osMapTLBRdb
    /* 9B7E8 8009ABE8 00000000 */  nop
    /* 9B7EC 8009ABEC 00000000 */  nop
