.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching __osSetCompare, 0xC

glabel __osSetCompare
    /* 9DFA0 8009D3A0 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
    /* 9DFA4 8009D3A4 03E00008 */  jr         $ra
    /* 9DFA8 8009D3A8 00000000 */   nop
endlabel __osSetCompare
    /* 9DFAC 8009D3AC 00000000 */  nop
