.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

nonmatching __osSetFpcCsr, 0x10

glabel __osSetFpcCsr
    /* 9B690 8009AA90 4442F800 */  cfc1       $v0, $31
    /* 9B694 8009AA94 44C4F800 */  ctc1       $a0, $31
    /* 9B698 8009AA98 03E00008 */  jr         $ra
    /* 9B69C 8009AA9C 00000000 */   nop
endlabel __osSetFpcCsr
