.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching __osSetSR, 0x10

glabel __osSetSR
    /* 9B670 8009AA70 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
    /* 9B674 8009AA74 00000000 */  nop
    /* 9B678 8009AA78 03E00008 */  jr         $ra
    /* 9B67C 8009AA7C 00000000 */   nop
endlabel __osSetSR
