.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel __osDisableInt
    /* 9A880 80099C80 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 9A884 80099C84 2401FFFE */  addiu      $at, $zero, -0x2
    /* 9A888 80099C88 01014824 */  and        $t1, $t0, $at
    /* 9A88C 80099C8C 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 9A890 80099C90 31020001 */  andi       $v0, $t0, 0x1
    /* 9A894 80099C94 00000000 */  nop
    /* 9A898 80099C98 03E00008 */  jr         $ra
    /* 9A89C 80099C9C 00000000 */   nop
