.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel __osLeoInterrupt
    /* 751F0 800745F0 03E00008 */  jr         $ra
    /* 751F4 800745F4 00001025 */   or        $v0, $zero, $zero
    /* 751F8 800745F8 00000000 */  nop
    /* 751FC 800745FC 00000000 */  nop
