.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel _blkclr
    /* 97DC0 800971C0 28A1000C */  slti       $at, $a1, 0xC
    /* 97DC4 800971C4 1420001D */  bnez       $at, .L8009723C_97E3C
    /* 97DC8 800971C8 00041823 */   negu      $v1, $a0
    /* 97DCC 800971CC 30630003 */  andi       $v1, $v1, 0x3
    /* 97DD0 800971D0 10600003 */  beqz       $v1, .L800971E0_97DE0
    /* 97DD4 800971D4 00A32823 */   subu      $a1, $a1, $v1
    /* 97DD8 800971D8 A8800000 */  swl        $zero, 0x0($a0)
    /* 97DDC 800971DC 00832021 */  addu       $a0, $a0, $v1
  .L800971E0_97DE0:
    /* 97DE0 800971E0 2401FFE0 */  addiu      $at, $zero, -0x20
    /* 97DE4 800971E4 00A13824 */  and        $a3, $a1, $at
    /* 97DE8 800971E8 10E0000C */  beqz       $a3, .L8009721C_97E1C
    /* 97DEC 800971EC 00A72823 */   subu      $a1, $a1, $a3
    /* 97DF0 800971F0 00E43821 */  addu       $a3, $a3, $a0
  .L800971F4_97DF4:
    /* 97DF4 800971F4 24840020 */  addiu      $a0, $a0, 0x20
    /* 97DF8 800971F8 AC80FFE0 */  sw         $zero, -0x20($a0)
    /* 97DFC 800971FC AC80FFE4 */  sw         $zero, -0x1C($a0)
    /* 97E00 80097200 AC80FFE8 */  sw         $zero, -0x18($a0)
    /* 97E04 80097204 AC80FFEC */  sw         $zero, -0x14($a0)
    /* 97E08 80097208 AC80FFF0 */  sw         $zero, -0x10($a0)
    /* 97E0C 8009720C AC80FFF4 */  sw         $zero, -0xC($a0)
    /* 97E10 80097210 AC80FFF8 */  sw         $zero, -0x8($a0)
    /* 97E14 80097214 1487FFF7 */  bne        $a0, $a3, .L800971F4_97DF4
    /* 97E18 80097218 AC80FFFC */   sw        $zero, -0x4($a0)
  .L8009721C_97E1C:
    /* 97E1C 8009721C 2401FFFC */  addiu      $at, $zero, -0x4
    /* 97E20 80097220 00A13824 */  and        $a3, $a1, $at
    /* 97E24 80097224 10E00005 */  beqz       $a3, .L8009723C_97E3C
    /* 97E28 80097228 00A72823 */   subu      $a1, $a1, $a3
    /* 97E2C 8009722C 00E43821 */  addu       $a3, $a3, $a0
  .L80097230_97E30:
    /* 97E30 80097230 24840004 */  addiu      $a0, $a0, 0x4
    /* 97E34 80097234 1487FFFE */  bne        $a0, $a3, .L80097230_97E30
    /* 97E38 80097238 AC80FFFC */   sw        $zero, -0x4($a0)
  .L8009723C_97E3C:
    /* 97E3C 8009723C 18A00005 */  blez       $a1, .L80097254_97E54
    /* 97E40 80097240 00000000 */   nop
    /* 97E44 80097244 00A42821 */  addu       $a1, $a1, $a0
  .L80097248_97E48:
    /* 97E48 80097248 24840001 */  addiu      $a0, $a0, 0x1
    /* 97E4C 8009724C 1485FFFE */  bne        $a0, $a1, .L80097248_97E48
    /* 97E50 80097250 A080FFFF */   sb        $zero, -0x1($a0)
  .L80097254_97E54:
    /* 97E54 80097254 03E00008 */  jr         $ra
    /* 97E58 80097258 00000000 */   nop
    /* 97E5C 8009725C 00000000 */  nop
