.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel __osExceptionPreamble
    /* 763A0 800757A0 3C1A8007 */  lui        $k0, %hi(__osException) /* handwritten instruction */
    /* 763A4 800757A4 275A57B0 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
    /* 763A8 800757A8 03400008 */  jr         $k0
    /* 763AC 800757AC 00000000 */   nop

/* Handwritten function */
glabel __osException
    /* 763B0 800757B0 3C1A8010 */  lui        $k0, %hi(D_80106280_106E80) /* handwritten instruction */
    /* 763B4 800757B4 275A6280 */  addiu      $k0, $k0, %lo(D_80106280_106E80) /* handwritten instruction */
    /* 763B8 800757B8 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* 763BC 800757BC 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* 763C0 800757C0 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 763C4 800757C4 2401FFFC */  addiu      $at, $zero, -0x4
    /* 763C8 800757C8 0361D824 */  and        $k1, $k1, $at
    /* 763CC 800757CC 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 763D0 800757D0 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* 763D4 800757D4 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 763D8 800757D8 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* 763DC 800757DC AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* 763E0 800757E0 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 763E4 800757E4 03404025 */  or         $t0, $k0, $zero
    /* 763E8 800757E8 3C1A800B */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* 763EC 800757EC 8F5AA840 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* 763F0 800757F0 DD090020 */  ld         $t1, 0x20($t0)
    /* 763F4 800757F4 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* 763F8 800757F8 DD090118 */  ld         $t1, 0x118($t0)
    /* 763FC 800757FC FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* 76400 80075800 DD090058 */  ld         $t1, 0x58($t0)
    /* 76404 80075804 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* 76408 80075808 DD090060 */  ld         $t1, 0x60($t0)
    /* 7640C 8007580C FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 76410 80075810 DD090068 */  ld         $t1, 0x68($t0)
    /* 76414 80075814 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
    /* 76418 80075818 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 7641C 8007581C 00004012 */  mflo       $t0
    /* 76420 80075820 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* 76424 80075824 00004010 */  mfhi       $t0
    /* 76428 80075828 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 7642C 8007582C FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* 76430 80075830 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* 76434 80075834 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* 76438 80075838 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* 7643C 8007583C FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* 76440 80075840 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* 76444 80075844 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* 76448 80075848 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* 7644C 8007584C FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* 76450 80075850 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* 76454 80075854 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* 76458 80075858 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* 7645C 8007585C FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* 76460 80075860 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* 76464 80075864 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* 76468 80075868 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* 7646C 8007586C FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* 76470 80075870 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* 76474 80075874 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* 76478 80075878 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* 7647C 8007587C FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* 76480 80075880 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* 76484 80075884 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* 76488 80075888 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* 7648C 8007588C FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* 76490 80075890 1120000D */  beqz       $t1, .L800758C8_764C8
    /* 76494 80075894 FF480110 */   sd        $t0, 0x110($k0) /* handwritten instruction */
    /* 76498 80075898 3C08800B */  lui        $t0, %hi(D_800AA40C_AB00C)
    /* 7649C 8007589C 2508A40C */  addiu      $t0, $t0, %lo(D_800AA40C_AB00C)
    /* 764A0 800758A0 8D080000 */  lw         $t0, 0x0($t0)
    /* 764A4 800758A4 2401FFFF */  addiu      $at, $zero, -0x1
    /* 764A8 800758A8 01014026 */  xor        $t0, $t0, $at
    /* 764AC 800758AC 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 764B0 800758B0 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 764B4 800758B4 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 764B8 800758B8 01284825 */  or         $t1, $t1, $t0
    /* 764BC 800758BC 0361D824 */  and        $k1, $k1, $at
    /* 764C0 800758C0 0369D825 */  or         $k1, $k1, $t1
    /* 764C4 800758C4 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
  .L800758C8_764C8:
    /* 764C8 800758C8 3C09A430 */  lui        $t1, %hi(MI_INTR_MASK_REG)
    /* 764CC 800758CC 8D29000C */  lw         $t1, %lo(MI_INTR_MASK_REG)($t1)
    /* 764D0 800758D0 5120000C */  beql       $t1, $zero, .L80075904_76504
    /* 764D4 800758D4 AF490128 */   sw        $t1, 0x128($k0) /* handwritten instruction */
    /* 764D8 800758D8 3C08800B */  lui        $t0, %hi(D_800AA40C_AB00C)
    /* 764DC 800758DC 2508A40C */  addiu      $t0, $t0, %lo(D_800AA40C_AB00C)
    /* 764E0 800758E0 8D080000 */  lw         $t0, 0x0($t0)
    /* 764E4 800758E4 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
    /* 764E8 800758E8 2401FFFF */  addiu      $at, $zero, -0x1
    /* 764EC 800758EC 00084402 */  srl        $t0, $t0, 16
    /* 764F0 800758F0 01014026 */  xor        $t0, $t0, $at
    /* 764F4 800758F4 3108003F */  andi       $t0, $t0, 0x3F
    /* 764F8 800758F8 010C4024 */  and        $t0, $t0, $t4
    /* 764FC 800758FC 01284825 */  or         $t1, $t1, $t0
    /* 76500 80075900 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
  .L80075904_76504:
    /* 76504 80075904 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* 76508 80075908 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* 7650C 8007590C 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* 76510 80075910 11000024 */  beqz       $t0, .L800759A4_765A4
    /* 76514 80075914 00000000 */   nop
    /* 76518 80075918 4448F800 */  cfc1       $t0, $31
    /* 7651C 8007591C 00000000 */  nop
    /* 76520 80075920 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* 76524 80075924 F7400130 */  sdc1       $f0, 0x130($k0)
    /* 76528 80075928 F7410138 */  sdc1       $f1, 0x138($k0)
    /* 7652C 8007592C F7420140 */  sdc1       $f2, 0x140($k0)
    /* 76530 80075930 F7430148 */  sdc1       $f3, 0x148($k0)
    /* 76534 80075934 F7440150 */  sdc1       $f4, 0x150($k0)
    /* 76538 80075938 F7450158 */  sdc1       $f5, 0x158($k0)
    /* 7653C 8007593C F7460160 */  sdc1       $f6, 0x160($k0)
    /* 76540 80075940 F7470168 */  sdc1       $f7, 0x168($k0)
    /* 76544 80075944 F7480170 */  sdc1       $f8, 0x170($k0)
    /* 76548 80075948 F7490178 */  sdc1       $f9, 0x178($k0)
    /* 7654C 8007594C F74A0180 */  sdc1       $f10, 0x180($k0)
    /* 76550 80075950 F74B0188 */  sdc1       $f11, 0x188($k0)
    /* 76554 80075954 F74C0190 */  sdc1       $f12, 0x190($k0)
    /* 76558 80075958 F74D0198 */  sdc1       $f13, 0x198($k0)
    /* 7655C 8007595C F74E01A0 */  sdc1       $f14, 0x1A0($k0)
    /* 76560 80075960 F74F01A8 */  sdc1       $f15, 0x1A8($k0)
    /* 76564 80075964 F75001B0 */  sdc1       $f16, 0x1B0($k0)
    /* 76568 80075968 F75101B8 */  sdc1       $f17, 0x1B8($k0)
    /* 7656C 8007596C F75201C0 */  sdc1       $f18, 0x1C0($k0)
    /* 76570 80075970 F75301C8 */  sdc1       $f19, 0x1C8($k0)
    /* 76574 80075974 F75401D0 */  sdc1       $f20, 0x1D0($k0)
    /* 76578 80075978 F75501D8 */  sdc1       $f21, 0x1D8($k0)
    /* 7657C 8007597C F75601E0 */  sdc1       $f22, 0x1E0($k0)
    /* 76580 80075980 F75701E8 */  sdc1       $f23, 0x1E8($k0)
    /* 76584 80075984 F75801F0 */  sdc1       $f24, 0x1F0($k0)
    /* 76588 80075988 F75901F8 */  sdc1       $f25, 0x1F8($k0)
    /* 7658C 8007598C F75A0200 */  sdc1       $f26, 0x200($k0)
    /* 76590 80075990 F75B0208 */  sdc1       $f27, 0x208($k0)
    /* 76594 80075994 F75C0210 */  sdc1       $f28, 0x210($k0)
    /* 76598 80075998 F75D0218 */  sdc1       $f29, 0x218($k0)
    /* 7659C 8007599C F75E0220 */  sdc1       $f30, 0x220($k0)
    /* 765A0 800759A0 F75F0228 */  sdc1       $f31, 0x228($k0)
  .L800759A4_765A4:
    /* 765A4 800759A4 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 765A8 800759A8 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* 765AC 800759AC 24090002 */  addiu      $t1, $zero, 0x2
    /* 765B0 800759B0 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 765B4 800759B4 3109007C */  andi       $t1, $t0, 0x7C
    /* 765B8 800759B8 240A0024 */  addiu      $t2, $zero, 0x24
    /* 765BC 800759BC 512A00B8 */  beql       $t1, $t2, .L80075CA0_768A0
    /* 765C0 800759C0 24090001 */   addiu     $t1, $zero, 0x1
    /* 765C4 800759C4 240A002C */  addiu      $t2, $zero, 0x2C
    /* 765C8 800759C8 112A0106 */  beq        $t1, $t2, handle_CpU
    /* 765CC 800759CC 00000000 */   nop
    /* 765D0 800759D0 240A0000 */  addiu      $t2, $zero, 0x0
    /* 765D4 800759D4 152A00CA */  bne        $t1, $t2, .L80075D00_76900
    /* 765D8 800759D8 00000000 */   nop
    /* 765DC 800759DC 03688024 */  and        $s0, $k1, $t0
  .L800759E0_765E0:
    /* 765E0 800759E0 3209FF00 */  andi       $t1, $s0, 0xFF00
  .L800759E4_765E4:
    /* 765E4 800759E4 00095302 */  srl        $t2, $t1, 12
    /* 765E8 800759E8 15400003 */  bnez       $t2, .L800759F8_765F8
    /* 765EC 800759EC 00000000 */   nop
    /* 765F0 800759F0 00095202 */  srl        $t2, $t1, 8
    /* 765F4 800759F4 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .L800759F8_765F8:
    /* 765F8 800759F8 3C01800B */  lui        $at, %hi(D_800AFAD0_B06D0)
    /* 765FC 800759FC 002A0821 */  addu       $at, $at, $t2
    /* 76600 80075A00 902AFAD0 */  lbu        $t2, %lo(D_800AFAD0_B06D0)($at)
    /* 76604 80075A04 3C01800B */  lui        $at, %hi(jtbl_800AFAF0_B06F0)
    /* 76608 80075A08 002A0821 */  addu       $at, $at, $t2
    /* 7660C 80075A0C 8C2AFAF0 */  lw         $t2, %lo(jtbl_800AFAF0_B06F0)($at)
    /* 76610 80075A10 01400008 */  jr         $t2
    /* 76614 80075A14 00000000 */   nop
    /* 76618 80075A18 2401DFFF */  addiu      $at, $zero, -0x2001
    /* 7661C 80075A1C 1000FFF0 */  b          .L800759E0_765E0
    /* 76620 80075A20 02018024 */   and       $s0, $s0, $at
    /* 76624 80075A24 2401BFFF */  addiu      $at, $zero, -0x4001
    /* 76628 80075A28 1000FFED */  b          .L800759E0_765E0
    /* 7662C 80075A2C 02018024 */   and       $s0, $s0, $at
    /* 76630 80075A30 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* 76634 80075A34 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* 76638 80075A38 0C01D74C */  jal        send_mesg
    /* 7663C 80075A3C 24040018 */   addiu     $a0, $zero, 0x18
    /* 76640 80075A40 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* 76644 80075A44 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* 76648 80075A48 1000FFE5 */  b          .L800759E0_765E0
    /* 7664C 80075A4C 02018024 */   and       $s0, $s0, $at
    /* 76650 80075A50 3C09800A */  lui        $t1, %hi(D_800A7E40_A8A40)
    /* 76654 80075A54 25297E40 */  addiu      $t1, $t1, %lo(D_800A7E40_A8A40)
    /* 76658 80075A58 8D2A0008 */  lw         $t2, 0x8($t1)
    /* 7665C 80075A5C 2401F7FF */  addiu      $at, $zero, -0x801
    /* 76660 80075A60 02018024 */  and        $s0, $s0, $at
    /* 76664 80075A64 11400007 */  beqz       $t2, .L80075A84_76684
    /* 76668 80075A68 21290008 */   addi      $t1, $t1, 0x8 /* handwritten instruction */
    /* 7666C 80075A6C 0140F809 */  jalr       $t2
    /* 76670 80075A70 8D3D0004 */   lw        $sp, 0x4($t1)
    /* 76674 80075A74 10400003 */  beqz       $v0, .L80075A84_76684
    /* 76678 80075A78 00000000 */   nop
    /* 7667C 80075A7C 1000008D */  b          .L80075CB4_768B4
    /* 76680 80075A80 00000000 */   nop
  .L80075A84_76684:
    /* 76684 80075A84 0C01D74C */  jal        send_mesg
    /* 76688 80075A88 24040010 */   addiu     $a0, $zero, 0x10
    /* 7668C 80075A8C 1000FFD5 */  b          .L800759E4_765E4
    /* 76690 80075A90 3209FF00 */   andi      $t1, $s0, 0xFF00
    /* 76694 80075A94 3C08800B */  lui        $t0, %hi(D_800AA40C_AB00C)
    /* 76698 80075A98 2508A40C */  addiu      $t0, $t0, %lo(D_800AA40C_AB00C)
    /* 7669C 80075A9C 8D080000 */  lw         $t0, 0x0($t0)
    /* 766A0 80075AA0 3C11A430 */  lui        $s1, %hi(MI_INTR_REG)
    /* 766A4 80075AA4 8E310008 */  lw         $s1, %lo(MI_INTR_REG)($s1)
    /* 766A8 80075AA8 00084402 */  srl        $t0, $t0, 16
    /* 766AC 80075AAC 02288824 */  and        $s1, $s1, $t0
    /* 766B0 80075AB0 32290001 */  andi       $t1, $s1, 0x1
    /* 766B4 80075AB4 51200014 */  beql       $t1, $zero, .L80075B08_76708
    /* 766B8 80075AB8 32290008 */   andi      $t1, $s1, 0x8
    /* 766BC 80075ABC 3C0CA404 */  lui        $t4, %hi(SP_STATUS_REG)
    /* 766C0 80075AC0 8D8C0010 */  lw         $t4, %lo(SP_STATUS_REG)($t4)
    /* 766C4 80075AC4 24090008 */  addiu      $t1, $zero, 0x8
    /* 766C8 80075AC8 3C01A404 */  lui        $at, %hi(SP_STATUS_REG)
    /* 766CC 80075ACC 318C0300 */  andi       $t4, $t4, 0x300
    /* 766D0 80075AD0 3231003E */  andi       $s1, $s1, 0x3E
    /* 766D4 80075AD4 11800007 */  beqz       $t4, .L80075AF4_766F4
    /* 766D8 80075AD8 AC290010 */   sw        $t1, %lo(SP_STATUS_REG)($at)
    /* 766DC 80075ADC 0C01D74C */  jal        send_mesg
    /* 766E0 80075AE0 24040020 */   addiu     $a0, $zero, 0x20
    /* 766E4 80075AE4 52200043 */  beql       $s1, $zero, .L80075BF4_767F4
    /* 766E8 80075AE8 2401FBFF */   addiu     $at, $zero, -0x401
    /* 766EC 80075AEC 10000006 */  b          .L80075B08_76708
    /* 766F0 80075AF0 32290008 */   andi      $t1, $s1, 0x8
  .L80075AF4_766F4:
    /* 766F4 80075AF4 0C01D74C */  jal        send_mesg
    /* 766F8 80075AF8 24040058 */   addiu     $a0, $zero, 0x58
    /* 766FC 80075AFC 5220003D */  beql       $s1, $zero, .L80075BF4_767F4
    /* 76700 80075B00 2401FBFF */   addiu     $at, $zero, -0x401
    /* 76704 80075B04 32290008 */  andi       $t1, $s1, 0x8
  .L80075B08_76708:
    /* 76708 80075B08 11200007 */  beqz       $t1, .L80075B28_76728
    /* 7670C 80075B0C 3C01A440 */   lui       $at, %hi(VI_V_CURRENT_LINE_REG)
    /* 76710 80075B10 32310037 */  andi       $s1, $s1, 0x37
    /* 76714 80075B14 AC200010 */  sw         $zero, %lo(VI_V_CURRENT_LINE_REG)($at)
    /* 76718 80075B18 0C01D74C */  jal        send_mesg
    /* 7671C 80075B1C 24040038 */   addiu     $a0, $zero, 0x38
    /* 76720 80075B20 52200034 */  beql       $s1, $zero, .L80075BF4_767F4
    /* 76724 80075B24 2401FBFF */   addiu     $at, $zero, -0x401
  .L80075B28_76728:
    /* 76728 80075B28 32290004 */  andi       $t1, $s1, 0x4
    /* 7672C 80075B2C 5120000A */  beql       $t1, $zero, .L80075B58_76758
    /* 76730 80075B30 32290002 */   andi      $t1, $s1, 0x2
    /* 76734 80075B34 24090001 */  addiu      $t1, $zero, 0x1
    /* 76738 80075B38 3C01A450 */  lui        $at, %hi(AI_STATUS_REG)
    /* 7673C 80075B3C 3231003B */  andi       $s1, $s1, 0x3B
    /* 76740 80075B40 AC29000C */  sw         $t1, %lo(AI_STATUS_REG)($at)
    /* 76744 80075B44 0C01D74C */  jal        send_mesg
    /* 76748 80075B48 24040030 */   addiu     $a0, $zero, 0x30
    /* 7674C 80075B4C 52200029 */  beql       $s1, $zero, .L80075BF4_767F4
    /* 76750 80075B50 2401FBFF */   addiu     $at, $zero, -0x401
    /* 76754 80075B54 32290002 */  andi       $t1, $s1, 0x2
  .L80075B58_76758:
    /* 76758 80075B58 11200007 */  beqz       $t1, .L80075B78_76778
    /* 7675C 80075B5C 3C01A480 */   lui       $at, %hi(SI_STATUS_REG)
    /* 76760 80075B60 3231003D */  andi       $s1, $s1, 0x3D
    /* 76764 80075B64 AC200018 */  sw         $zero, %lo(SI_STATUS_REG)($at)
    /* 76768 80075B68 0C01D74C */  jal        send_mesg
    /* 7676C 80075B6C 24040028 */   addiu     $a0, $zero, 0x28
    /* 76770 80075B70 52200020 */  beql       $s1, $zero, .L80075BF4_767F4
    /* 76774 80075B74 2401FBFF */   addiu     $at, $zero, -0x401
  .L80075B78_76778:
    /* 76778 80075B78 32290010 */  andi       $t1, $s1, 0x10
    /* 7677C 80075B7C 51200014 */  beql       $t1, $zero, .L80075BD0_767D0
    /* 76780 80075B80 32290020 */   andi      $t1, $s1, 0x20
    /* 76784 80075B84 24090002 */  addiu      $t1, $zero, 0x2
    /* 76788 80075B88 3C01A460 */  lui        $at, %hi(PI_STATUS_REG)
    /* 7678C 80075B8C AC290010 */  sw         $t1, %lo(PI_STATUS_REG)($at)
    /* 76790 80075B90 3C09800A */  lui        $t1, %hi(D_800A7E68_A8A68)
    /* 76794 80075B94 25297E68 */  addiu      $t1, $t1, %lo(D_800A7E68_A8A68)
    /* 76798 80075B98 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 7679C 80075B9C 3231002F */  andi       $s1, $s1, 0x2F
    /* 767A0 80075BA0 11400006 */  beqz       $t2, .L80075BBC_767BC
    /* 767A4 80075BA4 00000000 */   nop
    /* 767A8 80075BA8 8D3D0004 */  lw         $sp, 0x4($t1)
    /* 767AC 80075BAC 0140F809 */  jalr       $t2
    /* 767B0 80075BB0 00402025 */   or        $a0, $v0, $zero
    /* 767B4 80075BB4 144000CA */  bnez       $v0, .L80075EE0_76AE0
    /* 767B8 80075BB8 00000000 */   nop
  .L80075BBC_767BC:
    /* 767BC 80075BBC 0C01D74C */  jal        send_mesg
    /* 767C0 80075BC0 24040040 */   addiu     $a0, $zero, 0x40
    /* 767C4 80075BC4 5220000B */  beql       $s1, $zero, .L80075BF4_767F4
    /* 767C8 80075BC8 2401FBFF */   addiu     $at, $zero, -0x401
    /* 767CC 80075BCC 32290020 */  andi       $t1, $s1, 0x20
  .L80075BD0_767D0:
    /* 767D0 80075BD0 51200008 */  beql       $t1, $zero, .L80075BF4_767F4
    /* 767D4 80075BD4 2401FBFF */   addiu     $at, $zero, -0x401
    /* 767D8 80075BD8 24090800 */  addiu      $t1, $zero, 0x800
    /* 767DC 80075BDC 3C01A430 */  lui        $at, %hi(MI_MODE_REG)
    /* 767E0 80075BE0 3231001F */  andi       $s1, $s1, 0x1F
    /* 767E4 80075BE4 AC290000 */  sw         $t1, %lo(MI_MODE_REG)($at)
    /* 767E8 80075BE8 0C01D74C */  jal        send_mesg
    /* 767EC 80075BEC 24040048 */   addiu     $a0, $zero, 0x48
    /* 767F0 80075BF0 2401FBFF */  addiu      $at, $zero, -0x401
  .L80075BF4_767F4:
    /* 767F4 80075BF4 1000FF7A */  b          .L800759E0_765E0
    /* 767F8 80075BF8 02018024 */   and       $s0, $s0, $at
    /* 767FC 80075BFC 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 76800 80075C00 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 76804 80075C04 3C09800B */  lui        $t1, %hi(D_800AA408_AB008)
    /* 76808 80075C08 0361D824 */  and        $k1, $k1, $at
    /* 7680C 80075C0C AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 76810 80075C10 2529A408 */  addiu      $t1, $t1, %lo(D_800AA408_AB008)
    /* 76814 80075C14 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 76818 80075C18 11400003 */  beqz       $t2, .L80075C28_76828
    /* 7681C 80075C1C 2401EFFF */   addiu     $at, $zero, -0x1001
    /* 76820 80075C20 10000024 */  b          .L80075CB4_768B4
    /* 76824 80075C24 02018024 */   and       $s0, $s0, $at
  .L80075C28_76828:
    /* 76828 80075C28 240A0001 */  addiu      $t2, $zero, 0x1
    /* 7682C 80075C2C AD2A0000 */  sw         $t2, 0x0($t1)
    /* 76830 80075C30 0C01D74C */  jal        send_mesg
    /* 76834 80075C34 24040070 */   addiu     $a0, $zero, 0x70
    /* 76838 80075C38 3C0A800B */  lui        $t2, %hi(D_800AA838_AB438)
    /* 7683C 80075C3C 8D4AA838 */  lw         $t2, %lo(D_800AA838_AB438)($t2)
    /* 76840 80075C40 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 76844 80075C44 02018024 */  and        $s0, $s0, $at
    /* 76848 80075C48 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* 7684C 80075C4C 0361D824 */  and        $k1, $k1, $at
    /* 76850 80075C50 10000018 */  b          .L80075CB4_768B4
    /* 76854 80075C54 AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
    /* 76858 80075C58 2401FDFF */  addiu      $at, $zero, -0x201
    /* 7685C 80075C5C 01014024 */  and        $t0, $t0, $at
    /* 76860 80075C60 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 76864 80075C64 0C01D74C */  jal        send_mesg
    /* 76868 80075C68 24040008 */   addiu     $a0, $zero, 0x8
    /* 7686C 80075C6C 2401FDFF */  addiu      $at, $zero, -0x201
    /* 76870 80075C70 1000FF5B */  b          .L800759E0_765E0
    /* 76874 80075C74 02018024 */   and       $s0, $s0, $at
    /* 76878 80075C78 2401FEFF */  addiu      $at, $zero, -0x101
    /* 7687C 80075C7C 01014024 */  and        $t0, $t0, $at
    /* 76880 80075C80 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 76884 80075C84 0C01D74C */  jal        send_mesg
    /* 76888 80075C88 24040000 */   addiu     $a0, $zero, 0x0
    /* 7688C 80075C8C 2401FEFF */  addiu      $at, $zero, -0x101
    /* 76890 80075C90 1000FF53 */  b          .L800759E0_765E0
    /* 76894 80075C94 02018024 */   and       $s0, $s0, $at
    /* 76898 80075C98 00000000 */  nop
    /* 7689C 80075C9C 24090001 */  addiu      $t1, $zero, 0x1
  .L80075CA0_768A0:
    /* 768A0 80075CA0 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 768A4 80075CA4 0C01D74C */  jal        send_mesg
    /* 768A8 80075CA8 24040050 */   addiu     $a0, $zero, 0x50
    /* 768AC 80075CAC 10000001 */  b          .L80075CB4_768B4
    /* 768B0 80075CB0 00000000 */   nop
  .L80075CB4_768B4:
    /* 768B4 80075CB4 3C0A800B */  lui        $t2, %hi(D_800AA838_AB438)
    /* 768B8 80075CB8 8D4AA838 */  lw         $t2, %lo(D_800AA838_AB438)($t2)
    /* 768BC 80075CBC 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* 768C0 80075CC0 8D4B0004 */  lw         $t3, 0x4($t2)
    /* 768C4 80075CC4 012B082A */  slt        $at, $t1, $t3
    /* 768C8 80075CC8 10200007 */  beqz       $at, .L80075CE8_768E8
    /* 768CC 80075CCC 00000000 */   nop
    /* 768D0 80075CD0 3C04800B */  lui        $a0, %hi(D_800AA838_AB438)
    /* 768D4 80075CD4 03402825 */  or         $a1, $k0, $zero
    /* 768D8 80075CD8 0C01D7CC */  jal        __osEnqueueThread
    /* 768DC 80075CDC 2484A838 */   addiu     $a0, $a0, %lo(D_800AA838_AB438)
    /* 768E0 80075CE0 0801D7E2 */  j          __osDispatchThread
    /* 768E4 80075CE4 00000000 */   nop
  .L80075CE8_768E8:
    /* 768E8 80075CE8 3C09800B */  lui        $t1, %hi(D_800AA838_AB438)
    /* 768EC 80075CEC 2529A838 */  addiu      $t1, $t1, %lo(D_800AA838_AB438)
    /* 768F0 80075CF0 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 768F4 80075CF4 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* 768F8 80075CF8 0801D7E2 */  j          __osDispatchThread
    /* 768FC 80075CFC AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .L80075D00_76900:
    /* 76900 80075D00 3C01800B */  lui        $at, %hi(D_800AA844_AB444)
    /* 76904 80075D04 AC3AA844 */  sw         $k0, %lo(D_800AA844_AB444)($at) /* handwritten instruction */
    /* 76908 80075D08 24090001 */  addiu      $t1, $zero, 0x1
    /* 7690C 80075D0C A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 76910 80075D10 24090002 */  addiu      $t1, $zero, 0x2
    /* 76914 80075D14 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 76918 80075D18 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* 7691C 80075D1C AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* 76920 80075D20 0C01D74C */  jal        send_mesg
    /* 76924 80075D24 24040060 */   addiu     $a0, $zero, 0x60
    /* 76928 80075D28 0801D7E2 */  j          __osDispatchThread
    /* 7692C 80075D2C 00000000 */   nop

glabel send_mesg
    /* 76930 80075D30 3C0A8010 */  lui        $t2, %hi(D_80105D10_106910)
    /* 76934 80075D34 254A5D10 */  addiu      $t2, $t2, %lo(D_80105D10_106910)
    /* 76938 80075D38 01445021 */  addu       $t2, $t2, $a0
    /* 7693C 80075D3C 8D490000 */  lw         $t1, 0x0($t2)
    /* 76940 80075D40 03E09025 */  or         $s2, $ra, $zero
    /* 76944 80075D44 11200025 */  beqz       $t1, .L80075DDC_769DC
    /* 76948 80075D48 00000000 */   nop
    /* 7694C 80075D4C 8D2B0008 */  lw         $t3, 0x8($t1)
    /* 76950 80075D50 8D2C0010 */  lw         $t4, 0x10($t1)
    /* 76954 80075D54 016C082A */  slt        $at, $t3, $t4
    /* 76958 80075D58 10200020 */  beqz       $at, .L80075DDC_769DC
    /* 7695C 80075D5C 00000000 */   nop
    /* 76960 80075D60 8D2D000C */  lw         $t5, 0xC($t1)
    /* 76964 80075D64 01AB6821 */  addu       $t5, $t5, $t3
    /* 76968 80075D68 01AC001A */  div        $zero, $t5, $t4
    /* 7696C 80075D6C 15800002 */  bnez       $t4, .L80075D78_76978
    /* 76970 80075D70 00000000 */   nop
    /* 76974 80075D74 0007000D */  break      7
  .L80075D78_76978:
    /* 76978 80075D78 2401FFFF */  addiu      $at, $zero, -0x1
    /* 7697C 80075D7C 15810004 */  bne        $t4, $at, .L80075D90_76990
    /* 76980 80075D80 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 76984 80075D84 15A10002 */  bne        $t5, $at, .L80075D90_76990
    /* 76988 80075D88 00000000 */   nop
    /* 7698C 80075D8C 0006000D */  break      6
  .L80075D90_76990:
    /* 76990 80075D90 8D2C0014 */  lw         $t4, 0x14($t1)
    /* 76994 80075D94 00006810 */  mfhi       $t5
    /* 76998 80075D98 000D6880 */  sll        $t5, $t5, 2
    /* 7699C 80075D9C 018D6021 */  addu       $t4, $t4, $t5
    /* 769A0 80075DA0 8D4D0004 */  lw         $t5, 0x4($t2)
    /* 769A4 80075DA4 256A0001 */  addiu      $t2, $t3, 0x1
    /* 769A8 80075DA8 AD8D0000 */  sw         $t5, 0x0($t4)
    /* 769AC 80075DAC AD2A0008 */  sw         $t2, 0x8($t1)
    /* 769B0 80075DB0 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 769B4 80075DB4 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 769B8 80075DB8 11600008 */  beqz       $t3, .L80075DDC_769DC
    /* 769BC 80075DBC 00000000 */   nop
    /* 769C0 80075DC0 0C01D7DE */  jal        __osPopThread
    /* 769C4 80075DC4 01202025 */   or        $a0, $t1, $zero
    /* 769C8 80075DC8 00405025 */  or         $t2, $v0, $zero
    /* 769CC 80075DCC 3C04800B */  lui        $a0, %hi(D_800AA838_AB438)
    /* 769D0 80075DD0 01402825 */  or         $a1, $t2, $zero
    /* 769D4 80075DD4 0C01D7CC */  jal        __osEnqueueThread
    /* 769D8 80075DD8 2484A838 */   addiu     $a0, $a0, %lo(D_800AA838_AB438)
  .L80075DDC_769DC:
    /* 769DC 80075DDC 02400008 */  jr         $s2
    /* 769E0 80075DE0 00000000 */   nop

/* Handwritten function */
glabel handle_CpU
    /* 769E4 80075DE4 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* 769E8 80075DE8 01014824 */  and        $t1, $t0, $at
    /* 769EC 80075DEC 00094F02 */  srl        $t1, $t1, 28
    /* 769F0 80075DF0 240A0001 */  addiu      $t2, $zero, 0x1
    /* 769F4 80075DF4 152AFFC2 */  bne        $t1, $t2, .L80075D00_76900
    /* 769F8 80075DF8 00000000 */   nop
    /* 769FC 80075DFC 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 76A00 80075E00 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* 76A04 80075E04 24090001 */  addiu      $t1, $zero, 0x1
    /* 76A08 80075E08 0361D825 */  or         $k1, $k1, $at
    /* 76A0C 80075E0C AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* 76A10 80075E10 1000FFB5 */  b          .L80075CE8_768E8
    /* 76A14 80075E14 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */

/* Handwritten function */
glabel __osEnqueueAndYield
    /* 76A18 80075E18 3C05800B */  lui        $a1, %hi(__osRunningThread)
    /* 76A1C 80075E1C 8CA5A840 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* 76A20 80075E20 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 76A24 80075E24 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* 76A28 80075E28 35080002 */  ori        $t0, $t0, 0x2
    /* 76A2C 80075E2C ACA80118 */  sw         $t0, 0x118($a1)
    /* 76A30 80075E30 FCB00098 */  sd         $s0, 0x98($a1)
    /* 76A34 80075E34 FCB100A0 */  sd         $s1, 0xA0($a1)
    /* 76A38 80075E38 FCB200A8 */  sd         $s2, 0xA8($a1)
    /* 76A3C 80075E3C FCB300B0 */  sd         $s3, 0xB0($a1)
    /* 76A40 80075E40 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* 76A44 80075E44 FCB500C0 */  sd         $s5, 0xC0($a1)
    /* 76A48 80075E48 FCB600C8 */  sd         $s6, 0xC8($a1)
    /* 76A4C 80075E4C FCB700D0 */  sd         $s7, 0xD0($a1)
    /* 76A50 80075E50 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* 76A54 80075E54 FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* 76A58 80075E58 FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* 76A5C 80075E5C FCBF0100 */  sd         $ra, 0x100($a1)
    /* 76A60 80075E60 1360000F */  beqz       $k1, .L80075EA0_76AA0 /* handwritten instruction */
    /* 76A64 80075E64 ACBF011C */   sw        $ra, 0x11C($a1)
    /* 76A68 80075E68 445BF800 */  cfc1       $k1, $31
    /* 76A6C 80075E6C F4B401D0 */  sdc1       $f20, 0x1D0($a1)
    /* 76A70 80075E70 F4B501D8 */  sdc1       $f21, 0x1D8($a1)
    /* 76A74 80075E74 F4B601E0 */  sdc1       $f22, 0x1E0($a1)
    /* 76A78 80075E78 F4B701E8 */  sdc1       $f23, 0x1E8($a1)
    /* 76A7C 80075E7C F4B801F0 */  sdc1       $f24, 0x1F0($a1)
    /* 76A80 80075E80 F4B901F8 */  sdc1       $f25, 0x1F8($a1)
    /* 76A84 80075E84 F4BA0200 */  sdc1       $f26, 0x200($a1)
    /* 76A88 80075E88 F4BB0208 */  sdc1       $f27, 0x208($a1)
    /* 76A8C 80075E8C F4BC0210 */  sdc1       $f28, 0x210($a1)
    /* 76A90 80075E90 F4BD0218 */  sdc1       $f29, 0x218($a1)
    /* 76A94 80075E94 F4BE0220 */  sdc1       $f30, 0x220($a1)
    /* 76A98 80075E98 F4BF0228 */  sdc1       $f31, 0x228($a1)
    /* 76A9C 80075E9C ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
  .L80075EA0_76AA0:
    /* 76AA0 80075EA0 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
    /* 76AA4 80075EA4 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 76AA8 80075EA8 5120000E */  beql       $t1, $zero, .L80075EE4_76AE4
    /* 76AAC 80075EAC 3C1BA430 */   lui       $k1, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
    /* 76AB0 80075EB0 3C08800B */  lui        $t0, %hi(D_800AA40C_AB00C)
    /* 76AB4 80075EB4 2508A40C */  addiu      $t0, $t0, %lo(D_800AA40C_AB00C)
    /* 76AB8 80075EB8 8D080000 */  lw         $t0, 0x0($t0)
    /* 76ABC 80075EBC 2401FFFF */  addiu      $at, $zero, -0x1
    /* 76AC0 80075EC0 01014026 */  xor        $t0, $t0, $at
    /* 76AC4 80075EC4 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 76AC8 80075EC8 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 76ACC 80075ECC 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 76AD0 80075ED0 01284825 */  or         $t1, $t1, $t0
    /* 76AD4 80075ED4 0361D824 */  and        $k1, $k1, $at
    /* 76AD8 80075ED8 0369D825 */  or         $k1, $k1, $t1
    /* 76ADC 80075EDC ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
  .L80075EE0_76AE0:
    /* 76AE0 80075EE0 3C1BA430 */  lui        $k1, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
  .L80075EE4_76AE4:
    /* 76AE4 80075EE4 8F7B000C */  lw         $k1, %lo(MI_INTR_MASK_REG)($k1) /* handwritten instruction */
    /* 76AE8 80075EE8 1360000B */  beqz       $k1, .L80075F18_76B18 /* handwritten instruction */
    /* 76AEC 80075EEC 00000000 */   nop
    /* 76AF0 80075EF0 3C1A800B */  lui        $k0, %hi(D_800AA40C_AB00C) /* handwritten instruction */
    /* 76AF4 80075EF4 275AA40C */  addiu      $k0, $k0, %lo(D_800AA40C_AB00C) /* handwritten instruction */
    /* 76AF8 80075EF8 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 76AFC 80075EFC 8CA80128 */  lw         $t0, 0x128($a1)
    /* 76B00 80075F00 2401FFFF */  addiu      $at, $zero, -0x1
    /* 76B04 80075F04 001AD402 */  srl        $k0, $k0, 16
    /* 76B08 80075F08 0341D026 */  xor        $k0, $k0, $at
    /* 76B0C 80075F0C 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
    /* 76B10 80075F10 0348D024 */  and        $k0, $k0, $t0
    /* 76B14 80075F14 037AD825 */  or         $k1, $k1, $k0
  .L80075F18_76B18:
    /* 76B18 80075F18 10800003 */  beqz       $a0, .L80075F28_76B28
    /* 76B1C 80075F1C ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* 76B20 80075F20 0C01D7CC */  jal        __osEnqueueThread
    /* 76B24 80075F24 00000000 */   nop
  .L80075F28_76B28:
    /* 76B28 80075F28 0801D7E2 */  j          __osDispatchThread
    /* 76B2C 80075F2C 00000000 */   nop

glabel __osEnqueueThread
    /* 76B30 80075F30 8C980000 */  lw         $t8, 0x0($a0)
    /* 76B34 80075F34 8CAF0004 */  lw         $t7, 0x4($a1)
    /* 76B38 80075F38 0080C825 */  or         $t9, $a0, $zero
    /* 76B3C 80075F3C 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 76B40 80075F40 01CF082A */  slt        $at, $t6, $t7
    /* 76B44 80075F44 54200008 */  bnel       $at, $zero, .L80075F68_76B68
    /* 76B48 80075F48 8F380000 */   lw        $t8, 0x0($t9)
    /* 76B4C 80075F4C 0300C825 */  or         $t9, $t8, $zero
  .L80075F50_76B50:
    /* 76B50 80075F50 8F180000 */  lw         $t8, 0x0($t8)
    /* 76B54 80075F54 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 76B58 80075F58 01CF082A */  slt        $at, $t6, $t7
    /* 76B5C 80075F5C 5020FFFC */  beql       $at, $zero, .L80075F50_76B50
    /* 76B60 80075F60 0300C825 */   or        $t9, $t8, $zero
    /* 76B64 80075F64 8F380000 */  lw         $t8, 0x0($t9)
  .L80075F68_76B68:
    /* 76B68 80075F68 ACB80000 */  sw         $t8, 0x0($a1)
    /* 76B6C 80075F6C AF250000 */  sw         $a1, 0x0($t9)
    /* 76B70 80075F70 03E00008 */  jr         $ra
    /* 76B74 80075F74 ACA40008 */   sw        $a0, 0x8($a1)

glabel __osPopThread
    /* 76B78 80075F78 8C820000 */  lw         $v0, 0x0($a0)
    /* 76B7C 80075F7C 8C590000 */  lw         $t9, 0x0($v0)
    /* 76B80 80075F80 03E00008 */  jr         $ra
    /* 76B84 80075F84 AC990000 */   sw        $t9, 0x0($a0)

/* Handwritten function */
glabel __osDispatchThread
    /* 76B88 80075F88 3C04800B */  lui        $a0, %hi(D_800AA838_AB438)
    /* 76B8C 80075F8C 0C01D7DE */  jal        __osPopThread
    /* 76B90 80075F90 2484A838 */   addiu     $a0, $a0, %lo(D_800AA838_AB438)
    /* 76B94 80075F94 3C01800B */  lui        $at, %hi(__osRunningThread)
    /* 76B98 80075F98 AC22A840 */  sw         $v0, %lo(__osRunningThread)($at)
    /* 76B9C 80075F9C 24080004 */  addiu      $t0, $zero, 0x4
    /* 76BA0 80075FA0 A4480010 */  sh         $t0, 0x10($v0)
    /* 76BA4 80075FA4 0040D025 */  or         $k0, $v0, $zero
    /* 76BA8 80075FA8 3C08800B */  lui        $t0, %hi(D_800AA40C_AB00C)
    /* 76BAC 80075FAC 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 76BB0 80075FB0 2508A40C */  addiu      $t0, $t0, %lo(D_800AA40C_AB00C)
    /* 76BB4 80075FB4 8D080000 */  lw         $t0, 0x0($t0)
    /* 76BB8 80075FB8 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 76BBC 80075FBC 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 76BC0 80075FC0 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 76BC4 80075FC4 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 76BC8 80075FC8 01284824 */  and        $t1, $t1, $t0
    /* 76BCC 80075FCC 0361D824 */  and        $k1, $k1, $at
    /* 76BD0 80075FD0 0369D825 */  or         $k1, $k1, $t1
    /* 76BD4 80075FD4 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 76BD8 80075FD8 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* 76BDC 80075FDC DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* 76BE0 80075FE0 DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* 76BE4 80075FE4 03600013 */  mtlo       $k1
    /* 76BE8 80075FE8 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* 76BEC 80075FEC DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* 76BF0 80075FF0 DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* 76BF4 80075FF4 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* 76BF8 80075FF8 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* 76BFC 80075FFC DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* 76C00 80076000 DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* 76C04 80076004 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* 76C08 80076008 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* 76C0C 8007600C DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* 76C10 80076010 DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* 76C14 80076014 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* 76C18 80076018 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* 76C1C 8007601C DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* 76C20 80076020 DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* 76C24 80076024 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* 76C28 80076028 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* 76C2C 8007602C DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* 76C30 80076030 DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* 76C34 80076034 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* 76C38 80076038 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* 76C3C 8007603C DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* 76C40 80076040 DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* 76C44 80076044 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* 76C48 80076048 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* 76C4C 8007604C 03600011 */  mthi       $k1
    /* 76C50 80076050 DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* 76C54 80076054 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* 76C58 80076058 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* 76C5C 8007605C 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* 76C60 80076060 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* 76C64 80076064 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* 76C68 80076068 13600023 */  beqz       $k1, .L800760F8_76CF8 /* handwritten instruction */
    /* 76C6C 8007606C 00000000 */   nop
    /* 76C70 80076070 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* 76C74 80076074 44DBF800 */  ctc1       $k1, $31
    /* 76C78 80076078 D7400130 */  ldc1       $f0, 0x130($k0)
    /* 76C7C 8007607C D7410138 */  ldc1       $f1, 0x138($k0)
    /* 76C80 80076080 D7420140 */  ldc1       $f2, 0x140($k0)
    /* 76C84 80076084 D7430148 */  ldc1       $f3, 0x148($k0)
    /* 76C88 80076088 D7440150 */  ldc1       $f4, 0x150($k0)
    /* 76C8C 8007608C D7450158 */  ldc1       $f5, 0x158($k0)
    /* 76C90 80076090 D7460160 */  ldc1       $f6, 0x160($k0)
    /* 76C94 80076094 D7470168 */  ldc1       $f7, 0x168($k0)
    /* 76C98 80076098 D7480170 */  ldc1       $f8, 0x170($k0)
    /* 76C9C 8007609C D7490178 */  ldc1       $f9, 0x178($k0)
    /* 76CA0 800760A0 D74A0180 */  ldc1       $f10, 0x180($k0)
    /* 76CA4 800760A4 D74B0188 */  ldc1       $f11, 0x188($k0)
    /* 76CA8 800760A8 D74C0190 */  ldc1       $f12, 0x190($k0)
    /* 76CAC 800760AC D74D0198 */  ldc1       $f13, 0x198($k0)
    /* 76CB0 800760B0 D74E01A0 */  ldc1       $f14, 0x1A0($k0)
    /* 76CB4 800760B4 D74F01A8 */  ldc1       $f15, 0x1A8($k0)
    /* 76CB8 800760B8 D75001B0 */  ldc1       $f16, 0x1B0($k0)
    /* 76CBC 800760BC D75101B8 */  ldc1       $f17, 0x1B8($k0)
    /* 76CC0 800760C0 D75201C0 */  ldc1       $f18, 0x1C0($k0)
    /* 76CC4 800760C4 D75301C8 */  ldc1       $f19, 0x1C8($k0)
    /* 76CC8 800760C8 D75401D0 */  ldc1       $f20, 0x1D0($k0)
    /* 76CCC 800760CC D75501D8 */  ldc1       $f21, 0x1D8($k0)
    /* 76CD0 800760D0 D75601E0 */  ldc1       $f22, 0x1E0($k0)
    /* 76CD4 800760D4 D75701E8 */  ldc1       $f23, 0x1E8($k0)
    /* 76CD8 800760D8 D75801F0 */  ldc1       $f24, 0x1F0($k0)
    /* 76CDC 800760DC D75901F8 */  ldc1       $f25, 0x1F8($k0)
    /* 76CE0 800760E0 D75A0200 */  ldc1       $f26, 0x200($k0)
    /* 76CE4 800760E4 D75B0208 */  ldc1       $f27, 0x208($k0)
    /* 76CE8 800760E8 D75C0210 */  ldc1       $f28, 0x210($k0)
    /* 76CEC 800760EC D75D0218 */  ldc1       $f29, 0x218($k0)
    /* 76CF0 800760F0 D75E0220 */  ldc1       $f30, 0x220($k0)
    /* 76CF4 800760F4 D75F0228 */  ldc1       $f31, 0x228($k0)
  .L800760F8_76CF8:
    /* 76CF8 800760F8 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* 76CFC 800760FC 3C1A800B */  lui        $k0, %hi(D_800AA40C_AB00C) /* handwritten instruction */
    /* 76D00 80076100 275AA40C */  addiu      $k0, $k0, %lo(D_800AA40C_AB00C) /* handwritten instruction */
    /* 76D04 80076104 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 76D08 80076108 001AD402 */  srl        $k0, $k0, 16
    /* 76D0C 8007610C 037AD824 */  and        $k1, $k1, $k0
    /* 76D10 80076110 001BD840 */  sll        $k1, $k1, 1
    /* 76D14 80076114 3C1A800B */  lui        $k0, %hi(D_800B0560_B1160) /* handwritten instruction */
    /* 76D18 80076118 275A0560 */  addiu      $k0, $k0, %lo(D_800B0560_B1160) /* handwritten instruction */
    /* 76D1C 8007611C 037AD821 */  addu       $k1, $k1, $k0
    /* 76D20 80076120 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* 76D24 80076124 3C1AA430 */  lui        $k0, %hi(MI_INTR_MASK_REG) /* handwritten instruction */
    /* 76D28 80076128 275A000C */  addiu      $k0, $k0, %lo(MI_INTR_MASK_REG) /* handwritten instruction */
    /* 76D2C 8007612C AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* 76D30 80076130 00000000 */  nop
    /* 76D34 80076134 00000000 */  nop
    /* 76D38 80076138 00000000 */  nop
    /* 76D3C 8007613C 00000000 */  nop
    /* 76D40 80076140 42000018 */  eret /* handwritten instruction */

glabel __osCleanupThread
    /* 76D44 80076144 0C0268F0 */  jal        osDestroyThread
    /* 76D48 80076148 00002025 */   or        $a0, $zero, $zero
    /* 76D4C 8007614C 00000000 */  nop
