.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel __osGetCause
    /* 9B7F0 8009ABF0 40026800 */  mfc0       $v0, $13 /* handwritten instruction */
    /* 9B7F4 8009ABF4 03E00008 */  jr         $ra
    /* 9B7F8 8009ABF8 00000000 */   nop
    /* 9B7FC 8009ABFC 00000000 */  nop
