.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel __osGetSR
    /* 9B680 8009AA80 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 9B684 8009AA84 03E00008 */  jr         $ra
    /* 9B688 8009AA88 00000000 */   nop
    /* 9B68C 8009AA8C 00000000 */  nop
