.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel osInvalICache
    /* 958C0 80094CC0 18A00011 */  blez       $a1, .L80094D08_95908
    /* 958C4 80094CC4 00000000 */   nop
    /* 958C8 80094CC8 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 958CC 80094CCC 00AB082B */  sltu       $at, $a1, $t3
    /* 958D0 80094CD0 1020000F */  beqz       $at, .L80094D10_95910
    /* 958D4 80094CD4 00000000 */   nop
    /* 958D8 80094CD8 00804025 */  or         $t0, $a0, $zero
    /* 958DC 80094CDC 00854821 */  addu       $t1, $a0, $a1
    /* 958E0 80094CE0 0109082B */  sltu       $at, $t0, $t1
    /* 958E4 80094CE4 10200008 */  beqz       $at, .L80094D08_95908
    /* 958E8 80094CE8 00000000 */   nop
    /* 958EC 80094CEC 310A001F */  andi       $t2, $t0, 0x1F
    /* 958F0 80094CF0 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* 958F4 80094CF4 010A4023 */  subu       $t0, $t0, $t2
  .L80094CF8_958F8:
    /* 958F8 80094CF8 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* 958FC 80094CFC 0109082B */  sltu       $at, $t0, $t1
    /* 95900 80094D00 1420FFFD */  bnez       $at, .L80094CF8_958F8
    /* 95904 80094D04 25080020 */   addiu     $t0, $t0, 0x20
  .L80094D08_95908:
    /* 95908 80094D08 03E00008 */  jr         $ra
    /* 9590C 80094D0C 00000000 */   nop
  .L80094D10_95910:
    /* 95910 80094D10 3C088000 */  lui        $t0, 0x8000
    /* 95914 80094D14 010B4821 */  addu       $t1, $t0, $t3
    /* 95918 80094D18 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L80094D1C_9591C:
    /* 9591C 80094D1C BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* 95920 80094D20 0109082B */  sltu       $at, $t0, $t1
    /* 95924 80094D24 1420FFFD */  bnez       $at, .L80094D1C_9591C
    /* 95928 80094D28 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* 9592C 80094D2C 03E00008 */  jr         $ra
    /* 95930 80094D30 00000000 */   nop
    /* 95934 80094D34 00000000 */  nop
    /* 95938 80094D38 00000000 */  nop
    /* 9593C 80094D3C 00000000 */  nop
