.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel __osProbeTLB
    /* 9B430 8009A830 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 9B434 8009A834 310900FF */  andi       $t1, $t0, 0xFF
    /* 9B438 8009A838 2401E000 */  addiu      $at, $zero, -0x2000
    /* 9B43C 8009A83C 00815024 */  and        $t2, $a0, $at
    /* 9B440 8009A840 012A4825 */  or         $t1, $t1, $t2
    /* 9B444 8009A844 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 9B448 8009A848 00000000 */  nop
    /* 9B44C 8009A84C 00000000 */  nop
    /* 9B450 8009A850 00000000 */  nop
    /* 9B454 8009A854 42000008 */  tlbp /* handwritten instruction */
    /* 9B458 8009A858 00000000 */  nop
    /* 9B45C 8009A85C 00000000 */  nop
    /* 9B460 8009A860 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* 9B464 8009A864 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 9B468 8009A868 01615824 */  and        $t3, $t3, $at
    /* 9B46C 8009A86C 1560001A */  bnez       $t3, .L8009A8D8
    /* 9B470 8009A870 00000000 */   nop
    /* 9B474 8009A874 42000001 */  tlbr /* handwritten instruction */
    /* 9B478 8009A878 00000000 */  nop
    /* 9B47C 8009A87C 00000000 */  nop
    /* 9B480 8009A880 00000000 */  nop
    /* 9B484 8009A884 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* 9B488 8009A888 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* 9B48C 8009A88C 000B5842 */  srl        $t3, $t3, 1
    /* 9B490 8009A890 01646024 */  and        $t4, $t3, $a0
    /* 9B494 8009A894 15800004 */  bnez       $t4, .L8009A8A8
    /* 9B498 8009A898 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* 9B49C 8009A89C 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* 9B4A0 8009A8A0 10000002 */  b          .L8009A8AC
    /* 9B4A4 8009A8A4 00000000 */   nop
  .L8009A8A8:
    /* 9B4A8 8009A8A8 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .L8009A8AC:
    /* 9B4AC 8009A8AC 304D0002 */  andi       $t5, $v0, 0x2
    /* 9B4B0 8009A8B0 11A00009 */  beqz       $t5, .L8009A8D8
    /* 9B4B4 8009A8B4 00000000 */   nop
    /* 9B4B8 8009A8B8 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* 9B4BC 8009A8BC 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* 9B4C0 8009A8C0 00411024 */  and        $v0, $v0, $at
    /* 9B4C4 8009A8C4 00021180 */  sll        $v0, $v0, 6
    /* 9B4C8 8009A8C8 008B6824 */  and        $t5, $a0, $t3
    /* 9B4CC 8009A8CC 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* 9B4D0 8009A8D0 10000002 */  b          .L8009A8DC
    /* 9B4D4 8009A8D4 00000000 */   nop
  .L8009A8D8:
    /* 9B4D8 8009A8D8 2402FFFF */  addiu      $v0, $zero, -0x1
  .L8009A8DC:
    /* 9B4DC 8009A8DC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 9B4E0 8009A8E0 03E00008 */  jr         $ra
    /* 9B4E4 8009A8E4 00000000 */   nop
    /* 9B4E8 8009A8E8 00000000 */  nop
    /* 9B4EC 8009A8EC 00000000 */  nop
