.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel __osSetFpcCsr
    /* 9B690 8009AA90 4442F800 */  cfc1       $v0, $31
    /* 9B694 8009AA94 44C4F800 */  ctc1       $a0, $31
    /* 9B698 8009AA98 03E00008 */  jr         $ra
    /* 9B69C 8009AA9C 00000000 */   nop
