.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .rodata

glabel __osRcpImTable
/* LUT to convert between MI_INTR and MI_INTR_MASK */
/* MI_INTR is status for each interrupt whereas    */
/* MI_INTR_MASK has seperate bits for set/clr      */
.half     0x0555, 0x0556, 0x0559, 0x055A, 0x0565, 0x0566, 0x0569, 0x056A
.half     0x0595, 0x0596, 0x0599, 0x059A, 0x05A5, 0x05A6, 0x05A9, 0x05AA
.half     0x0655, 0x0656, 0x0659, 0x065A, 0x0665, 0x0666, 0x0669, 0x066A
.half     0x0695, 0x0696, 0x0699, 0x069A, 0x06A5, 0x06A6, 0x06A9, 0x06AA
.half     0x0955, 0x0956, 0x0959, 0x095A, 0x0965, 0x0966, 0x0969, 0x096A
.half     0x0995, 0x0996, 0x0999, 0x099A, 0x09A5, 0x09A6, 0x09A9, 0x09AA
.half     0x0A55, 0x0A56, 0x0A59, 0x0A5A, 0x0A65, 0x0A66, 0x0A69, 0x0A6A
.half     0x0A95, 0x0A96, 0x0A99, 0x0A9A, 0x0AA5, 0x0AA6, 0x0AA9, 0x0AAA

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel osSetIntMask
    /* 999F0 80098DF0 400C6000 */  mfc0       $t4, $12 /* handwritten instruction */
    /* 999F4 80098DF4 3182FF01 */  andi       $v0, $t4, 0xFF01
    /* 999F8 80098DF8 3C08800B */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 999FC 80098DFC 2508A40C */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 99A00 80098E00 8D0B0000 */  lw         $t3, 0x0($t0)
    /* 99A04 80098E04 2401FFFF */  addiu      $at, $zero, -0x1
    /* 99A08 80098E08 01614026 */  xor        $t0, $t3, $at
    /* 99A0C 80098E0C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 99A10 80098E10 00481025 */  or         $v0, $v0, $t0
    /* 99A14 80098E14 3C0AA430 */  lui        $t2, %hi(MI_INTR_MASK_REG)
    /* 99A18 80098E18 8D4A000C */  lw         $t2, %lo(MI_INTR_MASK_REG)($t2)
    /* 99A1C 80098E1C 11400005 */  beqz       $t2, .L80098E34_99A34
    /* 99A20 80098E20 000B4C02 */   srl       $t1, $t3, 16
    /* 99A24 80098E24 2401FFFF */  addiu      $at, $zero, -0x1
    /* 99A28 80098E28 01214826 */  xor        $t1, $t1, $at
    /* 99A2C 80098E2C 3129003F */  andi       $t1, $t1, 0x3F
    /* 99A30 80098E30 01495025 */  or         $t2, $t2, $t1
  .L80098E34_99A34:
    /* 99A34 80098E34 000A5400 */  sll        $t2, $t2, 16
    /* 99A38 80098E38 004A1025 */  or         $v0, $v0, $t2
    /* 99A3C 80098E3C 3C01003F */  lui        $at, (0x3F0000 >> 16)
    /* 99A40 80098E40 00814024 */  and        $t0, $a0, $at
    /* 99A44 80098E44 010B4024 */  and        $t0, $t0, $t3
    /* 99A48 80098E48 000843C2 */  srl        $t0, $t0, 15
    /* 99A4C 80098E4C 3C0A800B */  lui        $t2, %hi(__osRcpImTable)
    /* 99A50 80098E50 01485021 */  addu       $t2, $t2, $t0
    /* 99A54 80098E54 954A0560 */  lhu        $t2, %lo(__osRcpImTable)($t2)
    /* 99A58 80098E58 3C01A430 */  lui        $at, %hi(MI_INTR_MASK_REG)
    /* 99A5C 80098E5C AC2A000C */  sw         $t2, %lo(MI_INTR_MASK_REG)($at)
    /* 99A60 80098E60 3088FF01 */  andi       $t0, $a0, 0xFF01
    /* 99A64 80098E64 3169FF00 */  andi       $t1, $t3, 0xFF00
    /* 99A68 80098E68 01094024 */  and        $t0, $t0, $t1
    /* 99A6C 80098E6C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 99A70 80098E70 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 99A74 80098E74 01816024 */  and        $t4, $t4, $at
    /* 99A78 80098E78 01886025 */  or         $t4, $t4, $t0
    /* 99A7C 80098E7C 408C6000 */  mtc0       $t4, $12 /* handwritten instruction */
    /* 99A80 80098E80 00000000 */  nop
    /* 99A84 80098E84 00000000 */  nop
    /* 99A88 80098E88 03E00008 */  jr         $ra
    /* 99A8C 80098E8C 00000000 */   nop
