.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel sqrtf
    /* 94980 80093D80 03E00008 */  jr         $ra
    /* 94984 80093D84 46006004 */   sqrt.s    $f0, $f12
    /* 94988 80093D88 00000000 */  nop
    /* 9498C 80093D8C 00000000 */  nop
