.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel osUnmapTLBAll
    /* 9B740 8009AB40 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 9B744 8009AB44 2409001F */  addiu      $t1, $zero, 0x1F
    /* 9B748 8009AB48 3C0A8000 */  lui        $t2, (0x80000000 >> 16)
    /* 9B74C 8009AB4C 408A5000 */  mtc0       $t2, $10 /* handwritten instruction */
    /* 9B750 8009AB50 40801000 */  mtc0       $zero, $2 /* handwritten instruction */
    /* 9B754 8009AB54 40801800 */  mtc0       $zero, $3 /* handwritten instruction */
  .L8009AB58:
    /* 9B758 8009AB58 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 9B75C 8009AB5C 00000000 */  nop
    /* 9B760 8009AB60 42000002 */  tlbwi /* handwritten instruction */
    /* 9B764 8009AB64 00000000 */  nop
    /* 9B768 8009AB68 00000000 */  nop
    /* 9B76C 8009AB6C 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* 9B770 8009AB70 5520FFF9 */  bnel       $t1, $zero, .L8009AB58
    /* 9B774 8009AB74 00000000 */   nop
    /* 9B778 8009AB78 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 9B77C 8009AB7C 03E00008 */  jr         $ra
    /* 9B780 8009AB80 00000000 */   nop
    /* 9B784 8009AB84 00000000 */  nop
    /* 9B788 8009AB88 00000000 */  nop
    /* 9B78C 8009AB8C 00000000 */  nop
