.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel osWritebackDCache
    /* 95840 80094C40 18A00011 */  blez       $a1, .L80094C88_95888
    /* 95844 80094C44 00000000 */   nop
    /* 95848 80094C48 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 9584C 80094C4C 00AB082B */  sltu       $at, $a1, $t3
    /* 95850 80094C50 1020000F */  beqz       $at, .L80094C90_95890
    /* 95854 80094C54 00000000 */   nop
    /* 95858 80094C58 00804025 */  or         $t0, $a0, $zero
    /* 9585C 80094C5C 00854821 */  addu       $t1, $a0, $a1
    /* 95860 80094C60 0109082B */  sltu       $at, $t0, $t1
    /* 95864 80094C64 10200008 */  beqz       $at, .L80094C88_95888
    /* 95868 80094C68 00000000 */   nop
    /* 9586C 80094C6C 310A000F */  andi       $t2, $t0, 0xF
    /* 95870 80094C70 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 95874 80094C74 010A4023 */  subu       $t0, $t0, $t2
  .L80094C78_95878:
    /* 95878 80094C78 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* 9587C 80094C7C 0109082B */  sltu       $at, $t0, $t1
    /* 95880 80094C80 1420FFFD */  bnez       $at, .L80094C78_95878
    /* 95884 80094C84 25080010 */   addiu     $t0, $t0, 0x10
  .L80094C88_95888:
    /* 95888 80094C88 03E00008 */  jr         $ra
    /* 9588C 80094C8C 00000000 */   nop
  .L80094C90_95890:
    /* 95890 80094C90 3C088000 */  lui        $t0, 0x8000
    /* 95894 80094C94 010B4821 */  addu       $t1, $t0, $t3
    /* 95898 80094C98 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L80094C9C_9589C:
    /* 9589C 80094C9C BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 958A0 80094CA0 0109082B */  sltu       $at, $t0, $t1
    /* 958A4 80094CA4 1420FFFD */  bnez       $at, .L80094C9C_9589C
    /* 958A8 80094CA8 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 958AC 80094CAC 03E00008 */  jr         $ra
    /* 958B0 80094CB0 00000000 */   nop
    /* 958B4 80094CB4 00000000 */  nop
    /* 958B8 80094CB8 00000000 */  nop
    /* 958BC 80094CBC 00000000 */  nop
