.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

glabel _Genld
    /* 9E250 8009D650 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 9E254 8009D654 AFB20028 */  sw         $s2, 0x28($sp)
    /* 9E258 8009D658 00127400 */  sll        $t6, $s2, 16
    /* 9E25C 8009D65C 000E9403 */  sra        $s2, $t6, 16
    /* 9E260 8009D660 AFB30024 */  sw         $s3, 0x24($sp)
    /* 9E264 8009D664 0013C400 */  sll        $t8, $s3, 16
    /* 9E268 8009D668 00189C03 */  sra        $s3, $t8, 16
    /* 9E26C 8009D66C 328E00FF */  andi       $t6, $s4, 0xFF
    /* 9E270 8009D670 AFB4001C */  sw         $s4, 0x1C($sp)
    /* 9E274 8009D674 01C0A025 */  or         $s4, $t6, $zero
    /* 9E278 8009D678 1E600004 */  bgtz       $s3, .L8009D68C
    /* 9E27C 8009D67C AFBF0014 */   sw        $ra, 0x14($sp)
    /* 9E280 8009D680 3C11800B */  lui        $s1, %hi(D_800B0760)
    /* 9E284 8009D684 26310760 */  addiu      $s1, $s1, %lo(D_800B0760)
    /* 9E288 8009D688 24130001 */  addiu      $s3, $zero, 0x1
  .L8009D68C:
    /* 9E28C 8009D68C 24020066 */  addiu      $v0, $zero, 0x66
    /* 9E290 8009D690 1054000C */  beq        $v0, $s4, .L8009D6C4
    /* 9E294 8009D694 02801825 */   or        $v1, $s4, $zero
    /* 9E298 8009D698 24040067 */  addiu      $a0, $zero, 0x67
    /* 9E29C 8009D69C 10830002 */  beq        $a0, $v1, .L8009D6A8
    /* 9E2A0 8009D6A0 24010047 */   addiu     $at, $zero, 0x47
    /* 9E2A4 8009D6A4 14610096 */  bne        $v1, $at, .L8009D900
  .L8009D6A8:
    /* 9E2A8 8009D6A8 2A41FFFC */   slti      $at, $s2, -0x4
    /* 9E2AC 8009D6AC 14200094 */  bnez       $at, .L8009D900
    /* 9E2B0 8009D6B0 00000000 */   nop
    /* 9E2B4 8009D6B4 8E0F0024 */  lw         $t7, 0x24($s0)
    /* 9E2B8 8009D6B8 024F082A */  slt        $at, $s2, $t7
    /* 9E2BC 8009D6BC 10200090 */  beqz       $at, .L8009D900
    /* 9E2C0 8009D6C0 00000000 */   nop
  .L8009D6C4:
    /* 9E2C4 8009D6C4 26520001 */  addiu      $s2, $s2, 0x1
    /* 9E2C8 8009D6C8 0012C400 */  sll        $t8, $s2, 16
    /* 9E2CC 8009D6CC 1043000E */  beq        $v0, $v1, .L8009D708
    /* 9E2D0 8009D6D0 00189403 */   sra       $s2, $t8, 16
    /* 9E2D4 8009D6D4 8E0E0030 */  lw         $t6, 0x30($s0)
    /* 9E2D8 8009D6D8 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E2DC 8009D6DC 31CF0008 */  andi       $t7, $t6, 0x8
    /* 9E2E0 8009D6E0 15E00005 */  bnez       $t7, .L8009D6F8
    /* 9E2E4 8009D6E4 0262082A */   slt       $at, $s3, $v0
    /* 9E2E8 8009D6E8 50200004 */  beql       $at, $zero, .L8009D6FC
    /* 9E2EC 8009D6EC 0052C023 */   subu      $t8, $v0, $s2
    /* 9E2F0 8009D6F0 AE130024 */  sw         $s3, 0x24($s0)
    /* 9E2F4 8009D6F4 02601025 */  or         $v0, $s3, $zero
  .L8009D6F8:
    /* 9E2F8 8009D6F8 0052C023 */  subu       $t8, $v0, $s2
  .L8009D6FC:
    /* 9E2FC 8009D6FC 07010002 */  bgez       $t8, .L8009D708
    /* 9E300 8009D700 AE180024 */   sw        $t8, 0x24($s0)
    /* 9E304 8009D704 AE000024 */  sw         $zero, 0x24($s0)
  .L8009D708:
    /* 9E308 8009D708 1E400033 */  bgtz       $s2, .L8009D7D8
    /* 9E30C 8009D70C 0272082A */   slt       $at, $s3, $s2
    /* 9E310 8009D710 8E0F0008 */  lw         $t7, 0x8($s0)
    /* 9E314 8009D714 8E180014 */  lw         $t8, 0x14($s0)
    /* 9E318 8009D718 240E0030 */  addiu      $t6, $zero, 0x30
    /* 9E31C 8009D71C 00121823 */  negu       $v1, $s2
    /* 9E320 8009D720 01F8C821 */  addu       $t9, $t7, $t8
    /* 9E324 8009D724 A32E0000 */  sb         $t6, 0x0($t9)
    /* 9E328 8009D728 8E0F0014 */  lw         $t7, 0x14($s0)
    /* 9E32C 8009D72C 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E330 8009D730 02202825 */  or         $a1, $s1, $zero
    /* 9E334 8009D734 25F80001 */  addiu      $t8, $t7, 0x1
    /* 9E338 8009D738 1C400005 */  bgtz       $v0, .L8009D750
    /* 9E33C 8009D73C AE180014 */   sw        $t8, 0x14($s0)
    /* 9E340 8009D740 8E0E0030 */  lw         $t6, 0x30($s0)
    /* 9E344 8009D744 31D90008 */  andi       $t9, $t6, 0x8
    /* 9E348 8009D748 5320000B */  beql       $t9, $zero, .L8009D778
    /* 9E34C 8009D74C 0043082A */   slt       $at, $v0, $v1
  .L8009D750:
    /* 9E350 8009D750 8E180008 */  lw         $t8, 0x8($s0)
    /* 9E354 8009D754 8E0E0014 */  lw         $t6, 0x14($s0)
    /* 9E358 8009D758 240F002E */  addiu      $t7, $zero, 0x2E
    /* 9E35C 8009D75C 030EC821 */  addu       $t9, $t8, $t6
    /* 9E360 8009D760 A32F0000 */  sb         $t7, 0x0($t9)
    /* 9E364 8009D764 8E180014 */  lw         $t8, 0x14($s0)
    /* 9E368 8009D768 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E36C 8009D76C 270E0001 */  addiu      $t6, $t8, 0x1
    /* 9E370 8009D770 AE0E0014 */  sw         $t6, 0x14($s0)
    /* 9E374 8009D774 0043082A */  slt        $at, $v0, $v1
  .L8009D778:
    /* 9E378 8009D778 50200006 */  beql       $at, $zero, .L8009D794
    /* 9E37C 8009D77C 0052C021 */   addu      $t8, $v0, $s2
    /* 9E380 8009D780 00029023 */  negu       $s2, $v0
    /* 9E384 8009D784 00127C00 */  sll        $t7, $s2, 16
    /* 9E388 8009D788 000F9403 */  sra        $s2, $t7, 16
    /* 9E38C 8009D78C 00121823 */  negu       $v1, $s2
    /* 9E390 8009D790 0052C021 */  addu       $t8, $v0, $s2
  .L8009D794:
    /* 9E394 8009D794 0313082A */  slt        $at, $t8, $s3
    /* 9E398 8009D798 AE030018 */  sw         $v1, 0x18($s0)
    /* 9E39C 8009D79C 10200004 */  beqz       $at, .L8009D7B0
    /* 9E3A0 8009D7A0 AE180024 */   sw        $t8, 0x24($s0)
    /* 9E3A4 8009D7A4 00189C00 */  sll        $s3, $t8, 16
    /* 9E3A8 8009D7A8 00137403 */  sra        $t6, $s3, 16
    /* 9E3AC 8009D7AC 01C09825 */  or         $s3, $t6, $zero
  .L8009D7B0:
    /* 9E3B0 8009D7B0 8E0F0008 */  lw         $t7, 0x8($s0)
    /* 9E3B4 8009D7B4 8E190014 */  lw         $t9, 0x14($s0)
    /* 9E3B8 8009D7B8 AE13001C */  sw         $s3, 0x1C($s0)
    /* 9E3BC 8009D7BC 02603025 */  or         $a2, $s3, $zero
    /* 9E3C0 8009D7C0 0C025714 */  jal        memcpy
    /* 9E3C4 8009D7C4 01F92021 */   addu      $a0, $t7, $t9
    /* 9E3C8 8009D7C8 8E180024 */  lw         $t8, 0x24($s0)
    /* 9E3CC 8009D7CC 03137023 */  subu       $t6, $t8, $s3
    /* 9E3D0 8009D7D0 100000E2 */  b          .L8009DB5C
    /* 9E3D4 8009D7D4 AE0E0020 */   sw        $t6, 0x20($s0)
  .L8009D7D8:
    /* 9E3D8 8009D7D8 1020001D */  beqz       $at, .L8009D850
    /* 9E3DC 8009D7DC 02202825 */   or        $a1, $s1, $zero
    /* 9E3E0 8009D7E0 8E0F0008 */  lw         $t7, 0x8($s0)
    /* 9E3E4 8009D7E4 8E190014 */  lw         $t9, 0x14($s0)
    /* 9E3E8 8009D7E8 02202825 */  or         $a1, $s1, $zero
    /* 9E3EC 8009D7EC 02603025 */  or         $a2, $s3, $zero
    /* 9E3F0 8009D7F0 0C025714 */  jal        memcpy
    /* 9E3F4 8009D7F4 01F92021 */   addu      $a0, $t7, $t9
    /* 9E3F8 8009D7F8 8E180014 */  lw         $t8, 0x14($s0)
    /* 9E3FC 8009D7FC 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E400 8009D800 02537823 */  subu       $t7, $s2, $s3
    /* 9E404 8009D804 03137021 */  addu       $t6, $t8, $s3
    /* 9E408 8009D808 AE0E0014 */  sw         $t6, 0x14($s0)
    /* 9E40C 8009D80C 1C400005 */  bgtz       $v0, .L8009D824
    /* 9E410 8009D810 AE0F0018 */   sw        $t7, 0x18($s0)
    /* 9E414 8009D814 8E190030 */  lw         $t9, 0x30($s0)
    /* 9E418 8009D818 33380008 */  andi       $t8, $t9, 0x8
    /* 9E41C 8009D81C 1300000A */  beqz       $t8, .L8009D848
    /* 9E420 8009D820 00000000 */   nop
  .L8009D824:
    /* 9E424 8009D824 8E0F0008 */  lw         $t7, 0x8($s0)
    /* 9E428 8009D828 8E190014 */  lw         $t9, 0x14($s0)
    /* 9E42C 8009D82C 240E002E */  addiu      $t6, $zero, 0x2E
    /* 9E430 8009D830 01F9C021 */  addu       $t8, $t7, $t9
    /* 9E434 8009D834 A30E0000 */  sb         $t6, 0x0($t8)
    /* 9E438 8009D838 8E0F001C */  lw         $t7, 0x1C($s0)
    /* 9E43C 8009D83C 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E440 8009D840 25F90001 */  addiu      $t9, $t7, 0x1
    /* 9E444 8009D844 AE19001C */  sw         $t9, 0x1C($s0)
  .L8009D848:
    /* 9E448 8009D848 100000C4 */  b          .L8009DB5C
    /* 9E44C 8009D84C AE020020 */   sw        $v0, 0x20($s0)
  .L8009D850:
    /* 9E450 8009D850 8E0E0008 */  lw         $t6, 0x8($s0)
    /* 9E454 8009D854 8E180014 */  lw         $t8, 0x14($s0)
    /* 9E458 8009D858 02403025 */  or         $a2, $s2, $zero
    /* 9E45C 8009D85C 0C025714 */  jal        memcpy
    /* 9E460 8009D860 01D82021 */   addu      $a0, $t6, $t8
    /* 9E464 8009D864 8E0F0014 */  lw         $t7, 0x14($s0)
    /* 9E468 8009D868 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E46C 8009D86C 02729823 */  subu       $s3, $s3, $s2
    /* 9E470 8009D870 00137400 */  sll        $t6, $s3, 16
    /* 9E474 8009D874 01F2C821 */  addu       $t9, $t7, $s2
    /* 9E478 8009D878 AE190014 */  sw         $t9, 0x14($s0)
    /* 9E47C 8009D87C 1C400005 */  bgtz       $v0, .L8009D894
    /* 9E480 8009D880 000E9C03 */   sra       $s3, $t6, 16
    /* 9E484 8009D884 8E0F0030 */  lw         $t7, 0x30($s0)
    /* 9E488 8009D888 31F90008 */  andi       $t9, $t7, 0x8
    /* 9E48C 8009D88C 5320000B */  beql       $t9, $zero, .L8009D8BC
    /* 9E490 8009D890 0053082A */   slt       $at, $v0, $s3
  .L8009D894:
    /* 9E494 8009D894 8E180008 */  lw         $t8, 0x8($s0)
    /* 9E498 8009D898 8E0F0014 */  lw         $t7, 0x14($s0)
    /* 9E49C 8009D89C 240E002E */  addiu      $t6, $zero, 0x2E
    /* 9E4A0 8009D8A0 030FC821 */  addu       $t9, $t8, $t7
    /* 9E4A4 8009D8A4 A32E0000 */  sb         $t6, 0x0($t9)
    /* 9E4A8 8009D8A8 8E180014 */  lw         $t8, 0x14($s0)
    /* 9E4AC 8009D8AC 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E4B0 8009D8B0 270F0001 */  addiu      $t7, $t8, 0x1
    /* 9E4B4 8009D8B4 AE0F0014 */  sw         $t7, 0x14($s0)
    /* 9E4B8 8009D8B8 0053082A */  slt        $at, $v0, $s3
  .L8009D8BC:
    /* 9E4BC 8009D8BC 10200004 */  beqz       $at, .L8009D8D0
    /* 9E4C0 8009D8C0 02512821 */   addu      $a1, $s2, $s1
    /* 9E4C4 8009D8C4 00029C00 */  sll        $s3, $v0, 16
    /* 9E4C8 8009D8C8 00137403 */  sra        $t6, $s3, 16
    /* 9E4CC 8009D8CC 01C09825 */  or         $s3, $t6, $zero
  .L8009D8D0:
    /* 9E4D0 8009D8D0 8E190008 */  lw         $t9, 0x8($s0)
    /* 9E4D4 8009D8D4 8E180014 */  lw         $t8, 0x14($s0)
    /* 9E4D8 8009D8D8 02603025 */  or         $a2, $s3, $zero
    /* 9E4DC 8009D8DC 0C025714 */  jal        memcpy
    /* 9E4E0 8009D8E0 03382021 */   addu      $a0, $t9, $t8
    /* 9E4E4 8009D8E4 8E0F0014 */  lw         $t7, 0x14($s0)
    /* 9E4E8 8009D8E8 8E190024 */  lw         $t9, 0x24($s0)
    /* 9E4EC 8009D8EC 01F37021 */  addu       $t6, $t7, $s3
    /* 9E4F0 8009D8F0 0333C023 */  subu       $t8, $t9, $s3
    /* 9E4F4 8009D8F4 AE0E0014 */  sw         $t6, 0x14($s0)
    /* 9E4F8 8009D8F8 10000098 */  b          .L8009DB5C
    /* 9E4FC 8009D8FC AE180018 */   sw        $t8, 0x18($s0)
  .L8009D900:
    /* 9E500 8009D900 10830003 */  beq        $a0, $v1, .L8009D910
    /* 9E504 8009D904 24010047 */   addiu     $at, $zero, 0x47
    /* 9E508 8009D908 54610011 */  bnel       $v1, $at, .L8009D950
    /* 9E50C 8009D90C 8E180008 */   lw        $t8, 0x8($s0)
  .L8009D910:
    /* 9E510 8009D910 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E514 8009D914 24140045 */  addiu      $s4, $zero, 0x45
    /* 9E518 8009D918 0262082A */  slt        $at, $s3, $v0
    /* 9E51C 8009D91C 50200004 */  beql       $at, $zero, .L8009D930
    /* 9E520 8009D920 244FFFFF */   addiu     $t7, $v0, -0x1
    /* 9E524 8009D924 AE130024 */  sw         $s3, 0x24($s0)
    /* 9E528 8009D928 02601025 */  or         $v0, $s3, $zero
    /* 9E52C 8009D92C 244FFFFF */  addiu      $t7, $v0, -0x1
  .L8009D930:
    /* 9E530 8009D930 05E10002 */  bgez       $t7, .L8009D93C
    /* 9E534 8009D934 AE0F0024 */   sw        $t7, 0x24($s0)
    /* 9E538 8009D938 AE000024 */  sw         $zero, 0x24($s0)
  .L8009D93C:
    /* 9E53C 8009D93C 14830003 */  bne        $a0, $v1, .L8009D94C
    /* 9E540 8009D940 00000000 */   nop
    /* 9E544 8009D944 10000001 */  b          .L8009D94C
    /* 9E548 8009D948 24140065 */   addiu     $s4, $zero, 0x65
  .L8009D94C:
    /* 9E54C 8009D94C 8E180008 */  lw         $t8, 0x8($s0)
  .L8009D950:
    /* 9E550 8009D950 8E0F0014 */  lw         $t7, 0x14($s0)
    /* 9E554 8009D954 92390000 */  lbu        $t9, 0x0($s1)
    /* 9E558 8009D958 26310001 */  addiu      $s1, $s1, 0x1
    /* 9E55C 8009D95C 030F7021 */  addu       $t6, $t8, $t7
    /* 9E560 8009D960 A1D90000 */  sb         $t9, 0x0($t6)
    /* 9E564 8009D964 8E180014 */  lw         $t8, 0x14($s0)
    /* 9E568 8009D968 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E56C 8009D96C 270F0001 */  addiu      $t7, $t8, 0x1
    /* 9E570 8009D970 1C400005 */  bgtz       $v0, .L8009D988
    /* 9E574 8009D974 AE0F0014 */   sw        $t7, 0x14($s0)
    /* 9E578 8009D978 8E190030 */  lw         $t9, 0x30($s0)
    /* 9E57C 8009D97C 332E0008 */  andi       $t6, $t9, 0x8
    /* 9E580 8009D980 11C0000A */  beqz       $t6, .L8009D9AC
    /* 9E584 8009D984 00000000 */   nop
  .L8009D988:
    /* 9E588 8009D988 8E0F0008 */  lw         $t7, 0x8($s0)
    /* 9E58C 8009D98C 8E190014 */  lw         $t9, 0x14($s0)
    /* 9E590 8009D990 2418002E */  addiu      $t8, $zero, 0x2E
    /* 9E594 8009D994 01F97021 */  addu       $t6, $t7, $t9
    /* 9E598 8009D998 A1D80000 */  sb         $t8, 0x0($t6)
    /* 9E59C 8009D99C 8E0F0014 */  lw         $t7, 0x14($s0)
    /* 9E5A0 8009D9A0 8E020024 */  lw         $v0, 0x24($s0)
    /* 9E5A4 8009D9A4 25F90001 */  addiu      $t9, $t7, 0x1
    /* 9E5A8 8009D9A8 AE190014 */  sw         $t9, 0x14($s0)
  .L8009D9AC:
    /* 9E5AC 8009D9AC 58400016 */  blezl      $v0, .L8009DA08
    /* 9E5B0 8009D9B0 8E0E0008 */   lw        $t6, 0x8($s0)
    /* 9E5B4 8009D9B4 2673FFFF */  addiu      $s3, $s3, -0x1
    /* 9E5B8 8009D9B8 0013C400 */  sll        $t8, $s3, 16
    /* 9E5BC 8009D9BC 00189C03 */  sra        $s3, $t8, 16
    /* 9E5C0 8009D9C0 0053082A */  slt        $at, $v0, $s3
    /* 9E5C4 8009D9C4 10200004 */  beqz       $at, .L8009D9D8
    /* 9E5C8 8009D9C8 02202825 */   or        $a1, $s1, $zero
    /* 9E5CC 8009D9CC 00029C00 */  sll        $s3, $v0, 16
    /* 9E5D0 8009D9D0 00137C03 */  sra        $t7, $s3, 16
    /* 9E5D4 8009D9D4 01E09825 */  or         $s3, $t7, $zero
  .L8009D9D8:
    /* 9E5D8 8009D9D8 8E190008 */  lw         $t9, 0x8($s0)
    /* 9E5DC 8009D9DC 8E180014 */  lw         $t8, 0x14($s0)
    /* 9E5E0 8009D9E0 02603025 */  or         $a2, $s3, $zero
    /* 9E5E4 8009D9E4 0C025714 */  jal        memcpy
    /* 9E5E8 8009D9E8 03382021 */   addu      $a0, $t9, $t8
    /* 9E5EC 8009D9EC 8E0E0014 */  lw         $t6, 0x14($s0)
    /* 9E5F0 8009D9F0 8E190024 */  lw         $t9, 0x24($s0)
    /* 9E5F4 8009D9F4 01D37821 */  addu       $t7, $t6, $s3
    /* 9E5F8 8009D9F8 0333C023 */  subu       $t8, $t9, $s3
    /* 9E5FC 8009D9FC AE0F0014 */  sw         $t7, 0x14($s0)
    /* 9E600 8009DA00 AE180018 */  sw         $t8, 0x18($s0)
    /* 9E604 8009DA04 8E0E0008 */  lw         $t6, 0x8($s0)
  .L8009DA08:
    /* 9E608 8009DA08 8E0F0014 */  lw         $t7, 0x14($s0)
    /* 9E60C 8009DA0C 01CF8821 */  addu       $s1, $t6, $t7
    /* 9E610 8009DA10 26310001 */  addiu      $s1, $s1, 0x1
    /* 9E614 8009DA14 06400005 */  bltz       $s2, .L8009DA2C
    /* 9E618 8009DA18 A234FFFF */   sb        $s4, -0x1($s1)
    /* 9E61C 8009DA1C 2419002B */  addiu      $t9, $zero, 0x2B
    /* 9E620 8009DA20 A2390000 */  sb         $t9, 0x0($s1)
    /* 9E624 8009DA24 10000008 */  b          .L8009DA48
    /* 9E628 8009DA28 26310001 */   addiu     $s1, $s1, 0x1
  .L8009DA2C:
    /* 9E62C 8009DA2C 00129023 */  negu       $s2, $s2
    /* 9E630 8009DA30 00127400 */  sll        $t6, $s2, 16
    /* 9E634 8009DA34 2418002D */  addiu      $t8, $zero, 0x2D
    /* 9E638 8009DA38 000E7C03 */  sra        $t7, $t6, 16
    /* 9E63C 8009DA3C A2380000 */  sb         $t8, 0x0($s1)
    /* 9E640 8009DA40 26310001 */  addiu      $s1, $s1, 0x1
    /* 9E644 8009DA44 01E09025 */  or         $s2, $t7, $zero
  .L8009DA48:
    /* 9E648 8009DA48 2A410064 */  slti       $at, $s2, 0x64
    /* 9E64C 8009DA4C 5420002A */  bnel       $at, $zero, .L8009DAF8
    /* 9E650 8009DA50 2402000A */   addiu     $v0, $zero, 0xA
    /* 9E654 8009DA54 2A4103E8 */  slti       $at, $s2, 0x3E8
    /* 9E658 8009DA58 14200013 */  bnez       $at, .L8009DAA8
    /* 9E65C 8009DA5C 240203E8 */   addiu     $v0, $zero, 0x3E8
    /* 9E660 8009DA60 0242001A */  div        $zero, $s2, $v0
    /* 9E664 8009DA64 14400002 */  bnez       $v0, .L8009DA70
    /* 9E668 8009DA68 00000000 */   nop
    /* 9E66C 8009DA6C 0007000D */  break      7
  .L8009DA70:
    /* 9E670 8009DA70 2401FFFF */  addiu      $at, $zero, -0x1
    /* 9E674 8009DA74 14410004 */  bne        $v0, $at, .L8009DA88
    /* 9E678 8009DA78 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 9E67C 8009DA7C 16410002 */  bne        $s2, $at, .L8009DA88
    /* 9E680 8009DA80 00000000 */   nop
    /* 9E684 8009DA84 0006000D */  break      6
  .L8009DA88:
    /* 9E688 8009DA88 00009010 */  mfhi       $s2
    /* 9E68C 8009DA8C 00127400 */  sll        $t6, $s2, 16
    /* 9E690 8009DA90 0000C812 */  mflo       $t9
    /* 9E694 8009DA94 27380030 */  addiu      $t8, $t9, 0x30
    /* 9E698 8009DA98 000E7C03 */  sra        $t7, $t6, 16
    /* 9E69C 8009DA9C 01E09025 */  or         $s2, $t7, $zero
    /* 9E6A0 8009DAA0 A2380000 */  sb         $t8, 0x0($s1)
    /* 9E6A4 8009DAA4 26310001 */  addiu      $s1, $s1, 0x1
  .L8009DAA8:
    /* 9E6A8 8009DAA8 24020064 */  addiu      $v0, $zero, 0x64
    /* 9E6AC 8009DAAC 0242001A */  div        $zero, $s2, $v0
    /* 9E6B0 8009DAB0 14400002 */  bnez       $v0, .L8009DABC
    /* 9E6B4 8009DAB4 00000000 */   nop
    /* 9E6B8 8009DAB8 0007000D */  break      7
  .L8009DABC:
    /* 9E6BC 8009DABC 2401FFFF */  addiu      $at, $zero, -0x1
    /* 9E6C0 8009DAC0 14410004 */  bne        $v0, $at, .L8009DAD4
    /* 9E6C4 8009DAC4 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 9E6C8 8009DAC8 16410002 */  bne        $s2, $at, .L8009DAD4
    /* 9E6CC 8009DACC 00000000 */   nop
    /* 9E6D0 8009DAD0 0006000D */  break      6
  .L8009DAD4:
    /* 9E6D4 8009DAD4 00009010 */  mfhi       $s2
    /* 9E6D8 8009DAD8 00127400 */  sll        $t6, $s2, 16
    /* 9E6DC 8009DADC 0000C812 */  mflo       $t9
    /* 9E6E0 8009DAE0 27380030 */  addiu      $t8, $t9, 0x30
    /* 9E6E4 8009DAE4 000E7C03 */  sra        $t7, $t6, 16
    /* 9E6E8 8009DAE8 01E09025 */  or         $s2, $t7, $zero
    /* 9E6EC 8009DAEC A2380000 */  sb         $t8, 0x0($s1)
    /* 9E6F0 8009DAF0 26310001 */  addiu      $s1, $s1, 0x1
    /* 9E6F4 8009DAF4 2402000A */  addiu      $v0, $zero, 0xA
  .L8009DAF8:
    /* 9E6F8 8009DAF8 0242001A */  div        $zero, $s2, $v0
    /* 9E6FC 8009DAFC 14400002 */  bnez       $v0, .L8009DB08
    /* 9E700 8009DB00 00000000 */   nop
    /* 9E704 8009DB04 0007000D */  break      7
  .L8009DB08:
    /* 9E708 8009DB08 2401FFFF */  addiu      $at, $zero, -0x1
    /* 9E70C 8009DB0C 14410004 */  bne        $v0, $at, .L8009DB20
    /* 9E710 8009DB10 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 9E714 8009DB14 16410002 */  bne        $s2, $at, .L8009DB20
    /* 9E718 8009DB18 00000000 */   nop
    /* 9E71C 8009DB1C 0006000D */  break      6
  .L8009DB20:
    /* 9E720 8009DB20 00009010 */  mfhi       $s2
    /* 9E724 8009DB24 00127400 */  sll        $t6, $s2, 16
    /* 9E728 8009DB28 0000C812 */  mflo       $t9
    /* 9E72C 8009DB2C 27380030 */  addiu      $t8, $t9, 0x30
    /* 9E730 8009DB30 000E7C03 */  sra        $t7, $t6, 16
    /* 9E734 8009DB34 25F90030 */  addiu      $t9, $t7, 0x30
    /* 9E738 8009DB38 A2380000 */  sb         $t8, 0x0($s1)
    /* 9E73C 8009DB3C A2390001 */  sb         $t9, 0x1($s1)
    /* 9E740 8009DB40 8E180008 */  lw         $t8, 0x8($s0)
    /* 9E744 8009DB44 01E09025 */  or         $s2, $t7, $zero
    /* 9E748 8009DB48 8E0F0014 */  lw         $t7, 0x14($s0)
    /* 9E74C 8009DB4C 26310002 */  addiu      $s1, $s1, 0x2
    /* 9E750 8009DB50 02387023 */  subu       $t6, $s1, $t8
    /* 9E754 8009DB54 01CFC823 */  subu       $t9, $t6, $t7
    /* 9E758 8009DB58 AE19001C */  sw         $t9, 0x1C($s0)
  .L8009DB5C:
    /* 9E75C 8009DB5C 8E180030 */  lw         $t8, 0x30($s0)
    /* 9E760 8009DB60 24010010 */  addiu      $at, $zero, 0x10
    /* 9E764 8009DB64 330E0014 */  andi       $t6, $t8, 0x14
    /* 9E768 8009DB68 55C10010 */  bnel       $t6, $at, .L8009DBAC
    /* 9E76C 8009DB6C 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 9E770 8009DB70 8E0F000C */  lw         $t7, 0xC($s0)
    /* 9E774 8009DB74 8E190014 */  lw         $t9, 0x14($s0)
    /* 9E778 8009DB78 8E0E0018 */  lw         $t6, 0x18($s0)
    /* 9E77C 8009DB7C 8E030028 */  lw         $v1, 0x28($s0)
    /* 9E780 8009DB80 01F9C021 */  addu       $t8, $t7, $t9
    /* 9E784 8009DB84 8E19001C */  lw         $t9, 0x1C($s0)
    /* 9E788 8009DB88 030E7821 */  addu       $t7, $t8, $t6
    /* 9E78C 8009DB8C 8E0E0020 */  lw         $t6, 0x20($s0)
    /* 9E790 8009DB90 01F9C021 */  addu       $t8, $t7, $t9
    /* 9E794 8009DB94 030E1021 */  addu       $v0, $t8, $t6
    /* 9E798 8009DB98 0043082A */  slt        $at, $v0, $v1
    /* 9E79C 8009DB9C 10200002 */  beqz       $at, .L8009DBA8
    /* 9E7A0 8009DBA0 00627823 */   subu      $t7, $v1, $v0
    /* 9E7A4 8009DBA4 AE0F0010 */  sw         $t7, 0x10($s0)
  .L8009DBA8:
    /* 9E7A8 8009DBA8 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8009DBAC:
    /* 9E7AC 8009DBAC 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 9E7B0 8009DBB0 03E00008 */  jr         $ra
    /* 9E7B4 8009DBB4 00000000 */   nop

glabel _Ldunscale
    /* 9E7B8 8009DBB8 03E00008 */  jr         $ra
    /* 9E7BC 8009DBBC 00000000 */   nop

glabel _Ldtob
    /* 9E7C0 8009DBC0 27BDFF30 */  addiu      $sp, $sp, -0xD0
    /* 9E7C4 8009DBC4 AFBF003C */  sw         $ra, 0x3C($sp)
    /* 9E7C8 8009DBC8 AFB50038 */  sw         $s5, 0x38($sp)
    /* 9E7CC 8009DBCC AFB40034 */  sw         $s4, 0x34($sp)
    /* 9E7D0 8009DBD0 AFB30030 */  sw         $s3, 0x30($sp)
    /* 9E7D4 8009DBD4 AFB2002C */  sw         $s2, 0x2C($sp)
    /* 9E7D8 8009DBD8 AFB10028 */  sw         $s1, 0x28($sp)
    /* 9E7DC 8009DBDC AFB00024 */  sw         $s0, 0x24($sp)
    /* 9E7E0 8009DBE0 F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 9E7E4 8009DBE4 AFA400D0 */  sw         $a0, 0xD0($sp)
    /* 9E7E8 8009DBE8 AFA500D4 */  sw         $a1, 0xD4($sp)
    /* 9E7EC 8009DBEC 8C820024 */  lw         $v0, 0x24($a0)
    /* 9E7F0 8009DBF0 27B500B0 */  addiu      $s5, $sp, 0xB0
    /* 9E7F4 8009DBF4 D4940000 */  ldc1       $f20, 0x0($a0)
    /* 9E7F8 8009DBF8 04410003 */  bgez       $v0, .L8009DC08
    /* 9E7FC 8009DBFC 240F0006 */   addiu     $t7, $zero, 0x6
    /* 9E800 8009DC00 1000000C */  b          .L8009DC34
    /* 9E804 8009DC04 AC8F0024 */   sw        $t7, 0x24($a0)
  .L8009DC08:
    /* 9E808 8009DC08 1440000A */  bnez       $v0, .L8009DC34
    /* 9E80C 8009DC0C 93B800D7 */   lbu       $t8, 0xD7($sp)
    /* 9E810 8009DC10 24010067 */  addiu      $at, $zero, 0x67
    /* 9E814 8009DC14 13010004 */  beq        $t8, $at, .L8009DC28
    /* 9E818 8009DC18 AFB80048 */   sw        $t8, 0x48($sp)
    /* 9E81C 8009DC1C 24010047 */  addiu      $at, $zero, 0x47
    /* 9E820 8009DC20 57010005 */  bnel       $t8, $at, .L8009DC38
    /* 9E824 8009DC24 8FAE00D0 */   lw        $t6, 0xD0($sp)
  .L8009DC28:
    /* 9E828 8009DC28 8FAF00D0 */  lw         $t7, 0xD0($sp)
    /* 9E82C 8009DC2C 24190001 */  addiu      $t9, $zero, 0x1
    /* 9E830 8009DC30 ADF90024 */  sw         $t9, 0x24($t7)
  .L8009DC34:
    /* 9E834 8009DC34 8FAE00D0 */  lw         $t6, 0xD0($sp)
  .L8009DC38:
    /* 9E838 8009DC38 240107FF */  addiu      $at, $zero, 0x7FF
    /* 9E83C 8009DC3C 95C40000 */  lhu        $a0, 0x0($t6)
    /* 9E840 8009DC40 30837FF0 */  andi       $v1, $a0, 0x7FF0
    /* 9E844 8009DC44 0003C103 */  sra        $t8, $v1, 4
    /* 9E848 8009DC48 0018CC00 */  sll        $t9, $t8, 16
    /* 9E84C 8009DC4C 00191C03 */  sra        $v1, $t9, 16
    /* 9E850 8009DC50 14610018 */  bne        $v1, $at, .L8009DCB4
    /* 9E854 8009DC54 00000000 */   nop
    /* 9E858 8009DC58 A7A0009A */  sh         $zero, 0x9A($sp)
    /* 9E85C 8009DC5C 95D80000 */  lhu        $t8, 0x0($t6)
    /* 9E860 8009DC60 24030002 */  addiu      $v1, $zero, 0x2
    /* 9E864 8009DC64 00031400 */  sll        $v0, $v1, 16
    /* 9E868 8009DC68 3319000F */  andi       $t9, $t8, 0xF
    /* 9E86C 8009DC6C 5720000A */  bnel       $t9, $zero, .L8009DC98
    /* 9E870 8009DC70 00027C03 */   sra       $t7, $v0, 16
    /* 9E874 8009DC74 95CF0002 */  lhu        $t7, 0x2($t6)
    /* 9E878 8009DC78 55E00007 */  bnel       $t7, $zero, .L8009DC98
    /* 9E87C 8009DC7C 00027C03 */   sra       $t7, $v0, 16
    /* 9E880 8009DC80 95D80004 */  lhu        $t8, 0x4($t6)
    /* 9E884 8009DC84 57000004 */  bnel       $t8, $zero, .L8009DC98
    /* 9E888 8009DC88 00027C03 */   sra       $t7, $v0, 16
    /* 9E88C 8009DC8C 95D90006 */  lhu        $t9, 0x6($t6)
    /* 9E890 8009DC90 13200003 */  beqz       $t9, .L8009DCA0
    /* 9E894 8009DC94 00027C03 */   sra       $t7, $v0, 16
  .L8009DC98:
    /* 9E898 8009DC98 10000014 */  b          .L8009DCEC
    /* 9E89C 8009DC9C 01E01025 */   or        $v0, $t7, $zero
  .L8009DCA0:
    /* 9E8A0 8009DCA0 24030001 */  addiu      $v1, $zero, 0x1
    /* 9E8A4 8009DCA4 00031400 */  sll        $v0, $v1, 16
    /* 9E8A8 8009DCA8 00027C03 */  sra        $t7, $v0, 16
    /* 9E8AC 8009DCAC 1000000F */  b          .L8009DCEC
    /* 9E8B0 8009DCB0 01E01025 */   or        $v0, $t7, $zero
  .L8009DCB4:
    /* 9E8B4 8009DCB4 18600008 */  blez       $v1, .L8009DCD8
    /* 9E8B8 8009DCB8 3098800F */   andi      $t8, $a0, 0x800F
    /* 9E8BC 8009DCBC 8FB900D0 */  lw         $t9, 0xD0($sp)
    /* 9E8C0 8009DCC0 370E3FF0 */  ori        $t6, $t8, 0x3FF0
    /* 9E8C4 8009DCC4 246FFC02 */  addiu      $t7, $v1, -0x3FE
    /* 9E8C8 8009DCC8 A72E0000 */  sh         $t6, 0x0($t9)
    /* 9E8CC 8009DCCC A7AF009A */  sh         $t7, 0x9A($sp)
    /* 9E8D0 8009DCD0 10000006 */  b          .L8009DCEC
    /* 9E8D4 8009DCD4 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8009DCD8:
    /* 9E8D8 8009DCD8 04610003 */  bgez       $v1, .L8009DCE8
    /* 9E8DC 8009DCDC 00001025 */   or        $v0, $zero, $zero
    /* 9E8E0 8009DCE0 10000002 */  b          .L8009DCEC
    /* 9E8E4 8009DCE4 24020002 */   addiu     $v0, $zero, 0x2
  .L8009DCE8:
    /* 9E8E8 8009DCE8 A7A0009A */  sh         $zero, 0x9A($sp)
  .L8009DCEC:
    /* 9E8EC 8009DCEC 18400012 */  blez       $v0, .L8009DD38
    /* 9E8F0 8009DCF0 0002C400 */   sll       $t8, $v0, 16
    /* 9E8F4 8009DCF4 0002C400 */  sll        $t8, $v0, 16
    /* 9E8F8 8009DCF8 00187403 */  sra        $t6, $t8, 16
    /* 9E8FC 8009DCFC 24010002 */  addiu      $at, $zero, 0x2
    /* 9E900 8009DD00 15C10004 */  bne        $t6, $at, .L8009DD14
    /* 9E904 8009DD04 8FB900D0 */   lw        $t9, 0xD0($sp)
    /* 9E908 8009DD08 3C05800B */  lui        $a1, %hi(D_800B0758)
    /* 9E90C 8009DD0C 10000003 */  b          .L8009DD1C
    /* 9E910 8009DD10 24A50758 */   addiu     $a1, $a1, %lo(D_800B0758)
  .L8009DD14:
    /* 9E914 8009DD14 3C05800B */  lui        $a1, %hi(D_800B075C)
    /* 9E918 8009DD18 24A5075C */  addiu      $a1, $a1, %lo(D_800B075C)
  .L8009DD1C:
    /* 9E91C 8009DD1C 240F0003 */  addiu      $t7, $zero, 0x3
    /* 9E920 8009DD20 AF2F0014 */  sw         $t7, 0x14($t9)
    /* 9E924 8009DD24 8F240008 */  lw         $a0, 0x8($t9)
    /* 9E928 8009DD28 0C025714 */  jal        memcpy
    /* 9E92C 8009DD2C 24060003 */   addiu     $a2, $zero, 0x3
    /* 9E930 8009DD30 100000ED */  b          .L8009E0E8
    /* 9E934 8009DD34 8FBF003C */   lw        $ra, 0x3C($sp)
  .L8009DD38:
    /* 9E938 8009DD38 00187403 */  sra        $t6, $t8, 16
    /* 9E93C 8009DD3C 15C00003 */  bnez       $t6, .L8009DD4C
    /* 9E940 8009DD40 00009825 */   or        $s3, $zero, $zero
    /* 9E944 8009DD44 100000E2 */  b          .L8009E0D0
    /* 9E948 8009DD48 A7A0009A */   sh        $zero, 0x9A($sp)
  .L8009DD4C:
    /* 9E94C 8009DD4C 44801800 */  mtc1       $zero, $f3
    /* 9E950 8009DD50 44801000 */  mtc1       $zero, $f2
    /* 9E954 8009DD54 93AF00D7 */  lbu        $t7, 0xD7($sp)
    /* 9E958 8009DD58 87B9009A */  lh         $t9, 0x9A($sp)
    /* 9E95C 8009DD5C 4622A03C */  c.lt.d     $f20, $f2
    /* 9E960 8009DD60 24017597 */  addiu      $at, $zero, 0x7597
    /* 9E964 8009DD64 00001825 */  or         $v1, $zero, $zero
    /* 9E968 8009DD68 27B500B1 */  addiu      $s5, $sp, 0xB1
    /* 9E96C 8009DD6C 45000002 */  bc1f       .L8009DD78
    /* 9E970 8009DD70 AFAF0048 */   sw        $t7, 0x48($sp)
    /* 9E974 8009DD74 4620A507 */  neg.d      $f20, $f20
  .L8009DD78:
    /* 9E978 8009DD78 03210019 */  multu      $t9, $at
    /* 9E97C 8009DD7C 3C010001 */  lui        $at, (0x186A0 >> 16)
    /* 9E980 8009DD80 342186A0 */  ori        $at, $at, (0x186A0 & 0xFFFF)
    /* 9E984 8009DD84 24050006 */  addiu      $a1, $zero, 0x6
    /* 9E988 8009DD88 0000C012 */  mflo       $t8
    /* 9E98C 8009DD8C 00000000 */  nop
    /* 9E990 8009DD90 00000000 */  nop
    /* 9E994 8009DD94 0301001A */  div        $zero, $t8, $at
    /* 9E998 8009DD98 00007012 */  mflo       $t6
    /* 9E99C 8009DD9C 25CFFFFC */  addiu      $t7, $t6, -0x4
    /* 9E9A0 8009DDA0 000FCC00 */  sll        $t9, $t7, 16
    /* 9E9A4 8009DDA4 0019C403 */  sra        $t8, $t9, 16
    /* 9E9A8 8009DDA8 07010019 */  bgez       $t8, .L8009DE10
    /* 9E9AC 8009DDAC A7AF009A */   sh        $t7, 0x9A($sp)
    /* 9E9B0 8009DDB0 000FCC00 */  sll        $t9, $t7, 16
    /* 9E9B4 8009DDB4 0019C403 */  sra        $t8, $t9, 16
    /* 9E9B8 8009DDB8 240E0003 */  addiu      $t6, $zero, 0x3
    /* 9E9BC 8009DDBC 01D82023 */  subu       $a0, $t6, $t8
    /* 9E9C0 8009DDC0 2401FFFC */  addiu      $at, $zero, -0x4
    /* 9E9C4 8009DDC4 00811024 */  and        $v0, $a0, $at
    /* 9E9C8 8009DDC8 0002C823 */  negu       $t9, $v0
    /* 9E9CC 8009DDCC 1840002C */  blez       $v0, .L8009DE80
    /* 9E9D0 8009DDD0 A7B9009A */   sh        $t9, 0x9A($sp)
    /* 9E9D4 8009DDD4 3C04800B */  lui        $a0, %hi(D_800B0710)
    /* 9E9D8 8009DDD8 24840710 */  addiu      $a0, $a0, %lo(D_800B0710)
  .L8009DDDC:
    /* 9E9DC 8009DDDC 304E0001 */  andi       $t6, $v0, 0x1
    /* 9E9E0 8009DDE0 11C00006 */  beqz       $t6, .L8009DDFC
    /* 9E9E4 8009DDE4 0002C843 */   sra       $t9, $v0, 1
    /* 9E9E8 8009DDE8 0003C0C0 */  sll        $t8, $v1, 3
    /* 9E9EC 8009DDEC 00987821 */  addu       $t7, $a0, $t8
    /* 9E9F0 8009DDF0 D5E40000 */  ldc1       $f4, 0x0($t7)
    /* 9E9F4 8009DDF4 4624A502 */  mul.d      $f20, $f20, $f4
    /* 9E9F8 8009DDF8 00000000 */  nop
  .L8009DDFC:
    /* 9E9FC 8009DDFC 03201025 */  or         $v0, $t9, $zero
    /* 9EA00 8009DE00 1F20FFF6 */  bgtz       $t9, .L8009DDDC
    /* 9EA04 8009DE04 24630001 */   addiu     $v1, $v1, 0x1
    /* 9EA08 8009DE08 1000001E */  b          .L8009DE84
    /* 9EA0C 8009DE0C 8FAF0048 */   lw        $t7, 0x48($sp)
  .L8009DE10:
    /* 9EA10 8009DE10 87AE009A */  lh         $t6, 0x9A($sp)
    /* 9EA14 8009DE14 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
    /* 9EA18 8009DE18 00001825 */  or         $v1, $zero, $zero
    /* 9EA1C 8009DE1C 19C00018 */  blez       $t6, .L8009DE80
    /* 9EA20 8009DE20 31D8FFFC */   andi      $t8, $t6, 0xFFFC
    /* 9EA24 8009DE24 00181400 */  sll        $v0, $t8, 16
    /* 9EA28 8009DE28 0018CC00 */  sll        $t9, $t8, 16
    /* 9EA2C 8009DE2C 44810800 */  mtc1       $at, $f1
    /* 9EA30 8009DE30 44800000 */  mtc1       $zero, $f0
    /* 9EA34 8009DE34 00197403 */  sra        $t6, $t9, 16
    /* 9EA38 8009DE38 00027C03 */  sra        $t7, $v0, 16
    /* 9EA3C 8009DE3C A7B8009A */  sh         $t8, 0x9A($sp)
    /* 9EA40 8009DE40 19C0000E */  blez       $t6, .L8009DE7C
    /* 9EA44 8009DE44 01E01025 */   or        $v0, $t7, $zero
    /* 9EA48 8009DE48 3C04800B */  lui        $a0, %hi(D_800B0710)
    /* 9EA4C 8009DE4C 24840710 */  addiu      $a0, $a0, %lo(D_800B0710)
  .L8009DE50:
    /* 9EA50 8009DE50 304F0001 */  andi       $t7, $v0, 0x1
    /* 9EA54 8009DE54 11E00006 */  beqz       $t7, .L8009DE70
    /* 9EA58 8009DE58 00027043 */   sra       $t6, $v0, 1
    /* 9EA5C 8009DE5C 0003C0C0 */  sll        $t8, $v1, 3
    /* 9EA60 8009DE60 0098C821 */  addu       $t9, $a0, $t8
    /* 9EA64 8009DE64 D7260000 */  ldc1       $f6, 0x0($t9)
    /* 9EA68 8009DE68 46260002 */  mul.d      $f0, $f0, $f6
    /* 9EA6C 8009DE6C 00000000 */  nop
  .L8009DE70:
    /* 9EA70 8009DE70 01C01025 */  or         $v0, $t6, $zero
    /* 9EA74 8009DE74 1DC0FFF6 */  bgtz       $t6, .L8009DE50
    /* 9EA78 8009DE78 24630001 */   addiu     $v1, $v1, 0x1
  .L8009DE7C:
    /* 9EA7C 8009DE7C 4620A503 */  div.d      $f20, $f20, $f0
  .L8009DE80:
    /* 9EA80 8009DE80 8FAF0048 */  lw         $t7, 0x48($sp)
  .L8009DE84:
    /* 9EA84 8009DE84 24010066 */  addiu      $at, $zero, 0x66
    /* 9EA88 8009DE88 8FB800D0 */  lw         $t8, 0xD0($sp)
    /* 9EA8C 8009DE8C 15E10004 */  bne        $t7, $at, .L8009DEA0
    /* 9EA90 8009DE90 240E0030 */   addiu     $t6, $zero, 0x30
    /* 9EA94 8009DE94 87A5009A */  lh         $a1, 0x9A($sp)
    /* 9EA98 8009DE98 10000001 */  b          .L8009DEA0
    /* 9EA9C 8009DE9C 24A5000A */   addiu     $a1, $a1, 0xA
  .L8009DEA0:
    /* 9EAA0 8009DEA0 8F190024 */  lw         $t9, 0x24($t8)
    /* 9EAA4 8009DEA4 00B9A021 */  addu       $s4, $a1, $t9
    /* 9EAA8 8009DEA8 2A810014 */  slti       $at, $s4, 0x14
    /* 9EAAC 8009DEAC 14200002 */  bnez       $at, .L8009DEB8
    /* 9EAB0 8009DEB0 00000000 */   nop
    /* 9EAB4 8009DEB4 24140013 */  addiu      $s4, $zero, 0x13
  .L8009DEB8:
    /* 9EAB8 8009DEB8 1A800033 */  blez       $s4, .L8009DF88
    /* 9EABC 8009DEBC A3AE00B0 */   sb        $t6, 0xB0($sp)
    /* 9EAC0 8009DEC0 4634103C */  c.lt.d     $f2, $f20
    /* 9EAC4 8009DEC4 24130030 */  addiu      $s3, $zero, 0x30
    /* 9EAC8 8009DEC8 27B20074 */  addiu      $s2, $sp, 0x74
    /* 9EACC 8009DECC 4502002F */  bc1fl      .L8009DF8C
    /* 9EAD0 8009DED0 87B8009A */   lh        $t8, 0x9A($sp)
    /* 9EAD4 8009DED4 4620A20D */  trunc.w.d  $f8, $f20
  .L8009DED8:
    /* 9EAD8 8009DED8 2694FFF8 */  addiu      $s4, $s4, -0x8
    /* 9EADC 8009DEDC 26B50008 */  addiu      $s5, $s5, 0x8
    /* 9EAE0 8009DEE0 44114000 */  mfc1       $s1, $f8
    /* 9EAE4 8009DEE4 1A800008 */  blez       $s4, .L8009DF08
    /* 9EAE8 8009DEE8 00000000 */   nop
    /* 9EAEC 8009DEEC 44915000 */  mtc1       $s1, $f10
    /* 9EAF0 8009DEF0 3C01800B */  lui        $at, %hi(D_800B0768)
    /* 9EAF4 8009DEF4 D4280768 */  ldc1       $f8, %lo(D_800B0768)($at)
    /* 9EAF8 8009DEF8 46805121 */  cvt.d.w    $f4, $f10
    /* 9EAFC 8009DEFC 4624A181 */  sub.d      $f6, $f20, $f4
    /* 9EB00 8009DF00 46283502 */  mul.d      $f20, $f6, $f8
    /* 9EB04 8009DF04 00000000 */  nop
  .L8009DF08:
    /* 9EB08 8009DF08 1A200011 */  blez       $s1, .L8009DF50
    /* 9EB0C 8009DF0C 24100008 */   addiu     $s0, $zero, 0x8
    /* 9EB10 8009DF10 24100007 */  addiu      $s0, $zero, 0x7
    /* 9EB14 8009DF14 0600000E */  bltz       $s0, .L8009DF50
    /* 9EB18 8009DF18 02402025 */   or        $a0, $s2, $zero
  .L8009DF1C:
    /* 9EB1C 8009DF1C 02202825 */  or         $a1, $s1, $zero
    /* 9EB20 8009DF20 0C027884 */  jal        ldiv
    /* 9EB24 8009DF24 2406000A */   addiu     $a2, $zero, 0xA
    /* 9EB28 8009DF28 8FB80078 */  lw         $t8, 0x78($sp)
    /* 9EB2C 8009DF2C 26B5FFFF */  addiu      $s5, $s5, -0x1
    /* 9EB30 8009DF30 27190030 */  addiu      $t9, $t8, 0x30
    /* 9EB34 8009DF34 A2B90000 */  sb         $t9, 0x0($s5)
    /* 9EB38 8009DF38 8FB10074 */  lw         $s1, 0x74($sp)
    /* 9EB3C 8009DF3C 5A200005 */  blezl      $s1, .L8009DF54
    /* 9EB40 8009DF40 44801800 */   mtc1      $zero, $f3
    /* 9EB44 8009DF44 2610FFFF */  addiu      $s0, $s0, -0x1
    /* 9EB48 8009DF48 0603FFF4 */  bgezl      $s0, .L8009DF1C
    /* 9EB4C 8009DF4C 02402025 */   or        $a0, $s2, $zero
  .L8009DF50:
    /* 9EB50 8009DF50 44801800 */  mtc1       $zero, $f3
  .L8009DF54:
    /* 9EB54 8009DF54 44801000 */  mtc1       $zero, $f2
    /* 9EB58 8009DF58 2610FFFF */  addiu      $s0, $s0, -0x1
    /* 9EB5C 8009DF5C 06000004 */  bltz       $s0, .L8009DF70
  .L8009DF60:
    /* 9EB60 8009DF60 2610FFFF */   addiu     $s0, $s0, -0x1
    /* 9EB64 8009DF64 26B5FFFF */  addiu      $s5, $s5, -0x1
    /* 9EB68 8009DF68 0601FFFD */  bgez       $s0, .L8009DF60
    /* 9EB6C 8009DF6C A2B30000 */   sb        $s3, 0x0($s5)
  .L8009DF70:
    /* 9EB70 8009DF70 1A800005 */  blez       $s4, .L8009DF88
    /* 9EB74 8009DF74 26B50008 */   addiu     $s5, $s5, 0x8
    /* 9EB78 8009DF78 4634103C */  c.lt.d     $f2, $f20
    /* 9EB7C 8009DF7C 00000000 */  nop
    /* 9EB80 8009DF80 4503FFD5 */  bc1tl      .L8009DED8
    /* 9EB84 8009DF84 4620A20D */   trunc.w.d $f8, $f20
  .L8009DF88:
    /* 9EB88 8009DF88 87B8009A */  lh         $t8, 0x9A($sp)
  .L8009DF8C:
    /* 9EB8C 8009DF8C 93AE00B1 */  lbu        $t6, 0xB1($sp)
    /* 9EB90 8009DF90 27AF00B0 */  addiu      $t7, $sp, 0xB0
    /* 9EB94 8009DF94 24020030 */  addiu      $v0, $zero, 0x30
    /* 9EB98 8009DF98 02AFA023 */  subu       $s4, $s5, $t7
    /* 9EB9C 8009DF9C 27190007 */  addiu      $t9, $t8, 0x7
    /* 9EBA0 8009DFA0 2694FFFF */  addiu      $s4, $s4, -0x1
    /* 9EBA4 8009DFA4 A7B9009A */  sh         $t9, 0x9A($sp)
    /* 9EBA8 8009DFA8 144E0009 */  bne        $v0, $t6, .L8009DFD0
    /* 9EBAC 8009DFAC 27B500B1 */   addiu     $s5, $sp, 0xB1
    /* 9EBB0 8009DFB0 87AF009A */  lh         $t7, 0x9A($sp)
  .L8009DFB4:
    /* 9EBB4 8009DFB4 26B50001 */  addiu      $s5, $s5, 0x1
    /* 9EBB8 8009DFB8 2694FFFF */  addiu      $s4, $s4, -0x1
    /* 9EBBC 8009DFBC 25F8FFFF */  addiu      $t8, $t7, -0x1
    /* 9EBC0 8009DFC0 A7B8009A */  sh         $t8, 0x9A($sp)
    /* 9EBC4 8009DFC4 92B90000 */  lbu        $t9, 0x0($s5)
    /* 9EBC8 8009DFC8 5059FFFA */  beql       $v0, $t9, .L8009DFB4
    /* 9EBCC 8009DFCC 87AF009A */   lh        $t7, 0x9A($sp)
  .L8009DFD0:
    /* 9EBD0 8009DFD0 8FAE0048 */  lw         $t6, 0x48($sp)
    /* 9EBD4 8009DFD4 24010066 */  addiu      $at, $zero, 0x66
    /* 9EBD8 8009DFD8 8FB800D0 */  lw         $t8, 0xD0($sp)
    /* 9EBDC 8009DFDC 15C10004 */  bne        $t6, $at, .L8009DFF0
    /* 9EBE0 8009DFE0 8FAF0048 */   lw        $t7, 0x48($sp)
    /* 9EBE4 8009DFE4 87A5009A */  lh         $a1, 0x9A($sp)
    /* 9EBE8 8009DFE8 10000009 */  b          .L8009E010
    /* 9EBEC 8009DFEC 24A50001 */   addiu     $a1, $a1, 0x1
  .L8009DFF0:
    /* 9EBF0 8009DFF0 24010065 */  addiu      $at, $zero, 0x65
    /* 9EBF4 8009DFF4 11E10003 */  beq        $t7, $at, .L8009E004
    /* 9EBF8 8009DFF8 24010045 */   addiu     $at, $zero, 0x45
    /* 9EBFC 8009DFFC 15E10003 */  bne        $t7, $at, .L8009E00C
    /* 9EC00 8009E000 00001025 */   or        $v0, $zero, $zero
  .L8009E004:
    /* 9EC04 8009E004 10000001 */  b          .L8009E00C
    /* 9EC08 8009E008 24020001 */   addiu     $v0, $zero, 0x1
  .L8009E00C:
    /* 9EC0C 8009E00C 00402825 */  or         $a1, $v0, $zero
  .L8009E010:
    /* 9EC10 8009E010 8F190024 */  lw         $t9, 0x24($t8)
    /* 9EC14 8009E014 00B99821 */  addu       $s3, $a1, $t9
    /* 9EC18 8009E018 00137400 */  sll        $t6, $s3, 16
    /* 9EC1C 8009E01C 000E9C03 */  sra        $s3, $t6, 16
    /* 9EC20 8009E020 0293082A */  slt        $at, $s4, $s3
    /* 9EC24 8009E024 10200004 */  beqz       $at, .L8009E038
    /* 9EC28 8009E028 00000000 */   nop
    /* 9EC2C 8009E02C 00149C00 */  sll        $s3, $s4, 16
    /* 9EC30 8009E030 0013C403 */  sra        $t8, $s3, 16
    /* 9EC34 8009E034 03009825 */  or         $s3, $t8, $zero
  .L8009E038:
    /* 9EC38 8009E038 1A600025 */  blez       $s3, .L8009E0D0
    /* 9EC3C 8009E03C 0274082A */   slt       $at, $s3, $s4
    /* 9EC40 8009E040 10200007 */  beqz       $at, .L8009E060
    /* 9EC44 8009E044 02751021 */   addu      $v0, $s3, $s5
    /* 9EC48 8009E048 90590000 */  lbu        $t9, 0x0($v0)
    /* 9EC4C 8009E04C 2B210035 */  slti       $at, $t9, 0x35
    /* 9EC50 8009E050 54200004 */  bnel       $at, $zero, .L8009E064
    /* 9EC54 8009E054 24050030 */   addiu     $a1, $zero, 0x30
    /* 9EC58 8009E058 10000003 */  b          .L8009E068
    /* 9EC5C 8009E05C 24050039 */   addiu     $a1, $zero, 0x39
  .L8009E060:
    /* 9EC60 8009E060 24050030 */  addiu      $a1, $zero, 0x30
  .L8009E064:
    /* 9EC64 8009E064 02751021 */  addu       $v0, $s3, $s5
  .L8009E068:
    /* 9EC68 8009E068 904EFFFF */  lbu        $t6, -0x1($v0)
    /* 9EC6C 8009E06C 2663FFFF */  addiu      $v1, $s3, -0x1
    /* 9EC70 8009E070 00A02025 */  or         $a0, $a1, $zero
    /* 9EC74 8009E074 14AE0009 */  bne        $a1, $t6, .L8009E09C
    /* 9EC78 8009E078 24010039 */   addiu     $at, $zero, 0x39
    /* 9EC7C 8009E07C 00751021 */  addu       $v0, $v1, $s5
  .L8009E080:
    /* 9EC80 8009E080 9059FFFF */  lbu        $t9, -0x1($v0)
    /* 9EC84 8009E084 2673FFFF */  addiu      $s3, $s3, -0x1
    /* 9EC88 8009E088 00137C00 */  sll        $t7, $s3, 16
    /* 9EC8C 8009E08C 2463FFFF */  addiu      $v1, $v1, -0x1
    /* 9EC90 8009E090 2442FFFF */  addiu      $v0, $v0, -0x1
    /* 9EC94 8009E094 1099FFFA */  beq        $a0, $t9, .L8009E080
    /* 9EC98 8009E098 000F9C03 */   sra       $s3, $t7, 16
  .L8009E09C:
    /* 9EC9C 8009E09C 14810004 */  bne        $a0, $at, .L8009E0B0
    /* 9ECA0 8009E0A0 02A31021 */   addu      $v0, $s5, $v1
    /* 9ECA4 8009E0A4 904E0000 */  lbu        $t6, 0x0($v0)
    /* 9ECA8 8009E0A8 25CF0001 */  addiu      $t7, $t6, 0x1
    /* 9ECAC 8009E0AC A04F0000 */  sb         $t7, 0x0($v0)
  .L8009E0B0:
    /* 9ECB0 8009E0B0 04610007 */  bgez       $v1, .L8009E0D0
    /* 9ECB4 8009E0B4 87AE009A */   lh        $t6, 0x9A($sp)
    /* 9ECB8 8009E0B8 26730001 */  addiu      $s3, $s3, 0x1
    /* 9ECBC 8009E0BC 0013C400 */  sll        $t8, $s3, 16
    /* 9ECC0 8009E0C0 25CF0001 */  addiu      $t7, $t6, 0x1
    /* 9ECC4 8009E0C4 A7AF009A */  sh         $t7, 0x9A($sp)
    /* 9ECC8 8009E0C8 00189C03 */  sra        $s3, $t8, 16
    /* 9ECCC 8009E0CC 26B5FFFF */  addiu      $s5, $s5, -0x1
  .L8009E0D0:
    /* 9ECD0 8009E0D0 8FB000D0 */  lw         $s0, 0xD0($sp)
    /* 9ECD4 8009E0D4 93B400D7 */  lbu        $s4, 0xD7($sp)
    /* 9ECD8 8009E0D8 02A08825 */  or         $s1, $s5, $zero
    /* 9ECDC 8009E0DC 0C027594 */  jal        _Genld
    /* 9ECE0 8009E0E0 87B2009A */   lh        $s2, 0x9A($sp)
    /* 9ECE4 8009E0E4 8FBF003C */  lw         $ra, 0x3C($sp)
  .L8009E0E8:
    /* 9ECE8 8009E0E8 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 9ECEC 8009E0EC 8FB00024 */  lw         $s0, 0x24($sp)
    /* 9ECF0 8009E0F0 8FB10028 */  lw         $s1, 0x28($sp)
    /* 9ECF4 8009E0F4 8FB2002C */  lw         $s2, 0x2C($sp)
    /* 9ECF8 8009E0F8 8FB30030 */  lw         $s3, 0x30($sp)
    /* 9ECFC 8009E0FC 8FB40034 */  lw         $s4, 0x34($sp)
    /* 9ED00 8009E100 8FB50038 */  lw         $s5, 0x38($sp)
    /* 9ED04 8009E104 03E00008 */  jr         $ra
    /* 9ED08 8009E108 27BD00D0 */   addiu     $sp, $sp, 0xD0
    /* 9ED0C 8009E10C 00000000 */  nop
