compiler_type = "ido"

[preserve_macros]
"g[DS]P.*" = "void"
"gDma.*" = "void"
"gDkr.*" = "void"
"fast3d_cmd" = "void"
"OS_PHYSICAL_TO_K0" = "void *"
"_SHIFTL" = "unsigned int"

[decompme.compilers]
"tools/ido-recomp/linux/cc" = "ido5.3"
