.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel func_80000400_1000
    /* 1000 80000400 3C08800B */  lui        $t0, %hi(D_800B16B0_B22B0)
    /* 1004 80000404 3C090005 */  lui        $t1, (0x54DC0 >> 16)
    /* 1008 80000408 250816B0 */  addiu      $t0, $t0, %lo(D_800B16B0_B22B0)
    /* 100C 8000040C 35294DC0 */  ori        $t1, $t1, (0x54DC0 & 0xFFFF)
  .L80000410_1010:
    /* 1010 80000410 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1014 80000414 AD000000 */  sw         $zero, 0x0($t0)
    /* 1018 80000418 AD000004 */  sw         $zero, 0x4($t0)
    /* 101C 8000041C 1520FFFC */  bnez       $t1, .L80000410_1010
    /* 1020 80000420 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1024 80000424 3C0A8004 */  lui        $t2, %hi(boot)
    /* 1028 80000428 3C1D8010 */  lui        $sp, %hi(D_800FAF90_FBB90)
    /* 102C 8000042C 254AF030 */  addiu      $t2, $t2, %lo(boot)
    /* 1030 80000430 01400008 */  jr         $t2
    /* 1034 80000434 27BDAF90 */   addiu     $sp, $sp, %lo(D_800FAF90_FBB90)
    /* 1038 80000438 00000000 */  nop
    /* 103C 8000043C 00000000 */  nop
    /* 1040 80000440 00000000 */  nop
    /* 1044 80000444 00000000 */  nop
    /* 1048 80000448 00000000 */  nop
    /* 104C 8000044C 00000000 */  nop
