.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .rodata

glabel gzip_border
.byte 16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15

glabel gzip_cplens
.half 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115, 131, 163, 195, 227, 258, 0, 0

glabel gzip_cplext
.byte 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0, 99, 99

glabel gzip_cpdist
.half 1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577

glabel gzip_cpdext
.byte 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13

glabel gzip_mask_bits
.half 0x0000, 0x0001, 0x0003, 0x0007, 0x000f, 0x001f, 0x003f, 0x007f, 0x00ff, 0x01ff, 0x03ff, 0x07ff, 0x0fff, 0x1fff, 0x3fff, 0x7fff, 0xffff

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel inflate_block
    /* 73F70 80073370 3C0B8010 */  lui        $t3, %hi(rzip_num_bits)
    /* 73F74 80073374 8D6B5224 */  lw         $t3, %lo(rzip_num_bits)($t3)
    /* 73F78 80073378 3C018010 */  lui        $at, %hi(rzip_hufts)
    /* 73F7C 8007337C AC205228 */  sw         $zero, %lo(rzip_hufts)($at)
    /* 73F80 80073380 24080001 */  addiu      $t0, $zero, 0x1
    /* 73F84 80073384 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 73F88 80073388 3C0C800A */  lui        $t4, %hi(rzip_inflate_input)
    /* 73F8C 8007338C 3C0A8010 */  lui        $t2, %hi(rzip_bit_buffer)
    /* 73F90 80073390 0168082B */  sltu       $at, $t3, $t0
    /* 73F94 80073394 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 73F98 80073398 AFB00018 */  sw         $s0, 0x18($sp)
    /* 73F9C 8007339C 8D8C7968 */  lw         $t4, %lo(rzip_inflate_input)($t4)
    /* 73FA0 800733A0 10200008 */  beqz       $at, .L800733C4_73FC4
    /* 73FA4 800733A4 8D4A5220 */   lw        $t2, %lo(rzip_bit_buffer)($t2)
  .L800733A8_73FA8:
    /* 73FA8 800733A8 91820000 */  lbu        $v0, 0x0($t4)
    /* 73FAC 800733AC 258C0001 */  addiu      $t4, $t4, 0x1
    /* 73FB0 800733B0 01621004 */  sllv       $v0, $v0, $t3
    /* 73FB4 800733B4 256B0008 */  addiu      $t3, $t3, 0x8
    /* 73FB8 800733B8 0168082A */  slt        $at, $t3, $t0
    /* 73FBC 800733BC 1420FFFA */  bnez       $at, .L800733A8_73FA8
    /* 73FC0 800733C0 01425025 */   or        $t2, $t2, $v0
  .L800733C4_73FC4:
    /* 73FC4 800733C4 31500001 */  andi       $s0, $t2, 0x1
    /* 73FC8 800733C8 010A5006 */  srlv       $t2, $t2, $t0
    /* 73FCC 800733CC 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
    /* 73FD0 800733D0 24080002 */  addiu      $t0, $zero, 0x2
    /* 73FD4 800733D4 0168082B */  sltu       $at, $t3, $t0
    /* 73FD8 800733D8 10200008 */  beqz       $at, .L800733FC_73FFC
    /* 73FDC 800733DC 00000000 */   nop
  .L800733E0_73FE0:
    /* 73FE0 800733E0 91820000 */  lbu        $v0, 0x0($t4)
    /* 73FE4 800733E4 258C0001 */  addiu      $t4, $t4, 0x1
    /* 73FE8 800733E8 01621004 */  sllv       $v0, $v0, $t3
    /* 73FEC 800733EC 256B0008 */  addiu      $t3, $t3, 0x8
    /* 73FF0 800733F0 0168082A */  slt        $at, $t3, $t0
    /* 73FF4 800733F4 1420FFFA */  bnez       $at, .L800733E0_73FE0
    /* 73FF8 800733F8 01425025 */   or        $t2, $t2, $v0
  .L800733FC_73FFC:
    /* 73FFC 800733FC 3C01800A */  lui        $at, %hi(rzip_inflate_input)
    /* 74000 80073400 31490003 */  andi       $t1, $t2, 0x3
    /* 74004 80073404 AC2C7968 */  sw         $t4, %lo(rzip_inflate_input)($at)
    /* 74008 80073408 010A5006 */  srlv       $t2, $t2, $t0
    /* 7400C 8007340C 3C018010 */  lui        $at, %hi(rzip_bit_buffer)
    /* 74010 80073410 AC2A5220 */  sw         $t2, %lo(rzip_bit_buffer)($at)
    /* 74014 80073414 01685822 */  sub        $t3, $t3, $t0 /* handwritten instruction */
    /* 74018 80073418 3C018010 */  lui        $at, %hi(rzip_num_bits)
    /* 7401C 8007341C AC2B5224 */  sw         $t3, %lo(rzip_num_bits)($at)
    /* 74020 80073420 24010002 */  addiu      $at, $zero, 0x2
    /* 74024 80073424 1121000B */  beq        $t1, $at, .L80073454_74054
    /* 74028 80073428 24010001 */   addiu     $at, $zero, 0x1
    /* 7402C 8007342C 11210005 */  beq        $t1, $at, .L80073444_74044
    /* 74030 80073430 00000000 */   nop
    /* 74034 80073434 0C01CE79 */  jal        inflate_stored
    /* 74038 80073438 00000000 */   nop
    /* 7403C 8007343C 0801CD17 */  j          .L8007345C_7405C
    /* 74040 80073440 00000000 */   nop
  .L80073444_74044:
    /* 74044 80073444 0C01CE23 */  jal        inflate_fixed
    /* 74048 80073448 00000000 */   nop
    /* 7404C 8007344C 0801CD17 */  j          .L8007345C_7405C
    /* 74050 80073450 00000000 */   nop
  .L80073454_74054:
    /* 74054 80073454 0C01CD1D */  jal        inflate_dynamic
    /* 74058 80073458 00000000 */   nop
  .L8007345C_7405C:
    /* 7405C 8007345C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 74060 80073460 24020001 */  addiu      $v0, $zero, 0x1
    /* 74064 80073464 00501022 */  sub        $v0, $v0, $s0 /* handwritten instruction */
    /* 74068 80073468 8FB00018 */  lw         $s0, 0x18($sp)
    /* 7406C 8007346C 03E00008 */  jr         $ra
    /* 74070 80073470 27BD0020 */   addiu     $sp, $sp, 0x20

/* Handwritten function */
glabel inflate_dynamic
    /* 74074 80073474 27BDFAC0 */  addiu      $sp, $sp, -0x540
    /* 74078 80073478 AFB30028 */  sw         $s3, 0x28($sp)
    /* 7407C 8007347C 3C138010 */  lui        $s3, %hi(rzip_num_bits)
    /* 74080 80073480 8E735224 */  lw         $s3, %lo(rzip_num_bits)($s3)
    /* 74084 80073484 AFB4002C */  sw         $s4, 0x2C($sp)
    /* 74088 80073488 AFB20024 */  sw         $s2, 0x24($sp)
    /* 7408C 8007348C 24080005 */  addiu      $t0, $zero, 0x5
    /* 74090 80073490 3C14800A */  lui        $s4, %hi(rzip_inflate_input)
    /* 74094 80073494 3C128010 */  lui        $s2, %hi(rzip_bit_buffer)
    /* 74098 80073498 0268082B */  sltu       $at, $s3, $t0
    /* 7409C 8007349C AFBF0030 */  sw         $ra, 0x30($sp)
    /* 740A0 800734A0 AFB10020 */  sw         $s1, 0x20($sp)
    /* 740A4 800734A4 AFB0001C */  sw         $s0, 0x1C($sp)
    /* 740A8 800734A8 8E947968 */  lw         $s4, %lo(rzip_inflate_input)($s4)
    /* 740AC 800734AC 10200008 */  beqz       $at, .L800734D0_740D0
    /* 740B0 800734B0 8E525220 */   lw        $s2, %lo(rzip_bit_buffer)($s2)
  .L800734B4_740B4:
    /* 740B4 800734B4 92820000 */  lbu        $v0, 0x0($s4)
    /* 740B8 800734B8 26940001 */  addiu      $s4, $s4, 0x1
    /* 740BC 800734BC 02621004 */  sllv       $v0, $v0, $s3
    /* 740C0 800734C0 26730008 */  addiu      $s3, $s3, 0x8
    /* 740C4 800734C4 0268082A */  slt        $at, $s3, $t0
    /* 740C8 800734C8 1420FFFA */  bnez       $at, .L800734B4_740B4
    /* 740CC 800734CC 02429025 */   or        $s2, $s2, $v0
  .L800734D0_740D0:
    /* 740D0 800734D0 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
    /* 740D4 800734D4 3251001F */  andi       $s1, $s2, 0x1F
    /* 740D8 800734D8 0268082B */  sltu       $at, $s3, $t0
    /* 740DC 800734DC 26310101 */  addiu      $s1, $s1, 0x101
    /* 740E0 800734E0 10200008 */  beqz       $at, .L80073504_74104
    /* 740E4 800734E4 01129006 */   srlv      $s2, $s2, $t0
  .L800734E8_740E8:
    /* 740E8 800734E8 92820000 */  lbu        $v0, 0x0($s4)
    /* 740EC 800734EC 26940001 */  addiu      $s4, $s4, 0x1
    /* 740F0 800734F0 02621004 */  sllv       $v0, $v0, $s3
    /* 740F4 800734F4 26730008 */  addiu      $s3, $s3, 0x8
    /* 740F8 800734F8 0268082A */  slt        $at, $s3, $t0
    /* 740FC 800734FC 1420FFFA */  bnez       $at, .L800734E8_740E8
    /* 74100 80073500 02429025 */   or        $s2, $s2, $v0
  .L80073504_74104:
    /* 74104 80073504 3250001F */  andi       $s0, $s2, 0x1F
    /* 74108 80073508 01129006 */  srlv       $s2, $s2, $t0
    /* 7410C 8007350C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
    /* 74110 80073510 24080004 */  addiu      $t0, $zero, 0x4
    /* 74114 80073514 0268082B */  sltu       $at, $s3, $t0
    /* 74118 80073518 10200008 */  beqz       $at, .L8007353C_7413C
    /* 7411C 8007351C 26100001 */   addiu     $s0, $s0, 0x1
  .L80073520_74120:
    /* 74120 80073520 92820000 */  lbu        $v0, 0x0($s4)
    /* 74124 80073524 26940001 */  addiu      $s4, $s4, 0x1
    /* 74128 80073528 02621004 */  sllv       $v0, $v0, $s3
    /* 7412C 8007352C 26730008 */  addiu      $s3, $s3, 0x8
    /* 74130 80073530 0268082A */  slt        $at, $s3, $t0
    /* 74134 80073534 1420FFFA */  bnez       $at, .L80073520_74120
    /* 74138 80073538 02429025 */   or        $s2, $s2, $v0
  .L8007353C_7413C:
    /* 7413C 8007353C 324A000F */  andi       $t2, $s2, 0xF
    /* 74140 80073540 254A0004 */  addiu      $t2, $t2, 0x4
    /* 74144 80073544 3C19800B */  lui        $t9, %hi(gzip_border)
    /* 74148 80073548 01129006 */  srlv       $s2, $s2, $t0
    /* 7414C 8007354C 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
    /* 74150 80073550 000A4825 */  or         $t1, $zero, $t2
    /* 74154 80073554 2739F9E0 */  addiu      $t9, $t9, %lo(gzip_border)
    /* 74158 80073558 11400019 */  beqz       $t2, .L800735C0_741C0
    /* 7415C 8007355C 23AF0044 */   addi      $t7, $sp, 0x44 /* handwritten instruction */
  .L80073560_74160:
    /* 74160 80073560 24080003 */  addiu      $t0, $zero, 0x3
    /* 74164 80073564 0268082B */  sltu       $at, $s3, $t0
    /* 74168 80073568 50200009 */  beql       $at, $zero, .L80073590_74190
    /* 7416C 8007356C 93230000 */   lbu       $v1, 0x0($t9)
  .L80073570_74170:
    /* 74170 80073570 92820000 */  lbu        $v0, 0x0($s4)
    /* 74174 80073574 26940001 */  addiu      $s4, $s4, 0x1
    /* 74178 80073578 02621004 */  sllv       $v0, $v0, $s3
    /* 7417C 8007357C 26730008 */  addiu      $s3, $s3, 0x8
    /* 74180 80073580 0268082A */  slt        $at, $s3, $t0
    /* 74184 80073584 1420FFFA */  bnez       $at, .L80073570_74170
    /* 74188 80073588 02429025 */   or        $s2, $s2, $v0
    /* 7418C 8007358C 93230000 */  lbu        $v1, 0x0($t9)
  .L80073590_74190:
    /* 74190 80073590 32420007 */  andi       $v0, $s2, 0x7
    /* 74194 80073594 254AFFFF */  addiu      $t2, $t2, -0x1
    /* 74198 80073598 00031880 */  sll        $v1, $v1, 2
    /* 7419C 8007359C 006F1821 */  addu       $v1, $v1, $t7
    /* 741A0 800735A0 AC620000 */  sw         $v0, 0x0($v1)
    /* 741A4 800735A4 01129006 */  srlv       $s2, $s2, $t0
    /* 741A8 800735A8 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
    /* 741AC 800735AC 1540FFEC */  bnez       $t2, .L80073560_74160
    /* 741B0 800735B0 27390001 */   addiu     $t9, $t9, 0x1
    /* 741B4 800735B4 2D210013 */  sltiu      $at, $t1, 0x13
    /* 741B8 800735B8 5020000A */  beql       $at, $zero, .L800735E4_741E4
    /* 741BC 800735BC 240D0007 */   addiu     $t5, $zero, 0x7
  .L800735C0_741C0:
    /* 741C0 800735C0 93230000 */  lbu        $v1, 0x0($t9)
    /* 741C4 800735C4 25290001 */  addiu      $t1, $t1, 0x1
    /* 741C8 800735C8 29210013 */  slti       $at, $t1, 0x13
    /* 741CC 800735CC 00031880 */  sll        $v1, $v1, 2
    /* 741D0 800735D0 006F1821 */  addu       $v1, $v1, $t7
    /* 741D4 800735D4 AC600000 */  sw         $zero, 0x0($v1)
    /* 741D8 800735D8 1420FFF9 */  bnez       $at, .L800735C0_741C0
    /* 741DC 800735DC 27390001 */   addiu     $t9, $t9, 0x1
    /* 741E0 800735E0 240D0007 */  addiu      $t5, $zero, 0x7
  .L800735E4_741E4:
    /* 741E4 800735E4 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
    /* 741E8 800735E8 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
    /* 741EC 800735EC AFAD0038 */  sw         $t5, 0x38($sp)
    /* 741F0 800735F0 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
    /* 741F4 800735F4 24050013 */  addiu      $a1, $zero, 0x13
    /* 741F8 800735F8 24060013 */  addiu      $a2, $zero, 0x13
    /* 741FC 800735FC 24070000 */  addiu      $a3, $zero, 0x0
    /* 74200 80073600 AFA00010 */  sw         $zero, 0x10($sp)
    /* 74204 80073604 AFA80014 */  sw         $t0, 0x14($sp)
    /* 74208 80073608 0C01CB49 */  jal        huft_build
    /* 7420C 8007360C AFA90018 */   sw        $t1, 0x18($sp)
    /* 74210 80073610 23A90038 */  addi       $t1, $sp, 0x38 /* handwritten instruction */
    /* 74214 80073614 8D2D0000 */  lw         $t5, 0x0($t1)
    /* 74218 80073618 3C02800B */  lui        $v0, %hi(gzip_mask_bits)
    /* 7421C 8007361C 2442FAAC */  addiu      $v0, $v0, %lo(gzip_mask_bits)
    /* 74220 80073620 000D1840 */  sll        $v1, $t5, 1
    /* 74224 80073624 23A80034 */  addi       $t0, $sp, 0x34 /* handwritten instruction */
    /* 74228 80073628 00431020 */  add        $v0, $v0, $v1 /* handwritten instruction */
    /* 7422C 8007362C 8D0E0000 */  lw         $t6, 0x0($t0)
    /* 74230 80073630 0230C820 */  add        $t9, $s1, $s0 /* handwritten instruction */
    /* 74234 80073634 84580000 */  lh         $t8, 0x0($v0)
    /* 74238 80073638 23AF0044 */  addi       $t7, $sp, 0x44 /* handwritten instruction */
    /* 7423C 8007363C 240A0000 */  addiu      $t2, $zero, 0x0
  .L80073640_74240:
    /* 74240 80073640 1320005F */  beqz       $t9, .L800737C0_743C0
    /* 74244 80073644 026D082B */   sltu      $at, $s3, $t5
    /* 74248 80073648 50200009 */  beql       $at, $zero, .L80073670_74270
    /* 7424C 8007364C 02581024 */   and       $v0, $s2, $t8
  .L80073650_74250:
    /* 74250 80073650 92820000 */  lbu        $v0, 0x0($s4)
    /* 74254 80073654 26940001 */  addiu      $s4, $s4, 0x1
    /* 74258 80073658 02621004 */  sllv       $v0, $v0, $s3
    /* 7425C 8007365C 26730008 */  addiu      $s3, $s3, 0x8
    /* 74260 80073660 026D082A */  slt        $at, $s3, $t5
    /* 74264 80073664 1420FFFA */  bnez       $at, .L80073650_74250
    /* 74268 80073668 02429025 */   or        $s2, $s2, $v0
    /* 7426C 8007366C 02581024 */  and        $v0, $s2, $t8
  .L80073670_74270:
    /* 74270 80073670 000210C0 */  sll        $v0, $v0, 3
    /* 74274 80073674 01C24821 */  addu       $t1, $t6, $v0
    /* 74278 80073678 95280004 */  lhu        $t0, 0x4($t1)
    /* 7427C 8007367C 91220001 */  lbu        $v0, 0x1($t1)
    /* 74280 80073680 29010010 */  slti       $at, $t0, 0x10
    /* 74284 80073684 00529006 */  srlv       $s2, $s2, $v0
    /* 74288 80073688 1420001C */  bnez       $at, .L800736FC_742FC
    /* 7428C 8007368C 02629822 */   sub       $s3, $s3, $v0 /* handwritten instruction */
    /* 74290 80073690 24010010 */  addiu      $at, $zero, 0x10
    /* 74294 80073694 1101001E */  beq        $t0, $at, .L80073710_74310
    /* 74298 80073698 24010011 */   addiu     $at, $zero, 0x11
    /* 7429C 8007369C 51010033 */  beql       $t0, $at, .L8007376C_7436C
    /* 742A0 800736A0 24080003 */   addiu     $t0, $zero, 0x3
    /* 742A4 800736A4 24080007 */  addiu      $t0, $zero, 0x7
    /* 742A8 800736A8 0268082B */  sltu       $at, $s3, $t0
    /* 742AC 800736AC 50200009 */  beql       $at, $zero, .L800736D4_742D4
    /* 742B0 800736B0 3249007F */   andi      $t1, $s2, 0x7F
  .L800736B4_742B4:
    /* 742B4 800736B4 92820000 */  lbu        $v0, 0x0($s4)
    /* 742B8 800736B8 26940001 */  addiu      $s4, $s4, 0x1
    /* 742BC 800736BC 02621004 */  sllv       $v0, $v0, $s3
    /* 742C0 800736C0 26730008 */  addiu      $s3, $s3, 0x8
    /* 742C4 800736C4 0268082A */  slt        $at, $s3, $t0
    /* 742C8 800736C8 1420FFFA */  bnez       $at, .L800736B4_742B4
    /* 742CC 800736CC 02429025 */   or        $s2, $s2, $v0
    /* 742D0 800736D0 3249007F */  andi       $t1, $s2, 0x7F
  .L800736D4_742D4:
    /* 742D4 800736D4 2529000B */  addiu      $t1, $t1, 0xB
    /* 742D8 800736D8 01129006 */  srlv       $s2, $s2, $t0
    /* 742DC 800736DC 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
    /* 742E0 800736E0 0329C823 */  subu       $t9, $t9, $t1
  .L800736E4_742E4:
    /* 742E4 800736E4 2529FFFF */  addiu      $t1, $t1, -0x1
    /* 742E8 800736E8 ADE00000 */  sw         $zero, 0x0($t7)
    /* 742EC 800736EC 1520FFFD */  bnez       $t1, .L800736E4_742E4
    /* 742F0 800736F0 25EF0004 */   addiu     $t7, $t7, 0x4
    /* 742F4 800736F4 0801CD90 */  j          .L80073640_74240
    /* 742F8 800736F8 240A0000 */   addiu     $t2, $zero, 0x0
  .L800736FC_742FC:
    /* 742FC 800736FC ADE80000 */  sw         $t0, 0x0($t7)
    /* 74300 80073700 25EF0004 */  addiu      $t7, $t7, 0x4
    /* 74304 80073704 2739FFFF */  addiu      $t9, $t9, -0x1
    /* 74308 80073708 0801CD90 */  j          .L80073640_74240
    /* 7430C 8007370C 00085025 */   or        $t2, $zero, $t0
  .L80073710_74310:
    /* 74310 80073710 24080002 */  addiu      $t0, $zero, 0x2
    /* 74314 80073714 0268082B */  sltu       $at, $s3, $t0
    /* 74318 80073718 50200009 */  beql       $at, $zero, .L80073740_74340
    /* 7431C 8007371C 32490003 */   andi      $t1, $s2, 0x3
  .L80073720_74320:
    /* 74320 80073720 92820000 */  lbu        $v0, 0x0($s4)
    /* 74324 80073724 26940001 */  addiu      $s4, $s4, 0x1
    /* 74328 80073728 02621004 */  sllv       $v0, $v0, $s3
    /* 7432C 8007372C 26730008 */  addiu      $s3, $s3, 0x8
    /* 74330 80073730 0268082A */  slt        $at, $s3, $t0
    /* 74334 80073734 1420FFFA */  bnez       $at, .L80073720_74320
    /* 74338 80073738 02429025 */   or        $s2, $s2, $v0
    /* 7433C 8007373C 32490003 */  andi       $t1, $s2, 0x3
  .L80073740_74340:
    /* 74340 80073740 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
    /* 74344 80073744 01129006 */  srlv       $s2, $s2, $t0
    /* 74348 80073748 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
    /* 7434C 8007374C 0329C823 */  subu       $t9, $t9, $t1
  .L80073750_74350:
    /* 74350 80073750 2529FFFF */  addiu      $t1, $t1, -0x1
    /* 74354 80073754 ADEA0000 */  sw         $t2, 0x0($t7)
    /* 74358 80073758 1520FFFD */  bnez       $t1, .L80073750_74350
    /* 7435C 8007375C 25EF0004 */   addiu     $t7, $t7, 0x4
    /* 74360 80073760 0801CD90 */  j          .L80073640_74240
    /* 74364 80073764 00000000 */   nop
    /* 74368 80073768 24080003 */  addiu      $t0, $zero, 0x3
  .L8007376C_7436C:
    /* 7436C 8007376C 0268082B */  sltu       $at, $s3, $t0
    /* 74370 80073770 50200009 */  beql       $at, $zero, .L80073798_74398
    /* 74374 80073774 32490007 */   andi      $t1, $s2, 0x7
  .L80073778_74378:
    /* 74378 80073778 92820000 */  lbu        $v0, 0x0($s4)
    /* 7437C 8007377C 26940001 */  addiu      $s4, $s4, 0x1
    /* 74380 80073780 02621004 */  sllv       $v0, $v0, $s3
    /* 74384 80073784 26730008 */  addiu      $s3, $s3, 0x8
    /* 74388 80073788 0268082A */  slt        $at, $s3, $t0
    /* 7438C 8007378C 1420FFFA */  bnez       $at, .L80073778_74378
    /* 74390 80073790 02429025 */   or        $s2, $s2, $v0
    /* 74394 80073794 32490007 */  andi       $t1, $s2, 0x7
  .L80073798_74398:
    /* 74398 80073798 21290003 */  addi       $t1, $t1, 0x3 /* handwritten instruction */
    /* 7439C 8007379C 01129006 */  srlv       $s2, $s2, $t0
    /* 743A0 800737A0 02689822 */  sub        $s3, $s3, $t0 /* handwritten instruction */
    /* 743A4 800737A4 0329C823 */  subu       $t9, $t9, $t1
  .L800737A8_743A8:
    /* 743A8 800737A8 2529FFFF */  addiu      $t1, $t1, -0x1
    /* 743AC 800737AC ADE00000 */  sw         $zero, 0x0($t7)
    /* 743B0 800737B0 1520FFFD */  bnez       $t1, .L800737A8_743A8
    /* 743B4 800737B4 25EF0004 */   addiu     $t7, $t7, 0x4
    /* 743B8 800737B8 0801CD90 */  j          .L80073640_74240
    /* 743BC 800737BC 240A0000 */   addiu     $t2, $zero, 0x0
  .L800737C0_743C0:
    /* 743C0 800737C0 3C01800A */  lui        $at, %hi(rzip_inflate_input)
    /* 743C4 800737C4 AC347968 */  sw         $s4, %lo(rzip_inflate_input)($at)
    /* 743C8 800737C8 3C018010 */  lui        $at, %hi(rzip_bit_buffer)
    /* 743CC 800737CC 24080009 */  addiu      $t0, $zero, 0x9
    /* 743D0 800737D0 AC325220 */  sw         $s2, %lo(rzip_bit_buffer)($at)
    /* 743D4 800737D4 AFA80038 */  sw         $t0, 0x38($sp)
    /* 743D8 800737D8 3C02800B */  lui        $v0, %hi(gzip_cplext)
    /* 743DC 800737DC 3C018010 */  lui        $at, %hi(rzip_num_bits)
    /* 743E0 800737E0 3C07800B */  lui        $a3, %hi(gzip_cplens)
    /* 743E4 800737E4 2442FA32 */  addiu      $v0, $v0, %lo(gzip_cplext)
    /* 743E8 800737E8 23A30034 */  addi       $v1, $sp, 0x34 /* handwritten instruction */
    /* 743EC 800737EC 23A80038 */  addi       $t0, $sp, 0x38 /* handwritten instruction */
    /* 743F0 800737F0 AC335224 */  sw         $s3, %lo(rzip_num_bits)($at)
    /* 743F4 800737F4 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
    /* 743F8 800737F8 00112825 */  or         $a1, $zero, $s1
    /* 743FC 800737FC 24060101 */  addiu      $a2, $zero, 0x101
    /* 74400 80073800 24E7F9F4 */  addiu      $a3, $a3, %lo(gzip_cplens)
    /* 74404 80073804 AFA20010 */  sw         $v0, 0x10($sp)
    /* 74408 80073808 AFA30014 */  sw         $v1, 0x14($sp)
    /* 7440C 8007380C 0C01CB49 */  jal        huft_build
    /* 74410 80073810 AFA80018 */   sw        $t0, 0x18($sp)
    /* 74414 80073814 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
    /* 74418 80073818 00111080 */  sll        $v0, $s1, 2
    /* 7441C 8007381C 24080006 */  addiu      $t0, $zero, 0x6
    /* 74420 80073820 00822021 */  addu       $a0, $a0, $v0
    /* 74424 80073824 AFA80040 */  sw         $t0, 0x40($sp)
    /* 74428 80073828 3C02800B */  lui        $v0, %hi(gzip_cpdext)
    /* 7442C 8007382C 3C07800B */  lui        $a3, %hi(gzip_cpdist)
    /* 74430 80073830 2442FA8E */  addiu      $v0, $v0, %lo(gzip_cpdext)
    /* 74434 80073834 23A3003C */  addi       $v1, $sp, 0x3C /* handwritten instruction */
    /* 74438 80073838 23A80040 */  addi       $t0, $sp, 0x40 /* handwritten instruction */
    /* 7443C 8007383C 00102825 */  or         $a1, $zero, $s0
    /* 74440 80073840 24060000 */  addiu      $a2, $zero, 0x0
    /* 74444 80073844 24E7FA52 */  addiu      $a3, $a3, %lo(gzip_cpdist)
    /* 74448 80073848 AFA20010 */  sw         $v0, 0x10($sp)
    /* 7444C 8007384C AFA30014 */  sw         $v1, 0x14($sp)
    /* 74450 80073850 0C01CB49 */  jal        huft_build
    /* 74454 80073854 AFA80018 */   sw        $t0, 0x18($sp)
    /* 74458 80073858 8FA40034 */  lw         $a0, 0x34($sp)
    /* 7445C 8007385C 8FA5003C */  lw         $a1, 0x3C($sp)
    /* 74460 80073860 8FA60038 */  lw         $a2, 0x38($sp)
    /* 74464 80073864 0C01CEBC */  jal        inflate_codes
    /* 74468 80073868 8FA70040 */   lw        $a3, 0x40($sp)
    /* 7446C 8007386C 8FBF0030 */  lw         $ra, 0x30($sp)
    /* 74470 80073870 8FB4002C */  lw         $s4, 0x2C($sp)
    /* 74474 80073874 8FB30028 */  lw         $s3, 0x28($sp)
    /* 74478 80073878 8FB20024 */  lw         $s2, 0x24($sp)
    /* 7447C 8007387C 8FB10020 */  lw         $s1, 0x20($sp)
    /* 74480 80073880 8FB0001C */  lw         $s0, 0x1C($sp)
    /* 74484 80073884 03E00008 */  jr         $ra
    /* 74488 80073888 27BD0540 */   addiu     $sp, $sp, 0x540

/* Handwritten function */
glabel inflate_fixed
    /* 7448C 8007388C 27BDFAD0 */  addiu      $sp, $sp, -0x530
    /* 74490 80073890 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 74494 80073894 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
    /* 74498 80073898 24080024 */  addiu      $t0, $zero, 0x24
    /* 7449C 8007389C 24090008 */  addiu      $t1, $zero, 0x8
  .L800738A0_744A0:
    /* 744A0 800738A0 2508FFFF */  addiu      $t0, $t0, -0x1
    /* 744A4 800738A4 AD690000 */  sw         $t1, 0x0($t3)
    /* 744A8 800738A8 AD690004 */  sw         $t1, 0x4($t3)
    /* 744AC 800738AC AD690008 */  sw         $t1, 0x8($t3)
    /* 744B0 800738B0 AD69000C */  sw         $t1, 0xC($t3)
    /* 744B4 800738B4 1500FFFA */  bnez       $t0, .L800738A0_744A0
    /* 744B8 800738B8 256B0010 */   addiu     $t3, $t3, 0x10
    /* 744BC 800738BC 2408001C */  addiu      $t0, $zero, 0x1C
    /* 744C0 800738C0 24090009 */  addiu      $t1, $zero, 0x9
  .L800738C4_744C4:
    /* 744C4 800738C4 2508FFFF */  addiu      $t0, $t0, -0x1
    /* 744C8 800738C8 AD690000 */  sw         $t1, 0x0($t3)
    /* 744CC 800738CC AD690004 */  sw         $t1, 0x4($t3)
    /* 744D0 800738D0 AD690008 */  sw         $t1, 0x8($t3)
    /* 744D4 800738D4 AD69000C */  sw         $t1, 0xC($t3)
    /* 744D8 800738D8 1500FFFA */  bnez       $t0, .L800738C4_744C4
    /* 744DC 800738DC 256B0010 */   addiu     $t3, $t3, 0x10
    /* 744E0 800738E0 24080006 */  addiu      $t0, $zero, 0x6
    /* 744E4 800738E4 24090007 */  addiu      $t1, $zero, 0x7
  .L800738E8_744E8:
    /* 744E8 800738E8 2508FFFF */  addiu      $t0, $t0, -0x1
    /* 744EC 800738EC AD690000 */  sw         $t1, 0x0($t3)
    /* 744F0 800738F0 AD690004 */  sw         $t1, 0x4($t3)
    /* 744F4 800738F4 AD690008 */  sw         $t1, 0x8($t3)
    /* 744F8 800738F8 AD69000C */  sw         $t1, 0xC($t3)
    /* 744FC 800738FC 1500FFFA */  bnez       $t0, .L800738E8_744E8
    /* 74500 80073900 256B0010 */   addiu     $t3, $t3, 0x10
    /* 74504 80073904 24090008 */  addiu      $t1, $zero, 0x8
    /* 74508 80073908 AD690000 */  sw         $t1, 0x0($t3)
    /* 7450C 8007390C AD690004 */  sw         $t1, 0x4($t3)
    /* 74510 80073910 AD690008 */  sw         $t1, 0x8($t3)
    /* 74514 80073914 AD69000C */  sw         $t1, 0xC($t3)
    /* 74518 80073918 AD690010 */  sw         $t1, 0x10($t3)
    /* 7451C 8007391C AD690014 */  sw         $t1, 0x14($t3)
    /* 74520 80073920 AD690018 */  sw         $t1, 0x18($t3)
    /* 74524 80073924 AD69001C */  sw         $t1, 0x1C($t3)
    /* 74528 80073928 24080007 */  addiu      $t0, $zero, 0x7
    /* 7452C 8007392C AFA80038 */  sw         $t0, 0x38($sp)
    /* 74530 80073930 3C02800B */  lui        $v0, %hi(gzip_cplext)
    /* 74534 80073934 3C07800B */  lui        $a3, %hi(gzip_cplens)
    /* 74538 80073938 2442FA32 */  addiu      $v0, $v0, %lo(gzip_cplext)
    /* 7453C 8007393C 23A30020 */  addi       $v1, $sp, 0x20 /* handwritten instruction */
    /* 74540 80073940 23A80024 */  addi       $t0, $sp, 0x24 /* handwritten instruction */
    /* 74544 80073944 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
    /* 74548 80073948 24050120 */  addiu      $a1, $zero, 0x120
    /* 7454C 8007394C 24060101 */  addiu      $a2, $zero, 0x101
    /* 74550 80073950 24E7F9F4 */  addiu      $a3, $a3, %lo(gzip_cplens)
    /* 74554 80073954 AFA20010 */  sw         $v0, 0x10($sp)
    /* 74558 80073958 AFA30014 */  sw         $v1, 0x14($sp)
    /* 7455C 8007395C 0C01CB49 */  jal        huft_build
    /* 74560 80073960 AFA80018 */   sw        $t0, 0x18($sp)
    /* 74564 80073964 23AB0044 */  addi       $t3, $sp, 0x44 /* handwritten instruction */
    /* 74568 80073968 2408000A */  addiu      $t0, $zero, 0xA
    /* 7456C 8007396C 24090005 */  addiu      $t1, $zero, 0x5
  .L80073970_74570:
    /* 74570 80073970 2508FFFF */  addiu      $t0, $t0, -0x1
    /* 74574 80073974 AD690000 */  sw         $t1, 0x0($t3)
    /* 74578 80073978 AD690004 */  sw         $t1, 0x4($t3)
    /* 7457C 8007397C AD690008 */  sw         $t1, 0x8($t3)
    /* 74580 80073980 1500FFFB */  bnez       $t0, .L80073970_74570
    /* 74584 80073984 256B000C */   addiu     $t3, $t3, 0xC
    /* 74588 80073988 3C02800B */  lui        $v0, %hi(gzip_cpdext)
    /* 7458C 8007398C 3C07800B */  lui        $a3, %hi(gzip_cpdist)
    /* 74590 80073990 2442FA8E */  addiu      $v0, $v0, %lo(gzip_cpdext)
    /* 74594 80073994 23A30028 */  addi       $v1, $sp, 0x28 /* handwritten instruction */
    /* 74598 80073998 23A8002C */  addi       $t0, $sp, 0x2C /* handwritten instruction */
    /* 7459C 8007399C AFA90040 */  sw         $t1, 0x40($sp)
    /* 745A0 800739A0 23A40044 */  addi       $a0, $sp, 0x44 /* handwritten instruction */
    /* 745A4 800739A4 2405001E */  addiu      $a1, $zero, 0x1E
    /* 745A8 800739A8 24060000 */  addiu      $a2, $zero, 0x0
    /* 745AC 800739AC 24E7FA52 */  addiu      $a3, $a3, %lo(gzip_cpdist)
    /* 745B0 800739B0 AFA20010 */  sw         $v0, 0x10($sp)
    /* 745B4 800739B4 AFA30014 */  sw         $v1, 0x14($sp)
    /* 745B8 800739B8 0C01CB49 */  jal        huft_build
    /* 745BC 800739BC AFA80018 */   sw        $t0, 0x18($sp)
    /* 745C0 800739C0 8FA40020 */  lw         $a0, 0x20($sp)
    /* 745C4 800739C4 8FA50028 */  lw         $a1, 0x28($sp)
    /* 745C8 800739C8 8FA60024 */  lw         $a2, 0x24($sp)
    /* 745CC 800739CC 0C01CEBC */  jal        inflate_codes
    /* 745D0 800739D0 8FA7002C */   lw        $a3, 0x2C($sp)
    /* 745D4 800739D4 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 745D8 800739D8 27BD0530 */  addiu      $sp, $sp, 0x530
    /* 745DC 800739DC 03E00008 */  jr         $ra
    /* 745E0 800739E0 00000000 */   nop

/* Handwritten function */
glabel inflate_stored
    /* 745E4 800739E4 3C0D8010 */  lui        $t5, %hi(rzip_num_bits)
    /* 745E8 800739E8 8DAD5224 */  lw         $t5, %lo(rzip_num_bits)($t5)
    /* 745EC 800739EC 3C0C8010 */  lui        $t4, %hi(rzip_bit_buffer)
    /* 745F0 800739F0 8D8C5220 */  lw         $t4, %lo(rzip_bit_buffer)($t4)
    /* 745F4 800739F4 31A80007 */  andi       $t0, $t5, 0x7
    /* 745F8 800739F8 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
    /* 745FC 800739FC 010C6006 */  srlv       $t4, $t4, $t0
    /* 74600 80073A00 24080010 */  addiu      $t0, $zero, 0x10
    /* 74604 80073A04 3C0F800A */  lui        $t7, %hi(rzip_inflate_input)
    /* 74608 80073A08 3C0E800A */  lui        $t6, %hi(rzip_inflate_output)
    /* 7460C 80073A0C 01A8082B */  sltu       $at, $t5, $t0
    /* 74610 80073A10 8DEF7968 */  lw         $t7, %lo(rzip_inflate_input)($t7)
    /* 74614 80073A14 10200008 */  beqz       $at, .L80073A38_74638
    /* 74618 80073A18 8DCE796C */   lw        $t6, %lo(rzip_inflate_output)($t6)
  .L80073A1C_7461C:
    /* 7461C 80073A1C 91E20000 */  lbu        $v0, 0x0($t7)
    /* 74620 80073A20 25EF0001 */  addiu      $t7, $t7, 0x1
    /* 74624 80073A24 01A21004 */  sllv       $v0, $v0, $t5
    /* 74628 80073A28 25AD0008 */  addiu      $t5, $t5, 0x8
    /* 7462C 80073A2C 01A8082A */  slt        $at, $t5, $t0
    /* 74630 80073A30 1420FFFA */  bnez       $at, .L80073A1C_7461C
    /* 74634 80073A34 01826025 */   or        $t4, $t4, $v0
  .L80073A38_74638:
    /* 74638 80073A38 01A86822 */  sub        $t5, $t5, $t0 /* handwritten instruction */
    /* 7463C 80073A3C 3189FFFF */  andi       $t1, $t4, 0xFFFF
    /* 74640 80073A40 01A8082B */  sltu       $at, $t5, $t0
    /* 74644 80073A44 10200008 */  beqz       $at, .L80073A68_74668
    /* 74648 80073A48 010C6006 */   srlv      $t4, $t4, $t0
  .L80073A4C_7464C:
    /* 7464C 80073A4C 91E20000 */  lbu        $v0, 0x0($t7)
    /* 74650 80073A50 25EF0001 */  addiu      $t7, $t7, 0x1
    /* 74654 80073A54 01A21004 */  sllv       $v0, $v0, $t5
    /* 74658 80073A58 25AD0008 */  addiu      $t5, $t5, 0x8
    /* 7465C 80073A5C 01A8082A */  slt        $at, $t5, $t0
    /* 74660 80073A60 1420FFFA */  bnez       $at, .L80073A4C_7464C
    /* 74664 80073A64 01826025 */   or        $t4, $t4, $v0
  .L80073A68_74668:
    /* 74668 80073A68 31220003 */  andi       $v0, $t1, 0x3
    /* 7466C 80073A6C 010C6006 */  srlv       $t4, $t4, $t0
    /* 74670 80073A70 1040000A */  beqz       $v0, .L80073A9C_7469C
    /* 74674 80073A74 01A86822 */   sub       $t5, $t5, $t0 /* handwritten instruction */
    /* 74678 80073A78 01224822 */  sub        $t1, $t1, $v0 /* handwritten instruction */
  .L80073A7C_7467C:
    /* 7467C 80073A7C 91EA0000 */  lbu        $t2, 0x0($t7)
    /* 74680 80073A80 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
    /* 74684 80073A84 21EF0001 */  addi       $t7, $t7, 0x1 /* handwritten instruction */
    /* 74688 80073A88 21CE0001 */  addi       $t6, $t6, 0x1 /* handwritten instruction */
    /* 7468C 80073A8C 1440FFFB */  bnez       $v0, .L80073A7C_7467C
    /* 74690 80073A90 A1CAFFFF */   sb        $t2, -0x1($t6)
    /* 74694 80073A94 1120000D */  beqz       $t1, .L80073ACC_746CC
    /* 74698 80073A98 00000000 */   nop
  .L80073A9C_7469C:
    /* 7469C 80073A9C 91E20000 */  lbu        $v0, 0x0($t7)
    /* 746A0 80073AA0 2529FFFC */  addiu      $t1, $t1, -0x4
    /* 746A4 80073AA4 25EF0004 */  addiu      $t7, $t7, 0x4
    /* 746A8 80073AA8 A1C20000 */  sb         $v0, 0x0($t6)
    /* 746AC 80073AAC 91E3FFFD */  lbu        $v1, -0x3($t7)
    /* 746B0 80073AB0 25CE0004 */  addiu      $t6, $t6, 0x4
    /* 746B4 80073AB4 A1C3FFFD */  sb         $v1, -0x3($t6)
    /* 746B8 80073AB8 91EAFFFE */  lbu        $t2, -0x2($t7)
    /* 746BC 80073ABC A1CAFFFE */  sb         $t2, -0x2($t6)
    /* 746C0 80073AC0 91EBFFFF */  lbu        $t3, -0x1($t7)
    /* 746C4 80073AC4 1520FFF5 */  bnez       $t1, .L80073A9C_7469C
    /* 746C8 80073AC8 A1CBFFFF */   sb        $t3, -0x1($t6)
  .L80073ACC_746CC:
    /* 746CC 80073ACC 3C01800A */  lui        $at, %hi(rzip_inflate_input)
    /* 746D0 80073AD0 AC2F7968 */  sw         $t7, %lo(rzip_inflate_input)($at)
    /* 746D4 80073AD4 3C01800A */  lui        $at, %hi(rzip_inflate_output)
    /* 746D8 80073AD8 AC2E796C */  sw         $t6, %lo(rzip_inflate_output)($at)
    /* 746DC 80073ADC 3C018010 */  lui        $at, %hi(rzip_bit_buffer)
    /* 746E0 80073AE0 AC2C5220 */  sw         $t4, %lo(rzip_bit_buffer)($at)
    /* 746E4 80073AE4 3C018010 */  lui        $at, %hi(rzip_num_bits)
    /* 746E8 80073AE8 03E00008 */  jr         $ra
    /* 746EC 80073AEC AC2D5224 */   sw        $t5, %lo(rzip_num_bits)($at)

/* Handwritten function */
glabel inflate_codes
    /* 746F0 80073AF0 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 746F4 80073AF4 3C0B800B */  lui        $t3, %hi(gzip_mask_bits)
    /* 746F8 80073AF8 AFB20008 */  sw         $s2, 0x8($sp)
    /* 746FC 80073AFC AFB10004 */  sw         $s1, 0x4($sp)
    /* 74700 80073B00 AFB00000 */  sw         $s0, 0x0($sp)
    /* 74704 80073B04 256BFAAC */  addiu      $t3, $t3, %lo(gzip_mask_bits)
    /* 74708 80073B08 00061040 */  sll        $v0, $a2, 1
    /* 7470C 80073B0C 00074040 */  sll        $t0, $a3, 1
    /* 74710 80073B10 3C12800A */  lui        $s2, %hi(rzip_inflate_input)
    /* 74714 80073B14 3C11800A */  lui        $s1, %hi(rzip_inflate_output)
    /* 74718 80073B18 3C198010 */  lui        $t9, %hi(rzip_bit_buffer)
    /* 7471C 80073B1C 3C108010 */  lui        $s0, %hi(rzip_num_bits)
    /* 74720 80073B20 01621821 */  addu       $v1, $t3, $v0
    /* 74724 80073B24 01684821 */  addu       $t1, $t3, $t0
    /* 74728 80073B28 8E527968 */  lw         $s2, %lo(rzip_inflate_input)($s2)
    /* 7472C 80073B2C 8E31796C */  lw         $s1, %lo(rzip_inflate_output)($s1)
    /* 74730 80073B30 8F395220 */  lw         $t9, %lo(rzip_bit_buffer)($t9)
    /* 74734 80073B34 8E105224 */  lw         $s0, %lo(rzip_num_bits)($s0)
    /* 74738 80073B38 946D0000 */  lhu        $t5, 0x0($v1)
    /* 7473C 80073B3C 952C0000 */  lhu        $t4, 0x0($t1)
  .L80073B40_74740:
    /* 74740 80073B40 0206082B */  sltu       $at, $s0, $a2
  .L80073B44_74744:
    /* 74744 80073B44 50200009 */  beql       $at, $zero, .L80073B6C_7476C
    /* 74748 80073B48 032D1024 */   and       $v0, $t9, $t5
  .L80073B4C_7474C:
    /* 7474C 80073B4C 92420000 */  lbu        $v0, 0x0($s2)
    /* 74750 80073B50 26520001 */  addiu      $s2, $s2, 0x1
    /* 74754 80073B54 02021004 */  sllv       $v0, $v0, $s0
    /* 74758 80073B58 26100008 */  addiu      $s0, $s0, 0x8
    /* 7475C 80073B5C 0206082A */  slt        $at, $s0, $a2
    /* 74760 80073B60 1420FFFA */  bnez       $at, .L80073B4C_7474C
    /* 74764 80073B64 0322C825 */   or        $t9, $t9, $v0
    /* 74768 80073B68 032D1024 */  and        $v0, $t9, $t5
  .L80073B6C_7476C:
    /* 7476C 80073B6C 000210C0 */  sll        $v0, $v0, 3
    /* 74770 80073B70 00827821 */  addu       $t7, $a0, $v0
    /* 74774 80073B74 91F80000 */  lbu        $t8, 0x0($t7)
    /* 74778 80073B78 2B010011 */  slti       $at, $t8, 0x11
    /* 7477C 80073B7C 5420001A */  bnel       $at, $zero, .L80073BE8_747E8
    /* 74780 80073B80 91E20001 */   lbu       $v0, 0x1($t7)
    /* 74784 80073B84 81E30001 */  lb         $v1, 0x1($t7)
  .L80073B88_74788:
    /* 74788 80073B88 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
    /* 7478C 80073B8C 02038022 */  sub        $s0, $s0, $v1 /* handwritten instruction */
    /* 74790 80073B90 0218082B */  sltu       $at, $s0, $t8
    /* 74794 80073B94 10200008 */  beqz       $at, .L80073BB8_747B8
    /* 74798 80073B98 0079C806 */   srlv      $t9, $t9, $v1
  .L80073B9C_7479C:
    /* 7479C 80073B9C 92420000 */  lbu        $v0, 0x0($s2)
    /* 747A0 80073BA0 26520001 */  addiu      $s2, $s2, 0x1
    /* 747A4 80073BA4 02021004 */  sllv       $v0, $v0, $s0
    /* 747A8 80073BA8 26100008 */  addiu      $s0, $s0, 0x8
    /* 747AC 80073BAC 0218082A */  slt        $at, $s0, $t8
    /* 747B0 80073BB0 1420FFFA */  bnez       $at, .L80073B9C_7479C
    /* 747B4 80073BB4 0322C825 */   or        $t9, $t9, $v0
  .L80073BB8_747B8:
    /* 747B8 80073BB8 00181040 */  sll        $v0, $t8, 1
    /* 747BC 80073BBC 004B1021 */  addu       $v0, $v0, $t3
    /* 747C0 80073BC0 94490000 */  lhu        $t1, 0x0($v0)
    /* 747C4 80073BC4 8DE80004 */  lw         $t0, 0x4($t7)
    /* 747C8 80073BC8 01394824 */  and        $t1, $t1, $t9
    /* 747CC 80073BCC 000948C0 */  sll        $t1, $t1, 3
    /* 747D0 80073BD0 01097820 */  add        $t7, $t0, $t1 /* handwritten instruction */
    /* 747D4 80073BD4 91F80000 */  lbu        $t8, 0x0($t7)
    /* 747D8 80073BD8 2F010011 */  sltiu      $at, $t8, 0x11
    /* 747DC 80073BDC 5020FFEA */  beql       $at, $zero, .L80073B88_74788
    /* 747E0 80073BE0 81E30001 */   lb        $v1, 0x1($t7)
    /* 747E4 80073BE4 91E20001 */  lbu        $v0, 0x1($t7)
  .L80073BE8_747E8:
    /* 747E8 80073BE8 24010010 */  addiu      $at, $zero, 0x10
    /* 747EC 80073BEC 0059C806 */  srlv       $t9, $t9, $v0
    /* 747F0 80073BF0 17010005 */  bne        $t8, $at, .L80073C08_74808
    /* 747F4 80073BF4 02028022 */   sub       $s0, $s0, $v0 /* handwritten instruction */
    /* 747F8 80073BF8 95E20004 */  lhu        $v0, 0x4($t7)
    /* 747FC 80073BFC 26310001 */  addiu      $s1, $s1, 0x1
    /* 74800 80073C00 0801CED0 */  j          .L80073B40_74740
    /* 74804 80073C04 A222FFFF */   sb        $v0, -0x1($s1)
  .L80073C08_74808:
    /* 74808 80073C08 2401000F */  addiu      $at, $zero, 0xF
    /* 7480C 80073C0C 13010068 */  beq        $t8, $at, .L80073DB0_749B0
    /* 74810 80073C10 0218082B */   sltu      $at, $s0, $t8
    /* 74814 80073C14 50200009 */  beql       $at, $zero, .L80073C3C_7483C
    /* 74818 80073C18 00181040 */   sll       $v0, $t8, 1
  .L80073C1C_7481C:
    /* 7481C 80073C1C 92420000 */  lbu        $v0, 0x0($s2)
    /* 74820 80073C20 26520001 */  addiu      $s2, $s2, 0x1
    /* 74824 80073C24 02021004 */  sllv       $v0, $v0, $s0
    /* 74828 80073C28 26100008 */  addiu      $s0, $s0, 0x8
    /* 7482C 80073C2C 0218082A */  slt        $at, $s0, $t8
    /* 74830 80073C30 1420FFFA */  bnez       $at, .L80073C1C_7481C
    /* 74834 80073C34 0322C825 */   or        $t9, $t9, $v0
    /* 74838 80073C38 00181040 */  sll        $v0, $t8, 1
  .L80073C3C_7483C:
    /* 7483C 80073C3C 004B1021 */  addu       $v0, $v0, $t3
    /* 74840 80073C40 94490000 */  lhu        $t1, 0x0($v0)
    /* 74844 80073C44 95E80004 */  lhu        $t0, 0x4($t7)
    /* 74848 80073C48 02188022 */  sub        $s0, $s0, $t8 /* handwritten instruction */
    /* 7484C 80073C4C 0207082B */  sltu       $at, $s0, $a3
    /* 74850 80073C50 01394824 */  and        $t1, $t1, $t9
    /* 74854 80073C54 0319C806 */  srlv       $t9, $t9, $t8
    /* 74858 80073C58 10200008 */  beqz       $at, .L80073C7C_7487C
    /* 7485C 80073C5C 01097021 */   addu      $t6, $t0, $t1
  .L80073C60_74860:
    /* 74860 80073C60 92420000 */  lbu        $v0, 0x0($s2)
    /* 74864 80073C64 26520001 */  addiu      $s2, $s2, 0x1
    /* 74868 80073C68 02021004 */  sllv       $v0, $v0, $s0
    /* 7486C 80073C6C 26100008 */  addiu      $s0, $s0, 0x8
    /* 74870 80073C70 0207082A */  slt        $at, $s0, $a3
    /* 74874 80073C74 1420FFFA */  bnez       $at, .L80073C60_74860
    /* 74878 80073C78 0322C825 */   or        $t9, $t9, $v0
  .L80073C7C_7487C:
    /* 7487C 80073C7C 01991024 */  and        $v0, $t4, $t9
    /* 74880 80073C80 000210C0 */  sll        $v0, $v0, 3
    /* 74884 80073C84 00A27821 */  addu       $t7, $a1, $v0
    /* 74888 80073C88 91F80000 */  lbu        $t8, 0x0($t7)
    /* 7488C 80073C8C 2B010011 */  slti       $at, $t8, 0x11
    /* 74890 80073C90 5420001A */  bnel       $at, $zero, .L80073CFC_748FC
    /* 74894 80073C94 91E20001 */   lbu       $v0, 0x1($t7)
    /* 74898 80073C98 91E80001 */  lbu        $t0, 0x1($t7)
  .L80073C9C_7489C:
    /* 7489C 80073C9C 2318FFF0 */  addi       $t8, $t8, -0x10 /* handwritten instruction */
    /* 748A0 80073CA0 02088022 */  sub        $s0, $s0, $t0 /* handwritten instruction */
    /* 748A4 80073CA4 0218082B */  sltu       $at, $s0, $t8
    /* 748A8 80073CA8 10200008 */  beqz       $at, .L80073CCC_748CC
    /* 748AC 80073CAC 0119C806 */   srlv      $t9, $t9, $t0
  .L80073CB0_748B0:
    /* 748B0 80073CB0 92420000 */  lbu        $v0, 0x0($s2)
    /* 748B4 80073CB4 26520001 */  addiu      $s2, $s2, 0x1
    /* 748B8 80073CB8 02021004 */  sllv       $v0, $v0, $s0
    /* 748BC 80073CBC 26100008 */  addiu      $s0, $s0, 0x8
    /* 748C0 80073CC0 0218082A */  slt        $at, $s0, $t8
    /* 748C4 80073CC4 1420FFFA */  bnez       $at, .L80073CB0_748B0
    /* 748C8 80073CC8 0322C825 */   or        $t9, $t9, $v0
  .L80073CCC_748CC:
    /* 748CC 80073CCC 00181040 */  sll        $v0, $t8, 1
    /* 748D0 80073CD0 004B1021 */  addu       $v0, $v0, $t3
    /* 748D4 80073CD4 94490000 */  lhu        $t1, 0x0($v0)
    /* 748D8 80073CD8 8DE80004 */  lw         $t0, 0x4($t7)
    /* 748DC 80073CDC 01394824 */  and        $t1, $t1, $t9
    /* 748E0 80073CE0 000948C0 */  sll        $t1, $t1, 3
    /* 748E4 80073CE4 01097821 */  addu       $t7, $t0, $t1
    /* 748E8 80073CE8 91F80000 */  lbu        $t8, 0x0($t7)
    /* 748EC 80073CEC 2F010011 */  sltiu      $at, $t8, 0x11
    /* 748F0 80073CF0 5020FFEA */  beql       $at, $zero, .L80073C9C_7489C
    /* 748F4 80073CF4 91E80001 */   lbu       $t0, 0x1($t7)
    /* 748F8 80073CF8 91E20001 */  lbu        $v0, 0x1($t7)
  .L80073CFC_748FC:
    /* 748FC 80073CFC 02028022 */  sub        $s0, $s0, $v0 /* handwritten instruction */
    /* 74900 80073D00 0218082B */  sltu       $at, $s0, $t8
    /* 74904 80073D04 10200008 */  beqz       $at, .L80073D28_74928
    /* 74908 80073D08 0059C806 */   srlv      $t9, $t9, $v0
  .L80073D0C_7490C:
    /* 7490C 80073D0C 92420000 */  lbu        $v0, 0x0($s2)
    /* 74910 80073D10 26520001 */  addiu      $s2, $s2, 0x1
    /* 74914 80073D14 02021004 */  sllv       $v0, $v0, $s0
    /* 74918 80073D18 26100008 */  addiu      $s0, $s0, 0x8
    /* 7491C 80073D1C 0218082A */  slt        $at, $s0, $t8
    /* 74920 80073D20 1420FFFA */  bnez       $at, .L80073D0C_7490C
    /* 74924 80073D24 0322C825 */   or        $t9, $t9, $v0
  .L80073D28_74928:
    /* 74928 80073D28 00181040 */  sll        $v0, $t8, 1
    /* 7492C 80073D2C 004B1021 */  addu       $v0, $v0, $t3
    /* 74930 80073D30 94490000 */  lhu        $t1, 0x0($v0)
    /* 74934 80073D34 95E30004 */  lhu        $v1, 0x4($t7)
    /* 74938 80073D38 31C20003 */  andi       $v0, $t6, 0x3
    /* 7493C 80073D3C 01394824 */  and        $t1, $t1, $t9
    /* 74940 80073D40 02234022 */  sub        $t0, $s1, $v1 /* handwritten instruction */
    /* 74944 80073D44 01094022 */  sub        $t0, $t0, $t1 /* handwritten instruction */
    /* 74948 80073D48 0319C806 */  srlv       $t9, $t9, $t8
    /* 7494C 80073D4C 1040000A */  beqz       $v0, .L80073D78_74978
    /* 74950 80073D50 02188022 */   sub       $s0, $s0, $t8 /* handwritten instruction */
    /* 74954 80073D54 01C27022 */  sub        $t6, $t6, $v0 /* handwritten instruction */
  .L80073D58_74958:
    /* 74958 80073D58 910A0000 */  lbu        $t2, 0x0($t0)
    /* 7495C 80073D5C 2042FFFF */  addi       $v0, $v0, -0x1 /* handwritten instruction */
    /* 74960 80073D60 21080001 */  addi       $t0, $t0, 0x1 /* handwritten instruction */
    /* 74964 80073D64 22310001 */  addi       $s1, $s1, 0x1 /* handwritten instruction */
    /* 74968 80073D68 1440FFFB */  bnez       $v0, .L80073D58_74958
    /* 7496C 80073D6C A22AFFFF */   sb        $t2, -0x1($s1)
    /* 74970 80073D70 51C0FF74 */  beql       $t6, $zero, .L80073B44_74744
    /* 74974 80073D74 0206082B */   sltu      $at, $s0, $a2
  .L80073D78_74978:
    /* 74978 80073D78 91020000 */  lbu        $v0, 0x0($t0)
    /* 7497C 80073D7C 25CEFFFC */  addiu      $t6, $t6, -0x4
    /* 74980 80073D80 25080004 */  addiu      $t0, $t0, 0x4
    /* 74984 80073D84 A2220000 */  sb         $v0, 0x0($s1)
    /* 74988 80073D88 9103FFFD */  lbu        $v1, -0x3($t0)
    /* 7498C 80073D8C 26310004 */  addiu      $s1, $s1, 0x4
    /* 74990 80073D90 A223FFFD */  sb         $v1, -0x3($s1)
    /* 74994 80073D94 9109FFFE */  lbu        $t1, -0x2($t0)
    /* 74998 80073D98 A229FFFE */  sb         $t1, -0x2($s1)
    /* 7499C 80073D9C 910AFFFF */  lbu        $t2, -0x1($t0)
    /* 749A0 80073DA0 15C0FFF5 */  bnez       $t6, .L80073D78_74978
    /* 749A4 80073DA4 A22AFFFF */   sb        $t2, -0x1($s1)
    /* 749A8 80073DA8 0801CED0 */  j          .L80073B40_74740
    /* 749AC 80073DAC 00000000 */   nop
  .L80073DB0_749B0:
    /* 749B0 80073DB0 3C01800A */  lui        $at, %hi(rzip_inflate_input)
    /* 749B4 80073DB4 AC327968 */  sw         $s2, %lo(rzip_inflate_input)($at)
    /* 749B8 80073DB8 3C01800A */  lui        $at, %hi(rzip_inflate_output)
    /* 749BC 80073DBC AC31796C */  sw         $s1, %lo(rzip_inflate_output)($at)
    /* 749C0 80073DC0 3C018010 */  lui        $at, %hi(rzip_bit_buffer)
    /* 749C4 80073DC4 AC395220 */  sw         $t9, %lo(rzip_bit_buffer)($at)
    /* 749C8 80073DC8 3C018010 */  lui        $at, %hi(rzip_num_bits)
    /* 749CC 80073DCC AC305224 */  sw         $s0, %lo(rzip_num_bits)($at)
    /* 749D0 80073DD0 8FB20008 */  lw         $s2, 0x8($sp)
    /* 749D4 80073DD4 8FB10004 */  lw         $s1, 0x4($sp)
    /* 749D8 80073DD8 8FB00000 */  lw         $s0, 0x0($sp)
    /* 749DC 80073DDC 03E00008 */  jr         $ra
    /* 749E0 80073DE0 27BD0010 */   addiu     $sp, $sp, 0x10
    /* 749E4 80073DE4 00000000 */  nop
    /* 749E8 80073DE8 00000000 */  nop
    /* 749EC 80073DEC 00000000 */  nop
