.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

/* Generated by spimdisasm 1.30.2 */

.section .data

glabel gIntDisFlag
.byte 0x00

/* Not used in this file, 
   but it feels like they split this file since DKR, 
   and forgot to move this. */
glabel rngSeed
.word 0x5141564D

/* Unused in this game, but it's used in DKR */
glabel gPrevRNGSeed
.word 0x5141564D

.section .text, "ax"

/* Handwritten function */
glabel disableInterrupts
    /* 49A00 80048E00 3C08800A */  lui        $t0, %hi(gIntDisFlag)
    /* 49A04 80048E04 81083E40 */  lb         $t0, %lo(gIntDisFlag)($t0)
    /* 49A08 80048E08 11000006 */  beqz       $t0, .L80048E24_49A24
    /* 49A0C 80048E0C 40086000 */   mfc0      $t0, $12 /* handwritten instruction */
    /* 49A10 80048E10 2401FFFE */  addiu      $at, $zero, -0x2
    /* 49A14 80048E14 01014824 */  and        $t1, $t0, $at
    /* 49A18 80048E18 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 49A1C 80048E1C 31020001 */  andi       $v0, $t0, 0x1
    /* 49A20 80048E20 00000000 */  nop
  .L80048E24_49A24:
    /* 49A24 80048E24 03E00008 */  jr         $ra
    /* 49A28 80048E28 00000000 */   nop

/* Handwritten function */
glabel enableInterrupts
    /* 49A2C 80048E2C 3C08800A */  lui        $t0, %hi(gIntDisFlag)
    /* 49A30 80048E30 81083E40 */  lb         $t0, %lo(gIntDisFlag)($t0)
    /* 49A34 80048E34 11000005 */  beqz       $t0, .L80048E4C_49A4C
    /* 49A38 80048E38 40086000 */   mfc0      $t0, $12 /* handwritten instruction */
    /* 49A3C 80048E3C 01044025 */  or         $t0, $t0, $a0
    /* 49A40 80048E40 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 49A44 80048E44 00000000 */  nop
    /* 49A48 80048E48 00000000 */  nop
  .L80048E4C_49A4C:
    /* 49A4C 80048E4C 03E00008 */  jr         $ra
    /* 49A50 80048E50 00000000 */   nop

glabel setIntDisFlag
    /* 49A54 80048E54 3C01800A */  lui        $at, %hi(gIntDisFlag)
    /* 49A58 80048E58 03E00008 */  jr         $ra
    /* 49A5C 80048E5C A0243E40 */   sb        $a0, %lo(gIntDisFlag)($at)
