.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .rodata

/* Generated by spimdisasm 1.30.2 */

glabel D_800AD190_ADD90
    /* ADD90 800AD190 BF0F5C29 */ .float -0.56

glabel D_800AD194_ADD94
    /* ADD94 800AD194 3FB851EC */ .float 1.44

glabel D_800AD198_ADD98
    /* ADD98 800AD198 BFB851EC */ .float -1.44

glabel D_800AD19C_ADD9C
    /* ADD9C 800AD19C 3F0F5C29 */ .float 0.56

glabel D_800AD1A0_ADDA0
    /* ADDA0 800AD1A0 3F8F5C29 */ .float 1.12

glabel D_800AD1A4_ADDA4
    /* ADDA4 800AD1A4 C01C28F6 */ .float -2.44

glabel D_800AD1A8_ADDA8
    /* ADDA8 800AD1A8 3FF0A3D7 */ .float 1.88

glabel D_800AD1AC_ADDAC
    /* ADDAC 800AD1AC BF0F5C29 */ .float -0.56

glabel D_800AD1B0_ADDB0
    /* ADDB0 800AD1B0 BF0F5C29 */ .float -0.56

glabel D_800AD1B4_ADDB4
    /* ADDB4 800AD1B4 3F0F5C29 */ .float 0.56

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel pointListRPY
    /* 4A5B0 800499B0 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 4A5B4 800499B4 18800034 */  blez       $a0, .L80049A88_4A688
    /* 4A5B8 800499B8 FFBF0000 */   sd        $ra, 0x0($sp)
    /* 4A5BC 800499BC 0080C825 */  or         $t9, $a0, $zero
    /* 4A5C0 800499C0 44800000 */  mtc1       $zero, $f0
    /* 4A5C4 800499C4 0C0127CD */  jal        Sinf
    /* 4A5C8 800499C8 84A40000 */   lh        $a0, 0x0($a1)
    /* 4A5CC 800499CC 0C0127CC */  jal        Cosf
    /* 4A5D0 800499D0 46000106 */   mov.s     $f4, $f0
    /* 4A5D4 800499D4 46000146 */  mov.s      $f5, $f0
    /* 4A5D8 800499D8 0C0127CD */  jal        Sinf
    /* 4A5DC 800499DC 84A40002 */   lh        $a0, 0x2($a1)
    /* 4A5E0 800499E0 0C0127CC */  jal        Cosf
    /* 4A5E4 800499E4 46000186 */   mov.s     $f6, $f0
    /* 4A5E8 800499E8 460001C6 */  mov.s      $f7, $f0
    /* 4A5EC 800499EC 0C0127CD */  jal        Sinf
    /* 4A5F0 800499F0 84A40004 */   lh        $a0, 0x4($a1)
    /* 4A5F4 800499F4 0C0127CC */  jal        Cosf
    /* 4A5F8 800499F8 46000206 */   mov.s     $f8, $f0
    /* 4A5FC 800499FC 46000246 */  mov.s      $f9, $f0
  .L80049A00_4A600:
    /* 4A600 80049A00 C4CA0000 */  lwc1       $f10, 0x0($a2)
    /* 4A604 80049A04 C4CB0004 */  lwc1       $f11, 0x4($a2)
    /* 4A608 80049A08 C4CC0008 */  lwc1       $f12, 0x8($a2)
    /* 4A60C 80049A0C 46095382 */  mul.s      $f14, $f10, $f9
    /* 4A610 80049A10 2739FFFF */  addiu      $t9, $t9, -0x1
    /* 4A614 80049A14 24C6000C */  addiu      $a2, $a2, 0xC
    /* 4A618 80049A18 46085BC2 */  mul.s      $f15, $f11, $f8
    /* 4A61C 80049A1C 24E7000C */  addiu      $a3, $a3, 0xC
    /* 4A620 80049A20 46095C02 */  mul.s      $f16, $f11, $f9
    /* 4A624 80049A24 00000000 */  nop
    /* 4A628 80049A28 46085442 */  mul.s      $f17, $f10, $f8
    /* 4A62C 80049A2C 460F7281 */  sub.s      $f10, $f14, $f15
    /* 4A630 80049A30 461182C0 */  add.s      $f11, $f16, $f17
    /* 4A634 80049A34 46075B82 */  mul.s      $f14, $f11, $f7
    /* 4A638 80049A38 00000000 */  nop
    /* 4A63C 80049A3C 460663C2 */  mul.s      $f15, $f12, $f6
    /* 4A640 80049A40 00000000 */  nop
    /* 4A644 80049A44 46076402 */  mul.s      $f16, $f12, $f7
    /* 4A648 80049A48 00000000 */  nop
    /* 4A64C 80049A4C 46065C42 */  mul.s      $f17, $f11, $f6
    /* 4A650 80049A50 460F72C1 */  sub.s      $f11, $f14, $f15
    /* 4A654 80049A54 46055382 */  mul.s      $f14, $f10, $f5
    /* 4A658 80049A58 46118300 */  add.s      $f12, $f16, $f17
    /* 4A65C 80049A5C 460463C2 */  mul.s      $f15, $f12, $f4
    /* 4A660 80049A60 00000000 */  nop
    /* 4A664 80049A64 46056402 */  mul.s      $f16, $f12, $f5
    /* 4A668 80049A68 00000000 */  nop
    /* 4A66C 80049A6C 46045442 */  mul.s      $f17, $f10, $f4
    /* 4A670 80049A70 460F7280 */  add.s      $f10, $f14, $f15
    /* 4A674 80049A74 E4EAFFF4 */  swc1       $f10, -0xC($a3)
    /* 4A678 80049A78 46118301 */  sub.s      $f12, $f16, $f17
    /* 4A67C 80049A7C E4EBFFF8 */  swc1       $f11, -0x8($a3)
    /* 4A680 80049A80 1720FFDF */  bnez       $t9, .L80049A00_4A600
    /* 4A684 80049A84 E4ECFFFC */   swc1      $f12, -0x4($a3)
  .L80049A88_4A688:
    /* 4A688 80049A88 DFBF0000 */  ld         $ra, 0x0($sp)
    /* 4A68C 80049A8C 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 4A690 80049A90 03E00008 */  jr         $ra
    /* 4A694 80049A94 00000000 */   nop

glabel splinePos
    /* 4A698 80049A98 C7AA0010 */  lwc1       $f10, 0x10($sp)
    /* 4A69C 80049A9C 3C01800B */  lui        $at, %hi(D_800AD190_ADD90)
    /* 4A6A0 80049AA0 C420D190 */  lwc1       $f0, %lo(D_800AD190_ADD90)($at)
    /* 4A6A4 80049AA4 460A52C2 */  mul.s      $f11, $f10, $f10
    /* 4A6A8 80049AA8 3C01800B */  lui        $at, %hi(D_800AD194_ADD94)
    /* 4A6AC 80049AAC C421D194 */  lwc1       $f1, %lo(D_800AD194_ADD94)($at)
    /* 4A6B0 80049AB0 3C01800B */  lui        $at, %hi(D_800AD198_ADD98)
    /* 4A6B4 80049AB4 C422D198 */  lwc1       $f2, %lo(D_800AD198_ADD98)($at)
    /* 4A6B8 80049AB8 44868000 */  mtc1       $a2, $f16
    /* 4A6BC 80049ABC 3C01800B */  lui        $at, %hi(D_800AD19C_ADD9C)
    /* 4A6C0 80049AC0 460C0002 */  mul.s      $f0, $f0, $f12
    /* 4A6C4 80049AC4 C423D19C */  lwc1       $f3, %lo(D_800AD19C_ADD9C)($at)
    /* 4A6C8 80049AC8 44879000 */  mtc1       $a3, $f18
    /* 4A6CC 80049ACC 3C01800B */  lui        $at, %hi(D_800AD1A0_ADDA0)
    /* 4A6D0 80049AD0 C424D1A0 */  lwc1       $f4, %lo(D_800AD1A0_ADDA0)($at)
    /* 4A6D4 80049AD4 3C01800B */  lui        $at, %hi(D_800AD1A4_ADDA4)
    /* 4A6D8 80049AD8 C425D1A4 */  lwc1       $f5, %lo(D_800AD1A4_ADDA4)($at)
    /* 4A6DC 80049ADC 460E0842 */  mul.s      $f1, $f1, $f14
    /* 4A6E0 80049AE0 3C01800B */  lui        $at, %hi(D_800AD1A8_ADDA8)
    /* 4A6E4 80049AE4 C426D1A8 */  lwc1       $f6, %lo(D_800AD1A8_ADDA8)($at)
    /* 4A6E8 80049AE8 3C01800B */  lui        $at, %hi(D_800AD1AC_ADDAC)
    /* 4A6EC 80049AEC C427D1AC */  lwc1       $f7, %lo(D_800AD1AC_ADDAC)($at)
    /* 4A6F0 80049AF0 3C01800B */  lui        $at, %hi(D_800AD1B0_ADDB0)
    /* 4A6F4 80049AF4 C428D1B0 */  lwc1       $f8, %lo(D_800AD1B0_ADDB0)($at)
    /* 4A6F8 80049AF8 46101082 */  mul.s      $f2, $f2, $f16
    /* 4A6FC 80049AFC 3C01800B */  lui        $at, %hi(D_800AD1B4_ADDB4)
    /* 4A700 80049B00 C429D1B4 */  lwc1       $f9, %lo(D_800AD1B4_ADDB4)($at)
    /* 4A704 80049B04 46010000 */  add.s      $f0, $f0, $f1
    /* 4A708 80049B08 461218C2 */  mul.s      $f3, $f3, $f18
    /* 4A70C 80049B0C 00000000 */  nop
    /* 4A710 80049B10 460C2102 */  mul.s      $f4, $f4, $f12
    /* 4A714 80049B14 46031080 */  add.s      $f2, $f2, $f3
    /* 4A718 80049B18 46020000 */  add.s      $f0, $f0, $f2
    /* 4A71C 80049B1C 460E2942 */  mul.s      $f5, $f5, $f14
    /* 4A720 80049B20 00000000 */  nop
    /* 4A724 80049B24 46103182 */  mul.s      $f6, $f6, $f16
    /* 4A728 80049B28 46052100 */  add.s      $f4, $f4, $f5
    /* 4A72C 80049B2C 461239C2 */  mul.s      $f7, $f7, $f18
    /* 4A730 80049B30 00000000 */  nop
    /* 4A734 80049B34 460B53C2 */  mul.s      $f15, $f10, $f11
    /* 4A738 80049B38 00000000 */  nop
    /* 4A73C 80049B3C 460C4202 */  mul.s      $f8, $f8, $f12
    /* 4A740 80049B40 46073180 */  add.s      $f6, $f6, $f7
    /* 4A744 80049B44 46062100 */  add.s      $f4, $f4, $f6
    /* 4A748 80049B48 46104A42 */  mul.s      $f9, $f9, $f16
    /* 4A74C 80049B4C 46094200 */  add.s      $f8, $f8, $f9
    /* 4A750 80049B50 460A4202 */  mul.s      $f8, $f8, $f10
    /* 4A754 80049B54 00000000 */  nop
    /* 4A758 80049B58 46007BC2 */  mul.s      $f15, $f15, $f0
    /* 4A75C 80049B5C 00000000 */  nop
    /* 4A760 80049B60 46045AC2 */  mul.s      $f11, $f11, $f4
    /* 4A764 80049B64 46087380 */  add.s      $f14, $f14, $f8
    /* 4A768 80049B68 460B7BC0 */  add.s      $f15, $f15, $f11
    /* 4A76C 80049B6C 03E00008 */  jr         $ra
    /* 4A770 80049B70 460F7000 */   add.s     $f0, $f14, $f15

glabel matrixScale
    /* 4A774 80049B74 C4E00000 */  lwc1       $f0, 0x0($a3)
    /* 4A778 80049B78 C4E10004 */  lwc1       $f1, 0x4($a3)
    /* 4A77C 80049B7C C4E20008 */  lwc1       $f2, 0x8($a3)
    /* 4A780 80049B80 460C0002 */  mul.s      $f0, $f0, $f12
    /* 4A784 80049B84 C4E30010 */  lwc1       $f3, 0x10($a3)
    /* 4A788 80049B88 C4E40014 */  lwc1       $f4, 0x14($a3)
    /* 4A78C 80049B8C C4E50018 */  lwc1       $f5, 0x18($a3)
    /* 4A790 80049B90 C4E60020 */  lwc1       $f6, 0x20($a3)
    /* 4A794 80049B94 44865000 */  mtc1       $a2, $f10
    /* 4A798 80049B98 C4E70024 */  lwc1       $f7, 0x24($a3)
    /* 4A79C 80049B9C 460C0842 */  mul.s      $f1, $f1, $f12
    /* 4A7A0 80049BA0 C4E80028 */  lwc1       $f8, 0x28($a3)
    /* 4A7A4 80049BA4 E4E00000 */  swc1       $f0, 0x0($a3)
    /* 4A7A8 80049BA8 460C1082 */  mul.s      $f2, $f2, $f12
    /* 4A7AC 80049BAC E4E10004 */  swc1       $f1, 0x4($a3)
    /* 4A7B0 80049BB0 460E18C2 */  mul.s      $f3, $f3, $f14
    /* 4A7B4 80049BB4 E4E20008 */  swc1       $f2, 0x8($a3)
    /* 4A7B8 80049BB8 460E2102 */  mul.s      $f4, $f4, $f14
    /* 4A7BC 80049BBC E4E30010 */  swc1       $f3, 0x10($a3)
    /* 4A7C0 80049BC0 460E2942 */  mul.s      $f5, $f5, $f14
    /* 4A7C4 80049BC4 E4E40014 */  swc1       $f4, 0x14($a3)
    /* 4A7C8 80049BC8 460A3182 */  mul.s      $f6, $f6, $f10
    /* 4A7CC 80049BCC E4E50018 */  swc1       $f5, 0x18($a3)
    /* 4A7D0 80049BD0 460A39C2 */  mul.s      $f7, $f7, $f10
    /* 4A7D4 80049BD4 E4E60020 */  swc1       $f6, 0x20($a3)
    /* 4A7D8 80049BD8 460A4202 */  mul.s      $f8, $f8, $f10
    /* 4A7DC 80049BDC E4E70024 */  swc1       $f7, 0x24($a3)
    /* 4A7E0 80049BE0 03E00008 */  jr         $ra
    /* 4A7E4 80049BE4 E4E80028 */   swc1      $f8, 0x28($a3)

glabel matrixTranslate
    /* 4A7E8 80049BE8 C4E00000 */  lwc1       $f0, 0x0($a3)
    /* 4A7EC 80049BEC C4E10004 */  lwc1       $f1, 0x4($a3)
    /* 4A7F0 80049BF0 C4E30010 */  lwc1       $f3, 0x10($a3)
    /* 4A7F4 80049BF4 460C0002 */  mul.s      $f0, $f0, $f12
    /* 4A7F8 80049BF8 C4E40014 */  lwc1       $f4, 0x14($a3)
    /* 4A7FC 80049BFC C4E60020 */  lwc1       $f6, 0x20($a3)
    /* 4A800 80049C00 460C18C2 */  mul.s      $f3, $f3, $f12
    /* 4A804 80049C04 C4E70024 */  lwc1       $f7, 0x24($a3)
    /* 4A808 80049C08 C4E20008 */  lwc1       $f2, 0x8($a3)
    /* 4A80C 80049C0C 460C3182 */  mul.s      $f6, $f6, $f12
    /* 4A810 80049C10 C4E50018 */  lwc1       $f5, 0x18($a3)
    /* 4A814 80049C14 C4E80028 */  lwc1       $f8, 0x28($a3)
    /* 4A818 80049C18 460E0842 */  mul.s      $f1, $f1, $f14
    /* 4A81C 80049C1C 44866800 */  mtc1       $a2, $f13
    /* 4A820 80049C20 C4E90030 */  lwc1       $f9, 0x30($a3)
    /* 4A824 80049C24 460E2102 */  mul.s      $f4, $f4, $f14
    /* 4A828 80049C28 C4EA0034 */  lwc1       $f10, 0x34($a3)
    /* 4A82C 80049C2C C4EB0038 */  lwc1       $f11, 0x38($a3)
    /* 4A830 80049C30 460E39C2 */  mul.s      $f7, $f7, $f14
    /* 4A834 80049C34 00000000 */  nop
    /* 4A838 80049C38 460D1082 */  mul.s      $f2, $f2, $f13
    /* 4A83C 80049C3C 46030000 */  add.s      $f0, $f0, $f3
    /* 4A840 80049C40 460D2942 */  mul.s      $f5, $f5, $f13
    /* 4A844 80049C44 46060000 */  add.s      $f0, $f0, $f6
    /* 4A848 80049C48 460D4202 */  mul.s      $f8, $f8, $f13
    /* 4A84C 80049C4C 46090000 */  add.s      $f0, $f0, $f9
    /* 4A850 80049C50 46040840 */  add.s      $f1, $f1, $f4
    /* 4A854 80049C54 E4E00030 */  swc1       $f0, 0x30($a3)
    /* 4A858 80049C58 46070840 */  add.s      $f1, $f1, $f7
    /* 4A85C 80049C5C 460A0840 */  add.s      $f1, $f1, $f10
    /* 4A860 80049C60 46051080 */  add.s      $f2, $f2, $f5
    /* 4A864 80049C64 E4E10034 */  swc1       $f1, 0x34($a3)
    /* 4A868 80049C68 46081080 */  add.s      $f2, $f2, $f8
    /* 4A86C 80049C6C 460B1080 */  add.s      $f2, $f2, $f11
    /* 4A870 80049C70 03E00008 */  jr         $ra
    /* 4A874 80049C74 E4E20038 */   swc1      $f2, 0x38($a3)

glabel matrixRoll
    /* 4A878 80049C78 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 4A87C 80049C7C FFBF0000 */  sd         $ra, 0x0($sp)
    /* 4A880 80049C80 0C0127CD */  jal        Sinf
    /* 4A884 80049C84 00000000 */   nop
    /* 4A888 80049C88 0C0127CC */  jal        Cosf
    /* 4A88C 80049C8C 46000046 */   mov.s     $f1, $f0
    /* 4A890 80049C90 C4A20000 */  lwc1       $f2, 0x0($a1)
    /* 4A894 80049C94 C4A50010 */  lwc1       $f5, 0x10($a1)
    /* 4A898 80049C98 C4A30004 */  lwc1       $f3, 0x4($a1)
    /* 4A89C 80049C9C 46001202 */  mul.s      $f8, $f2, $f0
    /* 4A8A0 80049CA0 C4A60014 */  lwc1       $f6, 0x14($a1)
    /* 4A8A4 80049CA4 C4A40008 */  lwc1       $f4, 0x8($a1)
    /* 4A8A8 80049CA8 46012A42 */  mul.s      $f9, $f5, $f1
    /* 4A8AC 80049CAC C4A70018 */  lwc1       $f7, 0x18($a1)
    /* 4A8B0 80049CB0 46001A82 */  mul.s      $f10, $f3, $f0
    /* 4A8B4 80049CB4 00000000 */  nop
    /* 4A8B8 80049CB8 460132C2 */  mul.s      $f11, $f6, $f1
    /* 4A8BC 80049CBC 00000000 */  nop
    /* 4A8C0 80049CC0 46002302 */  mul.s      $f12, $f4, $f0
    /* 4A8C4 80049CC4 00000000 */  nop
    /* 4A8C8 80049CC8 46013B42 */  mul.s      $f13, $f7, $f1
    /* 4A8CC 80049CCC 460B5280 */  add.s      $f10, $f10, $f11
    /* 4A8D0 80049CD0 46002942 */  mul.s      $f5, $f5, $f0
    /* 4A8D4 80049CD4 00000000 */  nop
    /* 4A8D8 80049CD8 46011082 */  mul.s      $f2, $f2, $f1
    /* 4A8DC 80049CDC E4AA0004 */  swc1       $f10, 0x4($a1)
    /* 4A8E0 80049CE0 460D6300 */  add.s      $f12, $f12, $f13
    /* 4A8E4 80049CE4 46003182 */  mul.s      $f6, $f6, $f0
    /* 4A8E8 80049CE8 E4AC0008 */  swc1       $f12, 0x8($a1)
    /* 4A8EC 80049CEC 460118C2 */  mul.s      $f3, $f3, $f1
    /* 4A8F0 80049CF0 00000000 */  nop
    /* 4A8F4 80049CF4 460039C2 */  mul.s      $f7, $f7, $f0
    /* 4A8F8 80049CF8 00000000 */  nop
    /* 4A8FC 80049CFC 46012102 */  mul.s      $f4, $f4, $f1
    /* 4A900 80049D00 46094200 */  add.s      $f8, $f8, $f9
    /* 4A904 80049D04 46022941 */  sub.s      $f5, $f5, $f2
    /* 4A908 80049D08 46033181 */  sub.s      $f6, $f6, $f3
    /* 4A90C 80049D0C E4A50010 */  swc1       $f5, 0x10($a1)
    /* 4A910 80049D10 460439C1 */  sub.s      $f7, $f7, $f4
    /* 4A914 80049D14 E4A60014 */  swc1       $f6, 0x14($a1)
    /* 4A918 80049D18 E4A80000 */  swc1       $f8, 0x0($a1)
    /* 4A91C 80049D1C E4A70018 */  swc1       $f7, 0x18($a1)
    /* 4A920 80049D20 DFBF0000 */  ld         $ra, 0x0($sp)
    /* 4A924 80049D24 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 4A928 80049D28 03E00008 */  jr         $ra
    /* 4A92C 80049D2C 00000000 */   nop

glabel matrixPitch
    /* 4A930 80049D30 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 4A934 80049D34 FFBF0000 */  sd         $ra, 0x0($sp)
    /* 4A938 80049D38 0C0127CD */  jal        Sinf
    /* 4A93C 80049D3C 00000000 */   nop
    /* 4A940 80049D40 0C0127CC */  jal        Cosf
    /* 4A944 80049D44 46000046 */   mov.s     $f1, $f0
    /* 4A948 80049D48 C4A20010 */  lwc1       $f2, 0x10($a1)
    /* 4A94C 80049D4C C4A50020 */  lwc1       $f5, 0x20($a1)
    /* 4A950 80049D50 C4A30014 */  lwc1       $f3, 0x14($a1)
    /* 4A954 80049D54 46001202 */  mul.s      $f8, $f2, $f0
    /* 4A958 80049D58 C4A60024 */  lwc1       $f6, 0x24($a1)
    /* 4A95C 80049D5C C4A40018 */  lwc1       $f4, 0x18($a1)
    /* 4A960 80049D60 46012A42 */  mul.s      $f9, $f5, $f1
    /* 4A964 80049D64 C4A70028 */  lwc1       $f7, 0x28($a1)
    /* 4A968 80049D68 46001A82 */  mul.s      $f10, $f3, $f0
    /* 4A96C 80049D6C 00000000 */  nop
    /* 4A970 80049D70 460132C2 */  mul.s      $f11, $f6, $f1
    /* 4A974 80049D74 00000000 */  nop
    /* 4A978 80049D78 46002302 */  mul.s      $f12, $f4, $f0
    /* 4A97C 80049D7C 00000000 */  nop
    /* 4A980 80049D80 46013B42 */  mul.s      $f13, $f7, $f1
    /* 4A984 80049D84 460B5280 */  add.s      $f10, $f10, $f11
    /* 4A988 80049D88 46002942 */  mul.s      $f5, $f5, $f0
    /* 4A98C 80049D8C 00000000 */  nop
    /* 4A990 80049D90 46011082 */  mul.s      $f2, $f2, $f1
    /* 4A994 80049D94 E4AA0014 */  swc1       $f10, 0x14($a1)
    /* 4A998 80049D98 460D6300 */  add.s      $f12, $f12, $f13
    /* 4A99C 80049D9C 46003182 */  mul.s      $f6, $f6, $f0
    /* 4A9A0 80049DA0 E4AC0018 */  swc1       $f12, 0x18($a1)
    /* 4A9A4 80049DA4 460118C2 */  mul.s      $f3, $f3, $f1
    /* 4A9A8 80049DA8 00000000 */  nop
    /* 4A9AC 80049DAC 460039C2 */  mul.s      $f7, $f7, $f0
    /* 4A9B0 80049DB0 00000000 */  nop
    /* 4A9B4 80049DB4 46012102 */  mul.s      $f4, $f4, $f1
    /* 4A9B8 80049DB8 46094200 */  add.s      $f8, $f8, $f9
    /* 4A9BC 80049DBC 46022941 */  sub.s      $f5, $f5, $f2
    /* 4A9C0 80049DC0 46033181 */  sub.s      $f6, $f6, $f3
    /* 4A9C4 80049DC4 E4A50020 */  swc1       $f5, 0x20($a1)
    /* 4A9C8 80049DC8 460439C1 */  sub.s      $f7, $f7, $f4
    /* 4A9CC 80049DCC E4A60024 */  swc1       $f6, 0x24($a1)
    /* 4A9D0 80049DD0 E4A80010 */  swc1       $f8, 0x10($a1)
    /* 4A9D4 80049DD4 E4A70028 */  swc1       $f7, 0x28($a1)
    /* 4A9D8 80049DD8 DFBF0000 */  ld         $ra, 0x0($sp)
    /* 4A9DC 80049DDC 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 4A9E0 80049DE0 03E00008 */  jr         $ra
    /* 4A9E4 80049DE4 00000000 */   nop

glabel matrixYaw
    /* 4A9E8 80049DE8 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 4A9EC 80049DEC FFBF0000 */  sd         $ra, 0x0($sp)
    /* 4A9F0 80049DF0 0C0127CD */  jal        Sinf
    /* 4A9F4 80049DF4 00000000 */   nop
    /* 4A9F8 80049DF8 0C0127CC */  jal        Cosf
    /* 4A9FC 80049DFC 46000046 */   mov.s     $f1, $f0
    /* 4AA00 80049E00 C4A20000 */  lwc1       $f2, 0x0($a1)
    /* 4AA04 80049E04 C4A50020 */  lwc1       $f5, 0x20($a1)
    /* 4AA08 80049E08 C4A30004 */  lwc1       $f3, 0x4($a1)
    /* 4AA0C 80049E0C 46001202 */  mul.s      $f8, $f2, $f0
    /* 4AA10 80049E10 C4A60024 */  lwc1       $f6, 0x24($a1)
    /* 4AA14 80049E14 C4A40008 */  lwc1       $f4, 0x8($a1)
    /* 4AA18 80049E18 46012A42 */  mul.s      $f9, $f5, $f1
    /* 4AA1C 80049E1C C4A70028 */  lwc1       $f7, 0x28($a1)
    /* 4AA20 80049E20 46001A82 */  mul.s      $f10, $f3, $f0
    /* 4AA24 80049E24 00000000 */  nop
    /* 4AA28 80049E28 460132C2 */  mul.s      $f11, $f6, $f1
    /* 4AA2C 80049E2C 00000000 */  nop
    /* 4AA30 80049E30 46002302 */  mul.s      $f12, $f4, $f0
    /* 4AA34 80049E34 00000000 */  nop
    /* 4AA38 80049E38 46013B42 */  mul.s      $f13, $f7, $f1
    /* 4AA3C 80049E3C 460B5281 */  sub.s      $f10, $f10, $f11
    /* 4AA40 80049E40 46002942 */  mul.s      $f5, $f5, $f0
    /* 4AA44 80049E44 00000000 */  nop
    /* 4AA48 80049E48 46011082 */  mul.s      $f2, $f2, $f1
    /* 4AA4C 80049E4C E4AA0004 */  swc1       $f10, 0x4($a1)
    /* 4AA50 80049E50 460D6301 */  sub.s      $f12, $f12, $f13
    /* 4AA54 80049E54 46003182 */  mul.s      $f6, $f6, $f0
    /* 4AA58 80049E58 E4AC0008 */  swc1       $f12, 0x8($a1)
    /* 4AA5C 80049E5C 460118C2 */  mul.s      $f3, $f3, $f1
    /* 4AA60 80049E60 00000000 */  nop
    /* 4AA64 80049E64 460039C2 */  mul.s      $f7, $f7, $f0
    /* 4AA68 80049E68 00000000 */  nop
    /* 4AA6C 80049E6C 46012102 */  mul.s      $f4, $f4, $f1
    /* 4AA70 80049E70 46094201 */  sub.s      $f8, $f8, $f9
    /* 4AA74 80049E74 46022940 */  add.s      $f5, $f5, $f2
    /* 4AA78 80049E78 46033180 */  add.s      $f6, $f6, $f3
    /* 4AA7C 80049E7C E4A50020 */  swc1       $f5, 0x20($a1)
    /* 4AA80 80049E80 460439C0 */  add.s      $f7, $f7, $f4
    /* 4AA84 80049E84 E4A60024 */  swc1       $f6, 0x24($a1)
    /* 4AA88 80049E88 E4A80000 */  swc1       $f8, 0x0($a1)
    /* 4AA8C 80049E8C E4A70028 */  swc1       $f7, 0x28($a1)
    /* 4AA90 80049E90 DFBF0000 */  ld         $ra, 0x0($sp)
    /* 4AA94 80049E94 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 4AA98 80049E98 03E00008 */  jr         $ra
    /* 4AA9C 80049E9C 00000000 */   nop

glabel matrixID
    /* 4AAA0 80049EA0 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 4AAA4 80049EA4 44810000 */  mtc1       $at, $f0
    /* 4AAA8 80049EA8 AC800004 */  sw         $zero, 0x4($a0)
    /* 4AAAC 80049EAC AC800008 */  sw         $zero, 0x8($a0)
    /* 4AAB0 80049EB0 AC80000C */  sw         $zero, 0xC($a0)
    /* 4AAB4 80049EB4 AC800010 */  sw         $zero, 0x10($a0)
    /* 4AAB8 80049EB8 AC800018 */  sw         $zero, 0x18($a0)
    /* 4AABC 80049EBC AC80001C */  sw         $zero, 0x1C($a0)
    /* 4AAC0 80049EC0 AC800020 */  sw         $zero, 0x20($a0)
    /* 4AAC4 80049EC4 AC800024 */  sw         $zero, 0x24($a0)
    /* 4AAC8 80049EC8 AC80002C */  sw         $zero, 0x2C($a0)
    /* 4AACC 80049ECC AC800030 */  sw         $zero, 0x30($a0)
    /* 4AAD0 80049ED0 AC800034 */  sw         $zero, 0x34($a0)
    /* 4AAD4 80049ED4 AC800038 */  sw         $zero, 0x38($a0)
    /* 4AAD8 80049ED8 E4800000 */  swc1       $f0, 0x0($a0)
    /* 4AADC 80049EDC E4800014 */  swc1       $f0, 0x14($a0)
    /* 4AAE0 80049EE0 E4800028 */  swc1       $f0, 0x28($a0)
    /* 4AAE4 80049EE4 03E00008 */  jr         $ra
    /* 4AAE8 80049EE8 E480003C */   swc1      $f0, 0x3C($a0)

glabel Powerf
    /* 4AAEC 80049EEC 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 4AAF0 80049EF0 44810000 */  mtc1       $at, $f0
    /* 4AAF4 80049EF4 10A0000C */  beqz       $a1, .L80049F28_4AB28
    /* 4AAF8 80049EF8 00000000 */   nop
    /* 4AAFC 80049EFC 58A00008 */  blezl      $a1, .L80049F20_4AB20
    /* 4AB00 80049F00 24A50001 */   addiu     $a1, $a1, 0x1
    /* 4AB04 80049F04 24A5FFFF */  addiu      $a1, $a1, -0x1
  .L80049F08_4AB08:
    /* 4AB08 80049F08 460C0002 */  mul.s      $f0, $f0, $f12
    /* 4AB0C 80049F0C 54A0FFFE */  bnel       $a1, $zero, .L80049F08_4AB08
    /* 4AB10 80049F10 24A5FFFF */   addiu     $a1, $a1, -0x1
    /* 4AB14 80049F14 03E00008 */  jr         $ra
    /* 4AB18 80049F18 00000000 */   nop
  .L80049F1C_4AB1C:
    /* 4AB1C 80049F1C 24A50001 */  addiu      $a1, $a1, 0x1
  .L80049F20_4AB20:
    /* 4AB20 80049F20 14A0FFFE */  bnez       $a1, .L80049F1C_4AB1C
    /* 4AB24 80049F24 460C0003 */   div.s     $f0, $f0, $f12
  .L80049F28_4AB28:
    /* 4AB28 80049F28 03E00008 */  jr         $ra
    /* 4AB2C 80049F2C 00000000 */   nop

/* Handwritten function */
glabel Cosf
    /* 4AB30 80049F30 24844000 */  addiu      $a0, $a0, 0x4000
  glabel Sinf
    /* 4AB34 80049F34 3C0A800B */  lui        $t2, %hi(D_800A8754_A9354)
    /* 4AB38 80049F38 00044102 */  srl        $t0, $a0, 4
    /* 4AB3C 80049F3C 30894000 */  andi       $t1, $a0, 0x4000
    /* 4AB40 80049F40 254A8754 */  addiu      $t2, $t2, %lo(D_800A8754_A9354)
    /* 4AB44 80049F44 11200007 */  beqz       $t1, .L80049F64_4AB64
    /* 4AB48 80049F48 310803FF */   andi      $t0, $t0, 0x3FF
    /* 4AB4C 80049F4C 3089000F */  andi       $t1, $a0, 0xF
    /* 4AB50 80049F50 51200003 */  beql       $t1, $zero, .L80049F60_4AB60
    /* 4AB54 80049F54 34090400 */   ori       $t1, $zero, 0x400
    /* 4AB58 80049F58 25080001 */  addiu      $t0, $t0, 0x1
    /* 4AB5C 80049F5C 34090400 */  ori        $t1, $zero, 0x400
  .L80049F60_4AB60:
    /* 4AB60 80049F60 01284022 */  sub        $t0, $t1, $t0 /* handwritten instruction */
  .L80049F64_4AB64:
    /* 4AB64 80049F64 00084080 */  sll        $t0, $t0, 2
    /* 4AB68 80049F68 01485021 */  addu       $t2, $t2, $t0
    /* 4AB6C 80049F6C 30898000 */  andi       $t1, $a0, 0x8000
    /* 4AB70 80049F70 11200002 */  beqz       $t1, .L80049F7C_4AB7C
    /* 4AB74 80049F74 C5400000 */   lwc1      $f0, 0x0($t2)
    /* 4AB78 80049F78 46000007 */  neg.s      $f0, $f0
  .L80049F7C_4AB7C:
    /* 4AB7C 80049F7C 03E00008 */  jr         $ra
    /* 4AB80 80049F80 00000000 */   nop

/* Handwritten function */
glabel Arctanf
    /* 4AB84 80049F84 44800000 */  mtc1       $zero, $f0
    /* 4AB88 80049F88 24020000 */  addiu      $v0, $zero, 0x0
    /* 4AB8C 80049F8C 46006032 */  c.eq.s     $f12, $f0
    /* 4AB90 80049F90 45020005 */  bc1fl      .L80049FA8_4ABA8
    /* 4AB94 80049F94 4600603C */   c.lt.s    $f12, $f0
    /* 4AB98 80049F98 46007032 */  c.eq.s     $f14, $f0
    /* 4AB9C 80049F9C 45010036 */  bc1t       .L8004A078_4AC78
    /* 4ABA0 80049FA0 00000000 */   nop
    /* 4ABA4 80049FA4 4600603C */  c.lt.s     $f12, $f0
  .L80049FA8_4ABA8:
    /* 4ABA8 80049FA8 45030008 */  bc1tl      .L80049FCC_4ABCC
    /* 4ABAC 80049FAC 4600703C */   c.lt.s    $f14, $f0
    /* 4ABB0 80049FB0 4600703C */  c.lt.s     $f14, $f0
    /* 4ABB4 80049FB4 45020010 */  bc1fl      .L80049FF8_4ABF8
    /* 4ABB8 80049FB8 460E603C */   c.lt.s    $f12, $f14
    /* 4ABBC 80049FBC 46007387 */  neg.s      $f14, $f14
    /* 4ABC0 80049FC0 080127F7 */  j          .L80049FDC_4ABDC
    /* 4ABC4 80049FC4 24024000 */   addiu     $v0, $zero, 0x4000
    /* 4ABC8 80049FC8 4600703C */  c.lt.s     $f14, $f0
  .L80049FCC_4ABCC:
    /* 4ABCC 80049FCC 46006307 */  neg.s      $f12, $f12
    /* 4ABD0 80049FD0 45030007 */  bc1tl      .L80049FF0_4ABF0
    /* 4ABD4 80049FD4 46007387 */   neg.s     $f14, $f14
    /* 4ABD8 80049FD8 3402C000 */  ori        $v0, $zero, 0xC000
  .L80049FDC_4ABDC:
    /* 4ABDC 80049FDC 46006346 */  mov.s      $f13, $f12
    /* 4ABE0 80049FE0 46007306 */  mov.s      $f12, $f14
    /* 4ABE4 80049FE4 10000003 */  b          .L80049FF4_4ABF4
    /* 4ABE8 80049FE8 46006B86 */   mov.s     $f14, $f13
    /* 4ABEC 80049FEC 46007387 */  neg.s      $f14, $f14
  .L80049FF0_4ABF0:
    /* 4ABF0 80049FF0 34028000 */  ori        $v0, $zero, 0x8000
  .L80049FF4_4ABF4:
    /* 4ABF4 80049FF4 460E603C */  c.lt.s     $f12, $f14
  .L80049FF8_4ABF8:
    /* 4ABF8 80049FF8 45020011 */  bc1fl      .L8004A040_4AC40
    /* 4ABFC 80049FFC 460C7283 */   div.s     $f10, $f14, $f12
    /* 4AC00 8004A000 460E6283 */  div.s      $f10, $f12, $f14
    /* 4AC04 8004A004 3C014500 */  lui        $at, (0x45000000 >> 16)
    /* 4AC08 8004A008 44810800 */  mtc1       $at, $f1
    /* 4AC0C 8004A00C 3C08800B */  lui        $t0, %hi(gArcTanTable)
    /* 4AC10 8004A010 25089758 */  addiu      $t0, $t0, %lo(gArcTanTable)
    /* 4AC14 8004A014 46015282 */  mul.s      $f10, $f10, $f1
    /* 4AC18 8004A018 460052A4 */  cvt.w.s    $f10, $f10
    /* 4AC1C 8004A01C 44095000 */  mfc1       $t1, $f10
    /* 4AC20 8004A020 00000000 */  nop
    /* 4AC24 8004A024 31290FFE */  andi       $t1, $t1, 0xFFE
    /* 4AC28 8004A028 01094020 */  add        $t0, $t0, $t1 /* handwritten instruction */
    /* 4AC2C 8004A02C 85080000 */  lh         $t0, 0x0($t0)
    /* 4AC30 8004A030 00481021 */  addu       $v0, $v0, $t0
    /* 4AC34 8004A034 03E00008 */  jr         $ra
    /* 4AC38 8004A038 3042FFFF */   andi      $v0, $v0, 0xFFFF
    /* 4AC3C 8004A03C 460C7283 */  div.s      $f10, $f14, $f12
  .L8004A040_4AC40:
    /* 4AC40 8004A040 3C014500 */  lui        $at, (0x45000000 >> 16)
    /* 4AC44 8004A044 44810800 */  mtc1       $at, $f1
    /* 4AC48 8004A048 3C08800B */  lui        $t0, %hi(gArcTanTable)
    /* 4AC4C 8004A04C 25089758 */  addiu      $t0, $t0, %lo(gArcTanTable)
    /* 4AC50 8004A050 24424000 */  addiu      $v0, $v0, 0x4000
    /* 4AC54 8004A054 46015282 */  mul.s      $f10, $f10, $f1
    /* 4AC58 8004A058 460052A4 */  cvt.w.s    $f10, $f10
    /* 4AC5C 8004A05C 44095000 */  mfc1       $t1, $f10
    /* 4AC60 8004A060 00000000 */  nop
    /* 4AC64 8004A064 31290FFE */  andi       $t1, $t1, 0xFFE
    /* 4AC68 8004A068 01094020 */  add        $t0, $t0, $t1 /* handwritten instruction */
    /* 4AC6C 8004A06C 85080000 */  lh         $t0, 0x0($t0)
    /* 4AC70 8004A070 00481023 */  subu       $v0, $v0, $t0
    /* 4AC74 8004A074 3042FFFF */  andi       $v0, $v0, 0xFFFF
  .L8004A078_4AC78:
    /* 4AC78 8004A078 03E00008 */  jr         $ra
    /* 4AC7C 8004A07C 00000000 */   nop

/* Handwritten function */
glabel mathDiffAngle
    /* 4AC80 8004A080 00A41022 */  sub        $v0, $a1, $a0 /* handwritten instruction */
    /* 4AC84 8004A084 34018000 */  ori        $at, $zero, 0x8000
    /* 4AC88 8004A088 0041082A */  slt        $at, $v0, $at
    /* 4AC8C 8004A08C 10200006 */  beqz       $at, .L8004A0A8_4ACA8
    /* 4AC90 8004A090 3C080001 */   lui       $t0, (0x10000 >> 16)
    /* 4AC94 8004A094 28418001 */  slti       $at, $v0, -0x7FFF
    /* 4AC98 8004A098 14200005 */  bnez       $at, .L8004A0B0_4ACB0
    /* 4AC9C 8004A09C 00000000 */   nop
    /* 4ACA0 8004A0A0 03E00008 */  jr         $ra
    /* 4ACA4 8004A0A4 00000000 */   nop
  .L8004A0A8_4ACA8:
    /* 4ACA8 8004A0A8 03E00008 */  jr         $ra
    /* 4ACAC 8004A0AC 00481022 */   sub       $v0, $v0, $t0 /* handwritten instruction */
  .L8004A0B0_4ACB0:
    /* 4ACB0 8004A0B0 03E00008 */  jr         $ra
    /* 4ACB4 8004A0B4 00481020 */   add       $v0, $v0, $t0 /* handwritten instruction */
    /* 4ACB8 8004A0B8 00000000 */  nop
    /* 4ACBC 8004A0BC 00000000 */  nop
