.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .bss, "wa"

dlabel refractBuffers
    .space 0x08

dlabel refractCurrentBuffer
    .space 0x04

dlabel refractDelay
    .space 0x04

dlabel refractWhichBuffer
    .space 0x10


.section .text, "ax"

/* Generated by spimdisasm 1.42.3 */

glabel refractOutputAssembler
    lui        $a0, %hi(refractDelay)
    lw         $a0, %lo(refractDelay)($a0)
    beqz       $a0, .L80075C60_76860
     nop
    addiu      $a0, $a0, -0x1
    lui        $at, %hi(refractDelay)
    jr         $ra
     sw        $a0, %lo(refractDelay)($at)
  .L80075C60_76860:
    lui        $a0, %hi(refractWhichBuffer)
    lw         $a0, %lo(refractWhichBuffer)($a0)
    lui        $t9, %hi(refractBuffers)
    addiu      $sp, $sp, -0x48
    sll        $a0, $a0, 2
    addu       $t9, $t9, $a0
    lw         $t9, %lo(refractBuffers)($t9)
    sw         $ra, 0x14($sp)
    beql       $t9, $zero, .L8007600C_76C0C
     lw        $ra, 0x14($sp)
    or         $t1, $t9, $zero
    lui        $at, (0x25800 >> 16)
    lui        $t4, %hi(gUnresolvedSymbolAddr)
    lui        $t2, %hi(currentScreen)
    ori        $at, $at, (0x25800 & 0xFFFF)
    addiu      $t4, $t4, %lo(gUnresolvedSymbolAddr)
    lw         $t2, %lo(currentScreen)($t2)
    addu       $t3, $t1, $at
    or         $t5, $t4, $zero
    or         $t8, $t1, $zero
  .L80075CB0_768B0:
    lw         $t6, 0x0($t1)
  .L80075CB4_768B4:
    bnel       $t6, $zero, .L80075E18_76A18
     subu      $a0, $t1, $t8
    lw         $t6, 0x4($t1)
    bnel       $t6, $zero, .L80075D38_76938
     addiu     $t1, $t1, 0x4
    lw         $t6, 0x8($t1)
    bnel       $t6, $zero, .L80075D58_76958
     addiu     $t1, $t1, 0x8
    lw         $t6, 0xC($t1)
    bnel       $t6, $zero, .L80075D78_76978
     addiu     $t1, $t1, 0xC
    lw         $t6, 0x10($t1)
    bnel       $t6, $zero, .L80075D98_76998
     addiu     $t1, $t1, 0x10
    lw         $t6, 0x14($t1)
    bnel       $t6, $zero, .L80075DB8_769B8
     addiu     $t1, $t1, 0x14
    lw         $t6, 0x18($t1)
    bnel       $t6, $zero, .L80075DD8_769D8
     addiu     $t1, $t1, 0x18
    lw         $t6, 0x1C($t1)
    bnel       $t6, $zero, .L80075DF8_769F8
     addiu     $t1, $t1, 0x1C
    addiu      $t1, $t1, 0x20
    sltu       $at, $t1, $t3
    bnel       $at, $zero, .L80075CB4_768B4
     lw        $t6, 0x0($t1)
    sltu       $at, $t8, $t3
    beql       $at, $zero, .L80075F2C_76B2C
     lw        $a0, 0x0($t4)
    b          .L80075F24_76B24
     subu      $a1, $t1, $t8
    addiu      $t1, $t1, 0x4
  .L80075D38_76938:
    sltu       $at, $t1, $t3
    bnez       $at, .L80075E14_76A14
     sltu      $at, $t8, $t3
    beql       $at, $zero, .L80075F2C_76B2C
     lw        $a0, 0x0($t4)
    b          .L80075F24_76B24
     subu      $a1, $t1, $t8
    addiu      $t1, $t1, 0x8
  .L80075D58_76958:
    sltu       $at, $t1, $t3
    bnez       $at, .L80075E14_76A14
     sltu      $at, $t8, $t3
    beql       $at, $zero, .L80075F2C_76B2C
     lw        $a0, 0x0($t4)
    b          .L80075F24_76B24
     subu      $a1, $t1, $t8
    addiu      $t1, $t1, 0xC
  .L80075D78_76978:
    sltu       $at, $t1, $t3
    bnez       $at, .L80075E14_76A14
     sltu      $at, $t8, $t3
    beql       $at, $zero, .L80075F2C_76B2C
     lw        $a0, 0x0($t4)
    b          .L80075F24_76B24
     subu      $a1, $t1, $t8
    addiu      $t1, $t1, 0x10
  .L80075D98_76998:
    sltu       $at, $t1, $t3
    bnez       $at, .L80075E14_76A14
     sltu      $at, $t8, $t3
    beql       $at, $zero, .L80075F2C_76B2C
     lw        $a0, 0x0($t4)
    b          .L80075F24_76B24
     subu      $a1, $t1, $t8
    addiu      $t1, $t1, 0x14
  .L80075DB8_769B8:
    sltu       $at, $t1, $t3
    bnez       $at, .L80075E14_76A14
     sltu      $at, $t8, $t3
    beql       $at, $zero, .L80075F2C_76B2C
     lw        $a0, 0x0($t4)
    b          .L80075F24_76B24
     subu      $a1, $t1, $t8
    addiu      $t1, $t1, 0x18
  .L80075DD8_769D8:
    sltu       $at, $t1, $t3
    bnez       $at, .L80075E14_76A14
     sltu      $at, $t8, $t3
    beql       $at, $zero, .L80075F2C_76B2C
     lw        $a0, 0x0($t4)
    b          .L80075F24_76B24
     subu      $a1, $t1, $t8
    addiu      $t1, $t1, 0x1C
  .L80075DF8_769F8:
    sltu       $at, $t1, $t3
    bnez       $at, .L80075E14_76A14
     sltu      $at, $t8, $t3
    beql       $at, $zero, .L80075F2C_76B2C
     lw        $a0, 0x0($t4)
    b          .L80075F24_76B24
     subu      $a1, $t1, $t8
  .L80075E14_76A14:
    subu       $a0, $t1, $t8
  .L80075E18_76A18:
    addu       $t2, $t2, $a0
    sw         $a0, 0x0($t5)
    addiu      $t5, $t5, 0x4
    or         $t7, $t2, $zero
    srl        $a0, $t6, 16
  .L80075E2C_76A2C:
    beql       $a0, $zero, .L80075E7C_76A7C
     andi      $a0, $t6, 0xFFFF
    sll        $a2, $a0, 26
    andi       $a3, $a0, 0x7C0
    srl        $a2, $a2, 27
    srl        $a1, $a0, 11
    addiu      $a2, $a2, -0x10
    srl        $v0, $a3, 5
    addiu      $a1, $a1, -0x10
    addu       $v0, $v0, $a3
    sll        $a1, $a1, 1
    sll        $a0, $a2, 7
    sll        $a3, $a2, 9
    addu       $a1, $a1, $t2
    addu       $a2, $a0, $a3
    addu       $a0, $a1, $a2
    lhu        $a0, 0x0($a0)
    addu       $a0, $a0, $v0
    sh         $a0, 0x0($t1)
    andi       $a0, $t6, 0xFFFF
  .L80075E7C_76A7C:
    beql       $a0, $zero, .L80075ECC_76ACC
     addiu     $t1, $t1, 0x4
    sll        $a2, $a0, 26
    andi       $a3, $a0, 0x7C0
    srl        $a2, $a2, 27
    srl        $a1, $a0, 11
    addiu      $a2, $a2, -0x10
    srl        $v0, $a3, 5
    addiu      $a1, $a1, -0x10
    addu       $v0, $v0, $a3
    sll        $a1, $a1, 1
    sll        $a0, $a2, 7
    sll        $a3, $a2, 9
    addu       $a1, $a1, $t2
    addu       $a2, $a0, $a3
    addu       $a0, $a1, $a2
    lhu        $a0, 0x2($a0)
    addu       $a0, $a0, $v0
    sh         $a0, 0x2($t1)
    addiu      $t1, $t1, 0x4
  .L80075ECC_76ACC:
    sltu       $at, $t1, $t3
    bnel       $at, $zero, .L80075EEC_76AEC
     lw        $t6, 0x0($t1)
    subu       $a0, $t1, $t8
    sw         $a0, 0x0($t5)
    b          .L80075EF8_76AF8
     addiu     $t5, $t5, 0x4
    lw         $t6, 0x0($t1)
  .L80075EEC_76AEC:
    addiu      $t2, $t2, 0x4
    bnel       $t6, $zero, .L80075E2C_76A2C
     srl       $a0, $t6, 16
  .L80075EF8_76AF8:
    or         $t8, $t1, $zero
    addiu      $t1, $t1, 0x4
    subu       $a0, $t2, $t7
    sltu       $at, $t1, $t3
    sw         $a0, 0x0($t5)
    bnez       $at, .L80075CB0_768B0
     addiu     $t5, $t5, 0x4
    sltu       $at, $t8, $t3
    beql       $at, $zero, .L80075F2C_76B2C
     lw        $a0, 0x0($t4)
    subu       $a1, $t1, $t8
  .L80075F24_76B24:
    sw         $a1, 0x0($t5)
    lw         $a0, 0x0($t4)
  .L80075F2C_76B2C:
    lui        $a1, %hi(currentScreen)
    lw         $a1, %lo(currentScreen)($a1)
    addu       $t1, $t9, $a0
    sltu       $at, $t1, $t3
    beqz       $at, .L80076008_76C08
     addu      $t2, $a1, $a0
    lui        $t5, %hi(gUnresolvedSymbolAddr)
    addiu      $t5, $t5, %lo(gUnresolvedSymbolAddr)
    addiu      $t5, $t5, 0x4
  .L80075F50_76B50:
    lw         $t0, 0x0($t5)
    addiu      $t5, $t5, 0x4
    bgez       $t0, .L80075F64_76B64
     addu      $at, $t0, $zero
    addiu      $at, $t0, 0x3
  .L80075F64_76B64:
    sra        $t0, $at, 2
    slti       $at, $t0, 0x8
    bnel       $at, $zero, .L80075FD4_76BD4
     lw        $t6, 0x0($t1)
  .L80075F74_76B74:
    lw         $t6, 0x0($t1)
    addiu      $t0, $t0, -0x8
    sltiu      $at, $t0, 0x8
    sw         $t6, 0x0($t2)
    lw         $t6, 0x4($t1)
    addiu      $t1, $t1, 0x20
    addiu      $t2, $t2, 0x20
    sw         $t6, -0x1C($t2)
    lw         $t6, -0x18($t1)
    sw         $t6, -0x18($t2)
    lw         $t6, -0x14($t1)
    sw         $t6, -0x14($t2)
    lw         $t6, -0x10($t1)
    sw         $t6, -0x10($t2)
    lw         $t6, -0xC($t1)
    sw         $t6, -0xC($t2)
    lw         $t6, -0x8($t1)
    sw         $t6, -0x8($t2)
    lw         $t6, -0x4($t1)
    beqz       $at, .L80075F74_76B74
     sw        $t6, -0x4($t2)
    beql       $t0, $zero, .L80075FEC_76BEC
     lw        $a0, 0x0($t5)
  .L80075FD0_76BD0:
    lw         $t6, 0x0($t1)
  .L80075FD4_76BD4:
    addiu      $t0, $t0, -0x1
    addiu      $t1, $t1, 0x4
    addiu      $t2, $t2, 0x4
    bnez       $t0, .L80075FD0_76BD0
     sw        $t6, -0x4($t2)
    lw         $a0, 0x0($t5)
  .L80075FEC_76BEC:
    addiu      $t5, $t5, 0x4
    addu       $t1, $t1, $a0
    sltu       $at, $t1, $t3
    bnez       $at, .L80075F50_76B50
     addu      $t2, $t2, $a0
    b          .L8007600C_76C0C
     lw        $ra, 0x14($sp)
  .L80076008_76C08:
    lw         $ra, 0x14($sp)
  .L8007600C_76C0C:
    addiu      $sp, $sp, 0x48
    jr         $ra
endlabel refractOutputAssembler
