.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.0 */

/* Handwritten function */
glabel trackMakePolylist
    /* 1D800 8001CC00 8FB90010 */  lw         $t9, 0x10($sp)
    /* 1D804 8001CC04 8FB80014 */  lw         $t8, 0x14($sp)
    /* 1D808 8001CC08 8FAF0018 */  lw         $t7, 0x18($sp)
    /* 1D80C 8001CC0C 23BDFF40 */  addi       $sp, $sp, -0xC0 /* handwritten instruction */
    /* 1D810 8001CC10 3C080001 */  lui        $t0, (0x186A0 >> 16)
    /* 1D814 8001CC14 3C09FFFE */  lui        $t1, (0xFFFE7960 >> 16)
    /* 1D818 8001CC18 350886A0 */  ori        $t0, $t0, (0x186A0 & 0xFFFF)
    /* 1D81C 8001CC1C 35297960 */  ori        $t1, $t1, (0xFFFE7960 & 0xFFFF)
    /* 1D820 8001CC20 37390800 */  ori        $t9, $t9, 0x800
    /* 1D824 8001CC24 37390080 */  ori        $t9, $t9, 0x80
    /* 1D828 8001CC28 AFB50028 */  sw         $s5, 0x28($sp)
    /* 1D82C 8001CC2C AFB40024 */  sw         $s4, 0x24($sp)
    /* 1D830 8001CC30 AFB30020 */  sw         $s3, 0x20($sp)
    /* 1D834 8001CC34 AFB2001C */  sw         $s2, 0x1C($sp)
    /* 1D838 8001CC38 AFB10018 */  sw         $s1, 0x18($sp)
    /* 1D83C 8001CC3C AFB00014 */  sw         $s0, 0x14($sp)
    /* 1D840 8001CC40 AFB900B0 */  sw         $t9, 0xB0($sp)
    /* 1D844 8001CC44 AFBF0038 */  sw         $ra, 0x38($sp)
    /* 1D848 8001CC48 AFBE0034 */  sw         $fp, 0x34($sp)
    /* 1D84C 8001CC4C AFB70030 */  sw         $s7, 0x30($sp)
    /* 1D850 8001CC50 AFB6002C */  sw         $s6, 0x2C($sp)
    /* 1D854 8001CC54 01008025 */  or         $s0, $t0, $zero
    /* 1D858 8001CC58 01209825 */  or         $s3, $t1, $zero
    /* 1D85C 8001CC5C 01008825 */  or         $s1, $t0, $zero
    /* 1D860 8001CC60 0120A025 */  or         $s4, $t1, $zero
    /* 1D864 8001CC64 01009025 */  or         $s2, $t0, $zero
    /* 1D868 8001CC68 0120A825 */  or         $s5, $t1, $zero
    /* 1D86C 8001CC6C AFB800B4 */  sw         $t8, 0xB4($sp)
    /* 1D870 8001CC70 10800074 */  beqz       $a0, .L8001CE44
    /* 1D874 8001CC74 AFAF00B8 */   sw        $t7, 0xB8($sp)
    /* 1D878 8001CC78 000440C0 */  sll        $t0, $a0, 3
    /* 1D87C 8001CC7C 00044880 */  sll        $t1, $a0, 2
    /* 1D880 8001CC80 01092020 */  add        $a0, $t0, $t1 /* handwritten instruction */
    /* 1D884 8001CC84 00852020 */  add        $a0, $a0, $a1 /* handwritten instruction */
  .L8001CC88:
    /* 1D888 8001CC88 C4A00000 */  lwc1       $f0, 0x0($a1)
    /* 1D88C 8001CC8C C4EC0000 */  lwc1       $f12, 0x0($a3)
    /* 1D890 8001CC90 C4A20004 */  lwc1       $f2, 0x4($a1)
    /* 1D894 8001CC94 4600000D */  trunc.w.s  $f0, $f0
    /* 1D898 8001CC98 C4A40008 */  lwc1       $f4, 0x8($a1)
    /* 1D89C 8001CC9C C4C60000 */  lwc1       $f6, 0x0($a2)
    /* 1D8A0 8001CCA0 4600630D */  trunc.w.s  $f12, $f12
    /* 1D8A4 8001CCA4 C4C80004 */  lwc1       $f8, 0x4($a2)
    /* 1D8A8 8001CCA8 C4CA0008 */  lwc1       $f10, 0x8($a2)
    /* 1D8AC 8001CCAC 4600108D */  trunc.w.s  $f2, $f2
    /* 1D8B0 8001CCB0 44080000 */  mfc1       $t0, $f0
    /* 1D8B4 8001CCB4 440E6000 */  mfc1       $t6, $f12
    /* 1D8B8 8001CCB8 4600210D */  trunc.w.s  $f4, $f4
    /* 1D8BC 8001CCBC 44091000 */  mfc1       $t1, $f2
    /* 1D8C0 8001CCC0 010E7820 */  add        $t7, $t0, $t6 /* handwritten instruction */
    /* 1D8C4 8001CCC4 4600318D */  trunc.w.s  $f6, $f6
    /* 1D8C8 8001CCC8 440A2000 */  mfc1       $t2, $f4
    /* 1D8CC 8001CCCC 026F082A */  slt        $at, $s3, $t7
    /* 1D8D0 8001CCD0 4600420D */  trunc.w.s  $f8, $f8
    /* 1D8D4 8001CCD4 440B3000 */  mfc1       $t3, $f6
    /* 1D8D8 8001CCD8 4600528D */  trunc.w.s  $f10, $f10
    /* 1D8DC 8001CCDC 440C4000 */  mfc1       $t4, $f8
    /* 1D8E0 8001CCE0 440D5000 */  mfc1       $t5, $f10
    /* 1D8E4 8001CCE4 50200003 */  beql       $at, $zero, .L8001CCF4
    /* 1D8E8 8001CCE8 010E7822 */   sub       $t7, $t0, $t6 /* handwritten instruction */
    /* 1D8EC 8001CCEC 01E09825 */  or         $s3, $t7, $zero
    /* 1D8F0 8001CCF0 010E7822 */  sub        $t7, $t0, $t6 /* handwritten instruction */
  .L8001CCF4:
    /* 1D8F4 8001CCF4 01F0082A */  slt        $at, $t7, $s0
    /* 1D8F8 8001CCF8 50200003 */  beql       $at, $zero, .L8001CD08
    /* 1D8FC 8001CCFC 012E7820 */   add       $t7, $t1, $t6 /* handwritten instruction */
    /* 1D900 8001CD00 01E08025 */  or         $s0, $t7, $zero
    /* 1D904 8001CD04 012E7820 */  add        $t7, $t1, $t6 /* handwritten instruction */
  .L8001CD08:
    /* 1D908 8001CD08 028F082A */  slt        $at, $s4, $t7
    /* 1D90C 8001CD0C 50200003 */  beql       $at, $zero, .L8001CD1C
    /* 1D910 8001CD10 012E7822 */   sub       $t7, $t1, $t6 /* handwritten instruction */
    /* 1D914 8001CD14 01E0A025 */  or         $s4, $t7, $zero
    /* 1D918 8001CD18 012E7822 */  sub        $t7, $t1, $t6 /* handwritten instruction */
  .L8001CD1C:
    /* 1D91C 8001CD1C 01F1082A */  slt        $at, $t7, $s1
    /* 1D920 8001CD20 50200003 */  beql       $at, $zero, .L8001CD30
    /* 1D924 8001CD24 014E7820 */   add       $t7, $t2, $t6 /* handwritten instruction */
    /* 1D928 8001CD28 01E08825 */  or         $s1, $t7, $zero
    /* 1D92C 8001CD2C 014E7820 */  add        $t7, $t2, $t6 /* handwritten instruction */
  .L8001CD30:
    /* 1D930 8001CD30 02AF082A */  slt        $at, $s5, $t7
    /* 1D934 8001CD34 50200003 */  beql       $at, $zero, .L8001CD44
    /* 1D938 8001CD38 014E7822 */   sub       $t7, $t2, $t6 /* handwritten instruction */
    /* 1D93C 8001CD3C 01E0A825 */  or         $s5, $t7, $zero
    /* 1D940 8001CD40 014E7822 */  sub        $t7, $t2, $t6 /* handwritten instruction */
  .L8001CD44:
    /* 1D944 8001CD44 01F2082A */  slt        $at, $t7, $s2
    /* 1D948 8001CD48 50200003 */  beql       $at, $zero, .L8001CD58
    /* 1D94C 8001CD4C 016E7820 */   add       $t7, $t3, $t6 /* handwritten instruction */
    /* 1D950 8001CD50 01E09025 */  or         $s2, $t7, $zero
    /* 1D954 8001CD54 016E7820 */  add        $t7, $t3, $t6 /* handwritten instruction */
  .L8001CD58:
    /* 1D958 8001CD58 026F082A */  slt        $at, $s3, $t7
    /* 1D95C 8001CD5C 50200003 */  beql       $at, $zero, .L8001CD6C
    /* 1D960 8001CD60 016E7822 */   sub       $t7, $t3, $t6 /* handwritten instruction */
    /* 1D964 8001CD64 01E09825 */  or         $s3, $t7, $zero
    /* 1D968 8001CD68 016E7822 */  sub        $t7, $t3, $t6 /* handwritten instruction */
  .L8001CD6C:
    /* 1D96C 8001CD6C 01F0082A */  slt        $at, $t7, $s0
    /* 1D970 8001CD70 50200003 */  beql       $at, $zero, .L8001CD80
    /* 1D974 8001CD74 018E7820 */   add       $t7, $t4, $t6 /* handwritten instruction */
    /* 1D978 8001CD78 01E08025 */  or         $s0, $t7, $zero
    /* 1D97C 8001CD7C 018E7820 */  add        $t7, $t4, $t6 /* handwritten instruction */
  .L8001CD80:
    /* 1D980 8001CD80 028F082A */  slt        $at, $s4, $t7
    /* 1D984 8001CD84 50200003 */  beql       $at, $zero, .L8001CD94
    /* 1D988 8001CD88 018E7822 */   sub       $t7, $t4, $t6 /* handwritten instruction */
    /* 1D98C 8001CD8C 01E0A025 */  or         $s4, $t7, $zero
    /* 1D990 8001CD90 018E7822 */  sub        $t7, $t4, $t6 /* handwritten instruction */
  .L8001CD94:
    /* 1D994 8001CD94 01F1082A */  slt        $at, $t7, $s1
    /* 1D998 8001CD98 50200003 */  beql       $at, $zero, .L8001CDA8
    /* 1D99C 8001CD9C 01AE7820 */   add       $t7, $t5, $t6 /* handwritten instruction */
    /* 1D9A0 8001CDA0 01E08825 */  or         $s1, $t7, $zero
    /* 1D9A4 8001CDA4 01AE7820 */  add        $t7, $t5, $t6 /* handwritten instruction */
  .L8001CDA8:
    /* 1D9A8 8001CDA8 02AF082A */  slt        $at, $s5, $t7
    /* 1D9AC 8001CDAC 50200003 */  beql       $at, $zero, .L8001CDBC
    /* 1D9B0 8001CDB0 01AE7822 */   sub       $t7, $t5, $t6 /* handwritten instruction */
    /* 1D9B4 8001CDB4 01E0A825 */  or         $s5, $t7, $zero
    /* 1D9B8 8001CDB8 01AE7822 */  sub        $t7, $t5, $t6 /* handwritten instruction */
  .L8001CDBC:
    /* 1D9BC 8001CDBC 01F2082A */  slt        $at, $t7, $s2
    /* 1D9C0 8001CDC0 50200003 */  beql       $at, $zero, .L8001CDD0
    /* 1D9C4 8001CDC4 24A5000C */   addiu     $a1, $a1, 0xC
    /* 1D9C8 8001CDC8 01E09025 */  or         $s2, $t7, $zero
    /* 1D9CC 8001CDCC 24A5000C */  addiu      $a1, $a1, 0xC
  .L8001CDD0:
    /* 1D9D0 8001CDD0 00A4082A */  slt        $at, $a1, $a0
    /* 1D9D4 8001CDD4 24C6000C */  addiu      $a2, $a2, 0xC
    /* 1D9D8 8001CDD8 1420FFAB */  bnez       $at, .L8001CC88
    /* 1D9DC 8001CDDC 24E70004 */   addiu     $a3, $a3, 0x4
    /* 1D9E0 8001CDE0 0270082A */  slt        $at, $s3, $s0
    /* 1D9E4 8001CDE4 50200005 */  beql       $at, $zero, .L8001CDFC
    /* 1D9E8 8001CDE8 0291082A */   slt       $at, $s4, $s1
    /* 1D9EC 8001CDEC 02004025 */  or         $t0, $s0, $zero
    /* 1D9F0 8001CDF0 02608025 */  or         $s0, $s3, $zero
    /* 1D9F4 8001CDF4 01009825 */  or         $s3, $t0, $zero
    /* 1D9F8 8001CDF8 0291082A */  slt        $at, $s4, $s1
  .L8001CDFC:
    /* 1D9FC 8001CDFC 50200005 */  beql       $at, $zero, .L8001CE14
    /* 1DA00 8001CE00 02B2082A */   slt       $at, $s5, $s2
    /* 1DA04 8001CE04 02204025 */  or         $t0, $s1, $zero
    /* 1DA08 8001CE08 02808825 */  or         $s1, $s4, $zero
    /* 1DA0C 8001CE0C 0100A025 */  or         $s4, $t0, $zero
    /* 1DA10 8001CE10 02B2082A */  slt        $at, $s5, $s2
  .L8001CE14:
    /* 1DA14 8001CE14 50200005 */  beql       $at, $zero, .L8001CE2C
    /* 1DA18 8001CE18 24080005 */   addiu     $t0, $zero, 0x5
    /* 1DA1C 8001CE1C 02404025 */  or         $t0, $s2, $zero
    /* 1DA20 8001CE20 02A09025 */  or         $s2, $s5, $zero
    /* 1DA24 8001CE24 0100A825 */  or         $s5, $t0, $zero
    /* 1DA28 8001CE28 24080005 */  addiu      $t0, $zero, 0x5
  .L8001CE2C:
    /* 1DA2C 8001CE2C 02088022 */  sub        $s0, $s0, $t0 /* handwritten instruction */
    /* 1DA30 8001CE30 02288822 */  sub        $s1, $s1, $t0 /* handwritten instruction */
    /* 1DA34 8001CE34 02489022 */  sub        $s2, $s2, $t0 /* handwritten instruction */
    /* 1DA38 8001CE38 02689820 */  add        $s3, $s3, $t0 /* handwritten instruction */
    /* 1DA3C 8001CE3C 0288A020 */  add        $s4, $s4, $t0 /* handwritten instruction */
    /* 1DA40 8001CE40 02A8A820 */  add        $s5, $s5, $t0 /* handwritten instruction */
  .L8001CE44:
    /* 1DA44 8001CE44 44900000 */  mtc1       $s0, $f0
    /* 1DA48 8001CE48 44911000 */  mtc1       $s1, $f2
    /* 1DA4C 8001CE4C 44922000 */  mtc1       $s2, $f4
    /* 1DA50 8001CE50 46800020 */  cvt.s.w    $f0, $f0
    /* 1DA54 8001CE54 8FAF00B8 */  lw         $t7, 0xB8($sp)
    /* 1DA58 8001CE58 44933000 */  mtc1       $s3, $f6
    /* 1DA5C 8001CE5C 44944000 */  mtc1       $s4, $f8
    /* 1DA60 8001CE60 44955000 */  mtc1       $s5, $f10
    /* 1DA64 8001CE64 468010A0 */  cvt.s.w    $f2, $f2
    /* 1DA68 8001CE68 23A40098 */  addi       $a0, $sp, 0x98 /* handwritten instruction */
    /* 1DA6C 8001CE6C AFAF0010 */  sw         $t7, 0x10($sp)
    /* 1DA70 8001CE70 23A500A4 */  addi       $a1, $sp, 0xA4 /* handwritten instruction */
    /* 1DA74 8001CE74 E4800000 */  swc1       $f0, 0x0($a0)
    /* 1DA78 8001CE78 46802120 */  cvt.s.w    $f4, $f4
    /* 1DA7C 8001CE7C E4820004 */  swc1       $f2, 0x4($a0)
    /* 1DA80 8001CE80 03203025 */  or         $a2, $t9, $zero
    /* 1DA84 8001CE84 03003825 */  or         $a3, $t8, $zero
    /* 1DA88 8001CE88 468031A0 */  cvt.s.w    $f6, $f6
    /* 1DA8C 8001CE8C E4840008 */  swc1       $f4, 0x8($a0)
    /* 1DA90 8001CE90 46804220 */  cvt.s.w    $f8, $f8
    /* 1DA94 8001CE94 E4A60000 */  swc1       $f6, 0x0($a1)
    /* 1DA98 8001CE98 468052A0 */  cvt.s.w    $f10, $f10
    /* 1DA9C 8001CE9C E4A80004 */  swc1       $f8, 0x4($a1)
    /* 1DAA0 8001CEA0 0C01FBF1 */  jal        hitMakePolylist
    /* 1DAA4 8001CEA4 E4AA0008 */   swc1      $f10, 0x8($a1)
    /* 1DAA8 8001CEA8 3C08800A */  lui        $t0, %hi(track)
    /* 1DAAC 8001CEAC 8D0815F0 */  lw         $t0, %lo(track)($t0)
    /* 1DAB0 8001CEB0 23B6003C */  addi       $s6, $sp, 0x3C /* handwritten instruction */
    /* 1DAB4 8001CEB4 23B9008C */  addi       $t9, $sp, 0x8C /* handwritten instruction */
    /* 1DAB8 8001CEB8 850F001A */  lh         $t7, 0x1A($t0)
    /* 1DABC 8001CEBC 23B70064 */  addi       $s7, $sp, 0x64 /* handwritten instruction */
    /* 1DAC0 8001CEC0 0000F025 */  or         $fp, $zero, $zero
    /* 1DAC4 8001CEC4 8D040008 */  lw         $a0, 0x8($t0)
    /* 1DAC8 8001CEC8 11E00031 */  beqz       $t7, .L8001CF90
    /* 1DACC 8001CECC 8D0E0004 */   lw        $t6, 0x4($t0)
  .L8001CED0:
    /* 1DAD0 8001CED0 84820006 */  lh         $v0, 0x6($a0)
    /* 1DAD4 8001CED4 84830000 */  lh         $v1, 0x0($a0)
    /* 1DAD8 8001CED8 24420005 */  addiu      $v0, $v0, 0x5
    /* 1DADC 8001CEDC 0050082A */  slt        $at, $v0, $s0
    /* 1DAE0 8001CEE0 14200027 */  bnez       $at, .L8001CF80
    /* 1DAE4 8001CEE4 2463FFFB */   addiu     $v1, $v1, -0x5
    /* 1DAE8 8001CEE8 0263082A */  slt        $at, $s3, $v1
    /* 1DAEC 8001CEEC 54200025 */  bnel       $at, $zero, .L8001CF84
    /* 1DAF0 8001CEF0 21EFFFFF */   addi      $t7, $t7, -0x1 /* handwritten instruction */
    /* 1DAF4 8001CEF4 84820008 */  lh         $v0, 0x8($a0)
    /* 1DAF8 8001CEF8 84830002 */  lh         $v1, 0x2($a0)
    /* 1DAFC 8001CEFC 24420005 */  addiu      $v0, $v0, 0x5
    /* 1DB00 8001CF00 0051082A */  slt        $at, $v0, $s1
    /* 1DB04 8001CF04 1420001E */  bnez       $at, .L8001CF80
    /* 1DB08 8001CF08 2463FFFB */   addiu     $v1, $v1, -0x5
    /* 1DB0C 8001CF0C 0283082A */  slt        $at, $s4, $v1
    /* 1DB10 8001CF10 5420001C */  bnel       $at, $zero, .L8001CF84
    /* 1DB14 8001CF14 21EFFFFF */   addi      $t7, $t7, -0x1 /* handwritten instruction */
    /* 1DB18 8001CF18 8482000A */  lh         $v0, 0xA($a0)
    /* 1DB1C 8001CF1C 84830004 */  lh         $v1, 0x4($a0)
    /* 1DB20 8001CF20 24420005 */  addiu      $v0, $v0, 0x5
    /* 1DB24 8001CF24 0052082A */  slt        $at, $v0, $s2
    /* 1DB28 8001CF28 14200015 */  bnez       $at, .L8001CF80
    /* 1DB2C 8001CF2C 2463FFFB */   addiu     $v1, $v1, -0x5
    /* 1DB30 8001CF30 02A3082A */  slt        $at, $s5, $v1
    /* 1DB34 8001CF34 54200013 */  bnel       $at, $zero, .L8001CF84
    /* 1DB38 8001CF38 21EFFFFF */   addi      $t7, $t7, -0x1 /* handwritten instruction */
    /* 1DB3C 8001CF3C 02002825 */  or         $a1, $s0, $zero
    /* 1DB40 8001CF40 02403025 */  or         $a2, $s2, $zero
    /* 1DB44 8001CF44 02603825 */  or         $a3, $s3, $zero
    /* 1DB48 8001CF48 0C00744D */  jal        getXZCompareMask
    /* 1DB4C 8001CF4C AFB50010 */   sw        $s5, 0x10($sp)
    /* 1DB50 8001CF50 AEC20000 */  sw         $v0, 0x0($s6)
    /* 1DB54 8001CF54 02202825 */  or         $a1, $s1, $zero
    /* 1DB58 8001CF58 0C007495 */  jal        getYCompareMask
    /* 1DB5C 8001CF5C 02803025 */   or        $a2, $s4, $zero
    /* 1DB60 8001CF60 A3220000 */  sb         $v0, 0x0($t9)
    /* 1DB64 8001CF64 27DE0001 */  addiu      $fp, $fp, 0x1
    /* 1DB68 8001CF68 2401000A */  addiu      $at, $zero, 0xA
    /* 1DB6C 8001CF6C AEEE0000 */  sw         $t6, 0x0($s7)
    /* 1DB70 8001CF70 27390001 */  addiu      $t9, $t9, 0x1
    /* 1DB74 8001CF74 26D60004 */  addiu      $s6, $s6, 0x4
    /* 1DB78 8001CF78 13C10005 */  beq        $fp, $at, .L8001CF90
    /* 1DB7C 8001CF7C 26F70004 */   addiu     $s7, $s7, 0x4
  .L8001CF80:
    /* 1DB80 8001CF80 21EFFFFF */  addi       $t7, $t7, -0x1 /* handwritten instruction */
  .L8001CF84:
    /* 1DB84 8001CF84 2484000C */  addiu      $a0, $a0, 0xC
    /* 1DB88 8001CF88 15E0FFD1 */  bnez       $t7, .L8001CED0
    /* 1DB8C 8001CF8C 25CE0048 */   addiu     $t6, $t6, 0x48
  .L8001CF90:
    /* 1DB90 8001CF90 13C00059 */  beqz       $fp, func_8001D0F8
    /* 1DB94 8001CF94 00009825 */   or        $s3, $zero, $zero
    /* 1DB98 8001CF98 3C04800A */  lui        $a0, %hi(level)
    /* 1DB9C 8001CF9C 8C8415F4 */  lw         $a0, %lo(level)($a0)
    /* 1DBA0 8001CFA0 3C12800F */  lui        $s2, %hi(PLlist)
    /* 1DBA4 8001CFA4 3C1F800F */  lui        $ra, %hi(PLgrps)
    /* 1DBA8 8001CFA8 3C18800F */  lui        $t8, %hi(PLpolys)
    /* 1DBAC 8001CFAC 8E523E78 */  lw         $s2, %lo(PLlist)($s2)
    /* 1DBB0 8001CFB0 8FFF3E7C */  lw         $ra, %lo(PLgrps)($ra)
    /* 1DBB4 8001CFB4 8F183E80 */  lw         $t8, %lo(PLpolys)($t8)
    /* 1DBB8 8001CFB8 23B6003C */  addi       $s6, $sp, 0x3C /* handwritten instruction */
    /* 1DBBC 8001CFBC 23B9008C */  addi       $t9, $sp, 0x8C /* handwritten instruction */
    /* 1DBC0 8001CFC0 23B70064 */  addi       $s7, $sp, 0x64 /* handwritten instruction */
    /* 1DBC4 8001CFC4 848400EA */  lh         $a0, 0xEA($a0)
  .L8001CFC8:
    /* 1DBC8 8001CFC8 8EEF0000 */  lw         $t7, 0x0($s7)
    /* 1DBCC 8001CFCC 3C017FFF */  lui        $at, (0x7FFFFFFF >> 16)
    /* 1DBD0 8001CFD0 3421FFFF */  ori        $at, $at, (0x7FFFFFFF & 0xFFFF)
    /* 1DBD4 8001CFD4 8ECE0000 */  lw         $t6, 0x0($s6)
    /* 1DBD8 8001CFD8 832C0000 */  lb         $t4, 0x0($t9)
    /* 1DBDC 8001CFDC 95F40028 */  lhu        $s4, 0x28($t7)
    /* 1DBE0 8001CFE0 01E14024 */  and        $t0, $t7, $at
    /* 1DBE4 8001CFE4 AE480000 */  sw         $t0, 0x0($s2)
    /* 1DBE8 8001CFE8 00005025 */  or         $t2, $zero, $zero
    /* 1DBEC 8001CFEC 26730001 */  addiu      $s3, $s3, 0x1
    /* 1DBF0 8001CFF0 26520004 */  addiu      $s2, $s2, 0x4
    /* 1DBF4 8001CFF4 27180002 */  addiu      $t8, $t8, 0x2
    /* 1DBF8 8001CFF8 27FF0002 */  addiu      $ra, $ra, 0x2
    /* 1DBFC 8001CFFC 8DED000C */  lw         $t5, 0xC($t7)
    /* 1DC00 8001D000 8DF10010 */  lw         $s1, 0x10($t7)
    /* 1DC04 8001D004 8DEB0014 */  lw         $t3, 0x14($t7)
    /* 1DC08 8001D008 8DF00018 */  lw         $s0, 0x18($t7)
  .L8001D00C:
    /* 1DC0C 8001D00C 8DA8000C */  lw         $t0, 0xC($t5)
    /* 1DC10 8001D010 8FA900B4 */  lw         $t1, 0xB4($sp)
    /* 1DC14 8001D014 01094824 */  and        $t1, $t0, $t1
    /* 1DC18 8001D018 55200006 */  bnel       $t1, $zero, .L8001D034
    /* 1DC1C 8001D01C 95B50008 */   lhu       $s5, 0x8($t5)
    /* 1DC20 8001D020 8FA900B0 */  lw         $t1, 0xB0($sp)
    /* 1DC24 8001D024 01094824 */  and        $t1, $t0, $t1
    /* 1DC28 8001D028 55200028 */  bnel       $t1, $zero, .L8001D0CC
    /* 1DC2C 8001D02C 254A0001 */   addiu     $t2, $t2, 0x1
    /* 1DC30 8001D030 95B50008 */  lhu        $s5, 0x8($t5)
  .L8001D034:
    /* 1DC34 8001D034 25A80010 */  addiu      $t0, $t5, 0x10
    /* 1DC38 8001D038 95090008 */  lhu        $t1, 0x8($t0)
    /* 1DC3C 8001D03C 00151080 */  sll        $v0, $s5, 2
    /* 1DC40 8001D040 001540C0 */  sll        $t0, $s5, 3
    /* 1DC44 8001D044 00094880 */  sll        $t1, $t1, 2
    /* 1DC48 8001D048 02292820 */  add        $a1, $s1, $t1 /* handwritten instruction */
    /* 1DC4C 8001D04C 02223020 */  add        $a2, $s1, $v0 /* handwritten instruction */
    /* 1DC50 8001D050 02083820 */  add        $a3, $s0, $t0 /* handwritten instruction */
    /* 1DC54 8001D054 01751820 */  add        $v1, $t3, $s5 /* handwritten instruction */
  .L8001D058:
    /* 1DC58 8001D058 8CC20000 */  lw         $v0, 0x0($a2)
    /* 1DC5C 8001D05C 004E1024 */  and        $v0, $v0, $t6
    /* 1DC60 8001D060 3048FFFF */  andi       $t0, $v0, 0xFFFF
    /* 1DC64 8001D064 51000014 */  beql       $t0, $zero, .L8001D0B8
    /* 1DC68 8001D068 24C60004 */   addiu     $a2, $a2, 0x4
    /* 1DC6C 8001D06C 3C09FFFF */  lui        $t1, (0xFFFF0000 >> 16)
    /* 1DC70 8001D070 00494824 */  and        $t1, $v0, $t1
    /* 1DC74 8001D074 51200010 */  beql       $t1, $zero, .L8001D0B8
    /* 1DC78 8001D078 24C60004 */   addiu     $a2, $a2, 0x4
    /* 1DC7C 8001D07C 80620000 */  lb         $v0, 0x0($v1)
    /* 1DC80 8001D080 004C1024 */  and        $v0, $v0, $t4
    /* 1DC84 8001D084 304200FF */  andi       $v0, $v0, 0xFF
    /* 1DC88 8001D088 5040000B */  beql       $v0, $zero, .L8001D0B8
    /* 1DC8C 8001D08C 24C60004 */   addiu     $a2, $a2, 0x4
    /* 1DC90 8001D090 AE470000 */  sw         $a3, 0x0($s2)
    /* 1DC94 8001D094 26730001 */  addiu      $s3, $s3, 0x1
    /* 1DC98 8001D098 A7EA0000 */  sh         $t2, 0x0($ra)
    /* 1DC9C 8001D09C 0264082A */  slt        $at, $s3, $a0
    /* 1DCA0 8001D0A0 A7150000 */  sh         $s5, 0x0($t8)
    /* 1DCA4 8001D0A4 26520004 */  addiu      $s2, $s2, 0x4
    /* 1DCA8 8001D0A8 27180002 */  addiu      $t8, $t8, 0x2
    /* 1DCAC 8001D0AC 10200010 */  beqz       $at, .L8001D0F0
    /* 1DCB0 8001D0B0 27FF0002 */   addiu     $ra, $ra, 0x2
    /* 1DCB4 8001D0B4 24C60004 */  addiu      $a2, $a2, 0x4
  .L8001D0B8:
    /* 1DCB8 8001D0B8 26B50001 */  addiu      $s5, $s5, 0x1
    /* 1DCBC 8001D0BC 24630001 */  addiu      $v1, $v1, 0x1
    /* 1DCC0 8001D0C0 14C5FFE5 */  bne        $a2, $a1, .L8001D058
    /* 1DCC4 8001D0C4 24E70008 */   addiu     $a3, $a3, 0x8
    /* 1DCC8 8001D0C8 254A0001 */  addiu      $t2, $t2, 0x1
  .L8001D0CC:
    /* 1DCCC 8001D0CC 168AFFCF */  bne        $s4, $t2, .L8001D00C
    /* 1DCD0 8001D0D0 25AD0010 */   addiu     $t5, $t5, 0x10
    /* 1DCD4 8001D0D4 23DEFFFF */  addi       $fp, $fp, -0x1 /* handwritten instruction */
    /* 1DCD8 8001D0D8 26D60004 */  addiu      $s6, $s6, 0x4
    /* 1DCDC 8001D0DC 27390001 */  addiu      $t9, $t9, 0x1
    /* 1DCE0 8001D0E0 17C0FFB9 */  bnez       $fp, .L8001CFC8
    /* 1DCE4 8001D0E4 26F70004 */   addiu     $s7, $s7, 0x4
    /* 1DCE8 8001D0E8 0800743E */  j          func_8001D0F8
    /* 1DCEC 8001D0EC 00000000 */   nop
  .L8001D0F0:
    /* 1DCF0 8001D0F0 0800743F */  j          func_8001D0FC
    /* 1DCF4 8001D0F4 24020001 */   addiu     $v0, $zero, 0x1
  glabel func_8001D0F8
    /* 1DCF8 8001D0F8 00001025 */  or         $v0, $zero, $zero
  glabel func_8001D0FC
    /* 1DCFC 8001D0FC 8FBF0038 */  lw         $ra, 0x38($sp)
    /* 1DD00 8001D100 3C01800F */  lui        $at, %hi(PLno)
    /* 1DD04 8001D104 AC333E84 */  sw         $s3, %lo(PLno)($at)
    /* 1DD08 8001D108 8FBE0034 */  lw         $fp, 0x34($sp)
    /* 1DD0C 8001D10C 8FB70030 */  lw         $s7, 0x30($sp)
    /* 1DD10 8001D110 8FB6002C */  lw         $s6, 0x2C($sp)
    /* 1DD14 8001D114 8FB50028 */  lw         $s5, 0x28($sp)
    /* 1DD18 8001D118 8FB40024 */  lw         $s4, 0x24($sp)
    /* 1DD1C 8001D11C 8FB30020 */  lw         $s3, 0x20($sp)
    /* 1DD20 8001D120 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 1DD24 8001D124 8FB10018 */  lw         $s1, 0x18($sp)
    /* 1DD28 8001D128 8FB00014 */  lw         $s0, 0x14($sp)
    /* 1DD2C 8001D12C 03E00008 */  jr         $ra
    /* 1DD30 8001D130 27BD00C0 */   addiu     $sp, $sp, 0xC0

/* Handwritten function */
glabel getXZCompareMask
    /* 1DD34 8001D134 10800045 */  beqz       $a0, .L8001D24C
    /* 1DD38 8001D138 00001025 */   or        $v0, $zero, $zero
    /* 1DD3C 8001D13C 84880000 */  lh         $t0, 0x0($a0)
    /* 1DD40 8001D140 8FAD0010 */  lw         $t5, 0x10($sp)
    /* 1DD44 8001D144 84890004 */  lh         $t1, 0x4($a0)
    /* 1DD48 8001D148 00E8082A */  slt        $at, $a3, $t0
    /* 1DD4C 8001D14C 848A0006 */  lh         $t2, 0x6($a0)
    /* 1DD50 8001D150 10200002 */  beqz       $at, .L8001D15C
    /* 1DD54 8001D154 848B000A */   lh        $t3, 0xA($a0)
    /* 1DD58 8001D158 01003825 */  or         $a3, $t0, $zero
  .L8001D15C:
    /* 1DD5C 8001D15C 00A8082A */  slt        $at, $a1, $t0
    /* 1DD60 8001D160 50200003 */  beql       $at, $zero, .L8001D170
    /* 1DD64 8001D164 01A9082A */   slt       $at, $t5, $t1
    /* 1DD68 8001D168 01002825 */  or         $a1, $t0, $zero
    /* 1DD6C 8001D16C 01A9082A */  slt        $at, $t5, $t1
  .L8001D170:
    /* 1DD70 8001D170 50200003 */  beql       $at, $zero, .L8001D180
    /* 1DD74 8001D174 00C9082A */   slt       $at, $a2, $t1
    /* 1DD78 8001D178 01206825 */  or         $t5, $t1, $zero
    /* 1DD7C 8001D17C 00C9082A */  slt        $at, $a2, $t1
  .L8001D180:
    /* 1DD80 8001D180 50200003 */  beql       $at, $zero, .L8001D190
    /* 1DD84 8001D184 0147082A */   slt       $at, $t2, $a3
    /* 1DD88 8001D188 01203025 */  or         $a2, $t1, $zero
    /* 1DD8C 8001D18C 0147082A */  slt        $at, $t2, $a3
  .L8001D190:
    /* 1DD90 8001D190 50200003 */  beql       $at, $zero, .L8001D1A0
    /* 1DD94 8001D194 0145082A */   slt       $at, $t2, $a1
    /* 1DD98 8001D198 01403825 */  or         $a3, $t2, $zero
    /* 1DD9C 8001D19C 0145082A */  slt        $at, $t2, $a1
  .L8001D1A0:
    /* 1DDA0 8001D1A0 50200003 */  beql       $at, $zero, .L8001D1B0
    /* 1DDA4 8001D1A4 016D082A */   slt       $at, $t3, $t5
    /* 1DDA8 8001D1A8 01402825 */  or         $a1, $t2, $zero
    /* 1DDAC 8001D1AC 016D082A */  slt        $at, $t3, $t5
  .L8001D1B0:
    /* 1DDB0 8001D1B0 50200003 */  beql       $at, $zero, .L8001D1C0
    /* 1DDB4 8001D1B4 0166082A */   slt       $at, $t3, $a2
    /* 1DDB8 8001D1B8 01606825 */  or         $t5, $t3, $zero
    /* 1DDBC 8001D1BC 0166082A */  slt        $at, $t3, $a2
  .L8001D1C0:
    /* 1DDC0 8001D1C0 50200003 */  beql       $at, $zero, .L8001D1D0
    /* 1DDC4 8001D1C4 01485022 */   sub       $t2, $t2, $t0 /* handwritten instruction */
    /* 1DDC8 8001D1C8 01603025 */  or         $a2, $t3, $zero
    /* 1DDCC 8001D1CC 01485022 */  sub        $t2, $t2, $t0 /* handwritten instruction */
  .L8001D1D0:
    /* 1DDD0 8001D1D0 000A5103 */  sra        $t2, $t2, 4
    /* 1DDD4 8001D1D4 254A0001 */  addiu      $t2, $t2, 0x1
    /* 1DDD8 8001D1D8 24030001 */  addiu      $v1, $zero, 0x1
    /* 1DDDC 8001D1DC 01486020 */  add        $t4, $t2, $t0 /* handwritten instruction */
  .L8001D1E0:
    /* 1DDE0 8001D1E0 0185082A */  slt        $at, $t4, $a1
    /* 1DDE4 8001D1E4 14200004 */  bnez       $at, .L8001D1F8
    /* 1DDE8 8001D1E8 00E8082A */   slt       $at, $a3, $t0
    /* 1DDEC 8001D1EC 54200003 */  bnel       $at, $zero, .L8001D1FC
    /* 1DDF0 8001D1F0 00031840 */   sll       $v1, $v1, 1
    /* 1DDF4 8001D1F4 00431025 */  or         $v0, $v0, $v1
  .L8001D1F8:
    /* 1DDF8 8001D1F8 00031840 */  sll        $v1, $v1, 1
  .L8001D1FC:
    /* 1DDFC 8001D1FC 3C010001 */  lui        $at, (0x10000 >> 16)
    /* 1DE00 8001D200 0061082A */  slt        $at, $v1, $at
    /* 1DE04 8001D204 018A6020 */  add        $t4, $t4, $t2 /* handwritten instruction */
    /* 1DE08 8001D208 1420FFF5 */  bnez       $at, .L8001D1E0
    /* 1DE0C 8001D20C 010A4020 */   add       $t0, $t0, $t2 /* handwritten instruction */
    /* 1DE10 8001D210 01695022 */  sub        $t2, $t3, $t1 /* handwritten instruction */
    /* 1DE14 8001D214 000A5103 */  sra        $t2, $t2, 4
    /* 1DE18 8001D218 254A0001 */  addiu      $t2, $t2, 0x1
    /* 1DE1C 8001D21C 01496020 */  add        $t4, $t2, $t1 /* handwritten instruction */
    /* 1DE20 8001D220 01204025 */  or         $t0, $t1, $zero
  .L8001D224:
    /* 1DE24 8001D224 0186082A */  slt        $at, $t4, $a2
    /* 1DE28 8001D228 14200004 */  bnez       $at, .L8001D23C
    /* 1DE2C 8001D22C 01A8082A */   slt       $at, $t5, $t0
    /* 1DE30 8001D230 54200003 */  bnel       $at, $zero, .L8001D240
    /* 1DE34 8001D234 00031840 */   sll       $v1, $v1, 1
    /* 1DE38 8001D238 00431025 */  or         $v0, $v0, $v1
  .L8001D23C:
    /* 1DE3C 8001D23C 00031840 */  sll        $v1, $v1, 1
  .L8001D240:
    /* 1DE40 8001D240 018A6020 */  add        $t4, $t4, $t2 /* handwritten instruction */
    /* 1DE44 8001D244 1460FFF7 */  bnez       $v1, .L8001D224
    /* 1DE48 8001D248 010A4020 */   add       $t0, $t0, $t2 /* handwritten instruction */
  .L8001D24C:
    /* 1DE4C 8001D24C 03E00008 */  jr         $ra
    /* 1DE50 8001D250 00000000 */   nop

/* Handwritten function */
glabel getYCompareMask
    /* 1DE54 8001D254 10800024 */  beqz       $a0, .L8001D2E8
    /* 1DE58 8001D258 00001025 */   or        $v0, $zero, $zero
    /* 1DE5C 8001D25C 84880002 */  lh         $t0, 0x2($a0)
    /* 1DE60 8001D260 84890008 */  lh         $t1, 0x8($a0)
    /* 1DE64 8001D264 00C8082A */  slt        $at, $a2, $t0
    /* 1DE68 8001D268 50200003 */  beql       $at, $zero, .L8001D278
    /* 1DE6C 8001D26C 00A8082A */   slt       $at, $a1, $t0
    /* 1DE70 8001D270 01003025 */  or         $a2, $t0, $zero
    /* 1DE74 8001D274 00A8082A */  slt        $at, $a1, $t0
  .L8001D278:
    /* 1DE78 8001D278 50200003 */  beql       $at, $zero, .L8001D288
    /* 1DE7C 8001D27C 0126082A */   slt       $at, $t1, $a2
    /* 1DE80 8001D280 01002825 */  or         $a1, $t0, $zero
    /* 1DE84 8001D284 0126082A */  slt        $at, $t1, $a2
  .L8001D288:
    /* 1DE88 8001D288 50200003 */  beql       $at, $zero, .L8001D298
    /* 1DE8C 8001D28C 0125082A */   slt       $at, $t1, $a1
    /* 1DE90 8001D290 01203025 */  or         $a2, $t1, $zero
    /* 1DE94 8001D294 0125082A */  slt        $at, $t1, $a1
  .L8001D298:
    /* 1DE98 8001D298 50200003 */  beql       $at, $zero, .L8001D2A8
    /* 1DE9C 8001D29C 01285022 */   sub       $t2, $t1, $t0 /* handwritten instruction */
    /* 1DEA0 8001D2A0 01202825 */  or         $a1, $t1, $zero
    /* 1DEA4 8001D2A4 01285022 */  sub        $t2, $t1, $t0 /* handwritten instruction */
  .L8001D2A8:
    /* 1DEA8 8001D2A8 000A50C3 */  sra        $t2, $t2, 3
    /* 1DEAC 8001D2AC 254A0001 */  addiu      $t2, $t2, 0x1
    /* 1DEB0 8001D2B0 01486020 */  add        $t4, $t2, $t0 /* handwritten instruction */
    /* 1DEB4 8001D2B4 01004025 */  or         $t0, $t0, $zero
    /* 1DEB8 8001D2B8 24030001 */  addiu      $v1, $zero, 0x1
  .L8001D2BC:
    /* 1DEBC 8001D2BC 0185082A */  slt        $at, $t4, $a1
    /* 1DEC0 8001D2C0 14200004 */  bnez       $at, .L8001D2D4
    /* 1DEC4 8001D2C4 00C8082A */   slt       $at, $a2, $t0
    /* 1DEC8 8001D2C8 54200003 */  bnel       $at, $zero, .L8001D2D8
    /* 1DECC 8001D2CC 00031840 */   sll       $v1, $v1, 1
    /* 1DED0 8001D2D0 00431025 */  or         $v0, $v0, $v1
  .L8001D2D4:
    /* 1DED4 8001D2D4 00031840 */  sll        $v1, $v1, 1
  .L8001D2D8:
    /* 1DED8 8001D2D8 28610100 */  slti       $at, $v1, 0x100
    /* 1DEDC 8001D2DC 018A6020 */  add        $t4, $t4, $t2 /* handwritten instruction */
    /* 1DEE0 8001D2E0 1420FFF6 */  bnez       $at, .L8001D2BC
    /* 1DEE4 8001D2E4 010A4020 */   add       $t0, $t0, $t2 /* handwritten instruction */
  .L8001D2E8:
    /* 1DEE8 8001D2E8 03E00008 */  jr         $ra
    /* 1DEEC 8001D2EC 00000000 */   nop

/* Handwritten function */
glabel trackLightAsm
    /* 1DEF0 8001D2F0 24A30020 */  addiu      $v1, $a1, 0x20
    /* 1DEF4 8001D2F4 9068005D */  lbu        $t0, 0x5D($v1)
    /* 1DEF8 8001D2F8 9069005E */  lbu        $t1, 0x5E($v1)
    /* 1DEFC 8001D2FC 906A005F */  lbu        $t2, 0x5F($v1)
    /* 1DF00 8001D300 55000008 */  bnel       $t0, $zero, .L8001D324
    /* 1DF04 8001D304 27BDFF00 */   addiu     $sp, $sp, -0x100
    /* 1DF08 8001D308 55200006 */  bnel       $t1, $zero, .L8001D324
    /* 1DF0C 8001D30C 27BDFF00 */   addiu     $sp, $sp, -0x100
    /* 1DF10 8001D310 55400004 */  bnel       $t2, $zero, .L8001D324
    /* 1DF14 8001D314 27BDFF00 */   addiu     $sp, $sp, -0x100
    /* 1DF18 8001D318 03E00008 */  jr         $ra
    /* 1DF1C 8001D31C 00000000 */   nop
    /* 1DF20 8001D320 27BDFF00 */  addiu      $sp, $sp, -0x100
  .L8001D324:
    /* 1DF24 8001D324 AFB00000 */  sw         $s0, 0x0($sp)
    /* 1DF28 8001D328 AFB10004 */  sw         $s1, 0x4($sp)
    /* 1DF2C 8001D32C AFB20008 */  sw         $s2, 0x8($sp)
    /* 1DF30 8001D330 AFB3000C */  sw         $s3, 0xC($sp)
    /* 1DF34 8001D334 AFB40010 */  sw         $s4, 0x10($sp)
    /* 1DF38 8001D338 AFB50014 */  sw         $s5, 0x14($sp)
    /* 1DF3C 8001D33C AFB60018 */  sw         $s6, 0x18($sp)
    /* 1DF40 8001D340 AFB7001C */  sw         $s7, 0x1C($sp)
    /* 1DF44 8001D344 C4A7000C */  lwc1       $f7, 0xC($a1)
    /* 1DF48 8001D348 C4A10000 */  lwc1       $f1, 0x0($a1)
    /* 1DF4C 8001D34C C4A20004 */  lwc1       $f2, 0x4($a1)
    /* 1DF50 8001D350 4600380D */  trunc.w.s  $f0, $f7
    /* 1DF54 8001D354 C4A30008 */  lwc1       $f3, 0x8($a1)
    /* 1DF58 8001D358 848C001A */  lh         $t4, 0x1A($a0)
    /* 1DF5C 8001D35C 240D0000 */  addiu      $t5, $zero, 0x0
    /* 1DF60 8001D360 4600090D */  trunc.w.s  $f4, $f1
    /* 1DF64 8001D364 44130000 */  mfc1       $s3, $f0
    /* 1DF68 8001D368 27B70020 */  addiu      $s7, $sp, 0x20
    /* 1DF6C 8001D36C 4600114D */  trunc.w.s  $f5, $f2
    /* 1DF70 8001D370 44102000 */  mfc1       $s0, $f4
    /* 1DF74 8001D374 8C960004 */  lw         $s6, 0x4($a0)
    /* 1DF78 8001D378 4600198D */  trunc.w.s  $f6, $f3
    /* 1DF7C 8001D37C 44112800 */  mfc1       $s1, $f5
    /* 1DF80 8001D380 02137020 */  add        $t6, $s0, $s3 /* handwritten instruction */
    /* 1DF84 8001D384 8C870008 */  lw         $a3, 0x8($a0)
    /* 1DF88 8001D388 44123000 */  mfc1       $s2, $f6
    /* 1DF8C 8001D38C 02337820 */  add        $t7, $s1, $s3 /* handwritten instruction */
    /* 1DF90 8001D390 02138022 */  sub        $s0, $s0, $s3 /* handwritten instruction */
    /* 1DF94 8001D394 0253C020 */  add        $t8, $s2, $s3 /* handwritten instruction */
    /* 1DF98 8001D398 02338822 */  sub        $s1, $s1, $s3 /* handwritten instruction */
    /* 1DF9C 8001D39C 1180008A */  beqz       $t4, .L8001D5C8
    /* 1DFA0 8001D3A0 02539022 */   sub       $s2, $s2, $s3 /* handwritten instruction */
  .L8001D3A4:
    /* 1DFA4 8001D3A4 80C80000 */  lb         $t0, 0x0($a2)
    /* 1DFA8 8001D3A8 258CFFFF */  addiu      $t4, $t4, -0x1
    /* 1DFAC 8001D3AC 5100001D */  beql       $t0, $zero, .L8001D424
    /* 1DFB0 8001D3B0 24E7000C */   addiu     $a3, $a3, 0xC
    /* 1DFB4 8001D3B4 84E90006 */  lh         $t1, 0x6($a3)
    /* 1DFB8 8001D3B8 0130082A */  slt        $at, $t1, $s0
    /* 1DFBC 8001D3BC 54200019 */  bnel       $at, $zero, .L8001D424
    /* 1DFC0 8001D3C0 24E7000C */   addiu     $a3, $a3, 0xC
    /* 1DFC4 8001D3C4 84EA0008 */  lh         $t2, 0x8($a3)
    /* 1DFC8 8001D3C8 0151082A */  slt        $at, $t2, $s1
    /* 1DFCC 8001D3CC 54200015 */  bnel       $at, $zero, .L8001D424
    /* 1DFD0 8001D3D0 24E7000C */   addiu     $a3, $a3, 0xC
    /* 1DFD4 8001D3D4 84EB000A */  lh         $t3, 0xA($a3)
    /* 1DFD8 8001D3D8 0172082A */  slt        $at, $t3, $s2
    /* 1DFDC 8001D3DC 54200011 */  bnel       $at, $zero, .L8001D424
    /* 1DFE0 8001D3E0 24E7000C */   addiu     $a3, $a3, 0xC
    /* 1DFE4 8001D3E4 84E90000 */  lh         $t1, 0x0($a3)
    /* 1DFE8 8001D3E8 01C9082A */  slt        $at, $t6, $t1
    /* 1DFEC 8001D3EC 5420000D */  bnel       $at, $zero, .L8001D424
    /* 1DFF0 8001D3F0 24E7000C */   addiu     $a3, $a3, 0xC
    /* 1DFF4 8001D3F4 84EA0002 */  lh         $t2, 0x2($a3)
    /* 1DFF8 8001D3F8 01EA082A */  slt        $at, $t7, $t2
    /* 1DFFC 8001D3FC 54200009 */  bnel       $at, $zero, .L8001D424
    /* 1E000 8001D400 24E7000C */   addiu     $a3, $a3, 0xC
    /* 1E004 8001D404 84EB0004 */  lh         $t3, 0x4($a3)
    /* 1E008 8001D408 030B082A */  slt        $at, $t8, $t3
    /* 1E00C 8001D40C 54200005 */  bnel       $at, $zero, .L8001D424
    /* 1E010 8001D410 24E7000C */   addiu     $a3, $a3, 0xC
    /* 1E014 8001D414 AEF60000 */  sw         $s6, 0x0($s7)
    /* 1E018 8001D418 26F70004 */  addiu      $s7, $s7, 0x4
    /* 1E01C 8001D41C 25AD0001 */  addiu      $t5, $t5, 0x1
    /* 1E020 8001D420 24E7000C */  addiu      $a3, $a3, 0xC
  .L8001D424:
    /* 1E024 8001D424 26D60048 */  addiu      $s6, $s6, 0x48
    /* 1E028 8001D428 1580FFDE */  bnez       $t4, .L8001D3A4
    /* 1E02C 8001D42C 24C60001 */   addiu     $a2, $a2, 0x1
    /* 1E030 8001D430 51A00066 */  beql       $t5, $zero, .L8001D5CC
    /* 1E034 8001D434 8FB00000 */   lw        $s0, 0x0($sp)
    /* 1E038 8001D438 C4A80014 */  lwc1       $f8, 0x14($a1)
    /* 1E03C 8001D43C C4A90018 */  lwc1       $f9, 0x18($a1)
    /* 1E040 8001D440 C4AA001C */  lwc1       $f10, 0x1C($a1)
    /* 1E044 8001D444 27B70020 */  addiu      $s7, $sp, 0x20
    /* 1E048 8001D448 00139840 */  sll        $s3, $s3, 1
  .L8001D44C:
    /* 1E04C 8001D44C 8EF60000 */  lw         $s6, 0x0($s7)
    /* 1E050 8001D450 25ADFFFF */  addiu      $t5, $t5, -0x1
    /* 1E054 8001D454 24140000 */  addiu      $s4, $zero, 0x0
    /* 1E058 8001D458 8EC80034 */  lw         $t0, 0x34($s6)
    /* 1E05C 8001D45C 86CC0024 */  lh         $t4, 0x24($s6)
    /* 1E060 8001D460 24150001 */  addiu      $s5, $zero, 0x1
    /* 1E064 8001D464 8D070004 */  lw         $a3, 0x4($t0)
    /* 1E068 8001D468 8EC20000 */  lw         $v0, 0x0($s6)
    /* 1E06C 8001D46C 11800054 */  beqz       $t4, .L8001D5C0
    /* 1E070 8001D470 94F90000 */   lhu       $t9, 0x0($a3)
  .L8001D474:
    /* 1E074 8001D474 844E0000 */  lh         $t6, 0x0($v0)
    /* 1E078 8001D478 844F0002 */  lh         $t7, 0x2($v0)
    /* 1E07C 8001D47C 84580004 */  lh         $t8, 0x4($v0)
    /* 1E080 8001D480 01D04023 */  subu       $t0, $t6, $s0
    /* 1E084 8001D484 0268082B */  sltu       $at, $s3, $t0
    /* 1E088 8001D488 258CFFFF */  addiu      $t4, $t4, -0x1
    /* 1E08C 8001D48C 01F14823 */  subu       $t1, $t7, $s1
    /* 1E090 8001D490 1420003D */  bnez       $at, .L8001D588
    /* 1E094 8001D494 03125023 */   subu      $t2, $t8, $s2
    /* 1E098 8001D498 0269082B */  sltu       $at, $s3, $t1
    /* 1E09C 8001D49C 1420003A */  bnez       $at, .L8001D588
    /* 1E0A0 8001D4A0 026A082B */   sltu      $at, $s3, $t2
    /* 1E0A4 8001D4A4 54200039 */  bnel       $at, $zero, .L8001D58C
    /* 1E0A8 8001D4A8 0015A840 */   sll       $s5, $s5, 1
    /* 1E0AC 8001D4AC 448E2000 */  mtc1       $t6, $f4
    /* 1E0B0 8001D4B0 448F2800 */  mtc1       $t7, $f5
    /* 1E0B4 8001D4B4 44983000 */  mtc1       $t8, $f6
    /* 1E0B8 8001D4B8 46802120 */  cvt.s.w    $f4, $f4
    /* 1E0BC 8001D4BC 46802960 */  cvt.s.w    $f5, $f5
    /* 1E0C0 8001D4C0 46012101 */  sub.s      $f4, $f4, $f1
    /* 1E0C4 8001D4C4 468031A0 */  cvt.s.w    $f6, $f6
    /* 1E0C8 8001D4C8 46022941 */  sub.s      $f5, $f5, $f2
    /* 1E0CC 8001D4CC 46042102 */  mul.s      $f4, $f4, $f4
    /* 1E0D0 8001D4D0 46033181 */  sub.s      $f6, $f6, $f3
    /* 1E0D4 8001D4D4 46052942 */  mul.s      $f5, $f5, $f5
    /* 1E0D8 8001D4D8 00000000 */  nop
    /* 1E0DC 8001D4DC 46063182 */  mul.s      $f6, $f6, $f6
    /* 1E0E0 8001D4E0 460522C0 */  add.s      $f11, $f4, $f5
    /* 1E0E4 8001D4E4 46065AC0 */  add.s      $f11, $f11, $f6
    /* 1E0E8 8001D4E8 4608583C */  c.lt.s     $f11, $f8
    /* 1E0EC 8001D4EC 45000026 */  bc1f       .L8001D588
    /* 1E0F0 8001D4F0 00000000 */   nop
    /* 1E0F4 8001D4F4 4609583C */  c.lt.s     $f11, $f9
    /* 1E0F8 8001D4F8 246B005D */  addiu      $t3, $v1, 0x5D
    /* 1E0FC 8001D4FC 24140001 */  addiu      $s4, $zero, 0x1
    /* 1E100 8001D500 0335C825 */  or         $t9, $t9, $s5
    /* 1E104 8001D504 4503000F */  bc1tl      .L8001D544
    /* 1E108 8001D508 904E0006 */   lbu       $t6, 0x6($v0)
    /* 1E10C 8001D50C 46005AC4 */  sqrt.s     $f11, $f11
    /* 1E110 8001D510 904E0006 */  lbu        $t6, 0x6($v0)
    /* 1E114 8001D514 904F0007 */  lbu        $t7, 0x7($v0)
    /* 1E118 8001D518 90580008 */  lbu        $t8, 0x8($v0)
    /* 1E11C 8001D51C 460B3AC1 */  sub.s      $f11, $f7, $f11
    /* 1E120 8001D520 460A5AC2 */  mul.s      $f11, $f11, $f10
    /* 1E124 8001D524 4600580D */  trunc.w.s  $f0, $f11
    /* 1E128 8001D528 440B0000 */  mfc1       $t3, $f0
    /* 1E12C 8001D52C 00000000 */  nop
    /* 1E130 8001D530 000B5040 */  sll        $t2, $t3, 1
    /* 1E134 8001D534 016A5821 */  addu       $t3, $t3, $t2
    /* 1E138 8001D538 10000004 */  b          .L8001D54C
    /* 1E13C 8001D53C 01635821 */   addu      $t3, $t3, $v1
    /* 1E140 8001D540 904E0006 */  lbu        $t6, 0x6($v0)
  .L8001D544:
    /* 1E144 8001D544 904F0007 */  lbu        $t7, 0x7($v0)
    /* 1E148 8001D548 90580008 */  lbu        $t8, 0x8($v0)
  .L8001D54C:
    /* 1E14C 8001D54C 91680000 */  lbu        $t0, 0x0($t3)
    /* 1E150 8001D550 91690001 */  lbu        $t1, 0x1($t3)
    /* 1E154 8001D554 916A0002 */  lbu        $t2, 0x2($t3)
    /* 1E158 8001D558 01C8082A */  slt        $at, $t6, $t0
    /* 1E15C 8001D55C 50200003 */  beql       $at, $zero, .L8001D56C
    /* 1E160 8001D560 01E9082A */   slt       $at, $t7, $t1
    /* 1E164 8001D564 A0480006 */  sb         $t0, 0x6($v0)
    /* 1E168 8001D568 01E9082A */  slt        $at, $t7, $t1
  .L8001D56C:
    /* 1E16C 8001D56C 50200003 */  beql       $at, $zero, .L8001D57C
    /* 1E170 8001D570 030A082A */   slt       $at, $t8, $t2
    /* 1E174 8001D574 A0490007 */  sb         $t1, 0x7($v0)
    /* 1E178 8001D578 030A082A */  slt        $at, $t8, $t2
  .L8001D57C:
    /* 1E17C 8001D57C 50200003 */  beql       $at, $zero, .L8001D58C
    /* 1E180 8001D580 0015A840 */   sll       $s5, $s5, 1
    /* 1E184 8001D584 A04A0008 */  sb         $t2, 0x8($v0)
  .L8001D588:
    /* 1E188 8001D588 0015A840 */  sll        $s5, $s5, 1
  .L8001D58C:
    /* 1E18C 8001D58C 32B5FFFF */  andi       $s5, $s5, 0xFFFF
    /* 1E190 8001D590 16A00005 */  bnez       $s5, .L8001D5A8
    /* 1E194 8001D594 00000000 */   nop
    /* 1E198 8001D598 A4F90000 */  sh         $t9, 0x0($a3)
    /* 1E19C 8001D59C 84F90002 */  lh         $t9, 0x2($a3)
    /* 1E1A0 8001D5A0 24E70002 */  addiu      $a3, $a3, 0x2
    /* 1E1A4 8001D5A4 24150001 */  addiu      $s5, $zero, 0x1
  .L8001D5A8:
    /* 1E1A8 8001D5A8 1580FFB2 */  bnez       $t4, .L8001D474
    /* 1E1AC 8001D5AC 2442000A */   addiu     $v0, $v0, 0xA
    /* 1E1B0 8001D5B0 A4F90000 */  sh         $t9, 0x0($a3)
    /* 1E1B4 8001D5B4 92C80032 */  lbu        $t0, 0x32($s6)
    /* 1E1B8 8001D5B8 01144025 */  or         $t0, $t0, $s4
    /* 1E1BC 8001D5BC A2C80032 */  sb         $t0, 0x32($s6)
  .L8001D5C0:
    /* 1E1C0 8001D5C0 15A0FFA2 */  bnez       $t5, .L8001D44C
    /* 1E1C4 8001D5C4 26F70004 */   addiu     $s7, $s7, 0x4
  .L8001D5C8:
    /* 1E1C8 8001D5C8 8FB00000 */  lw         $s0, 0x0($sp)
  .L8001D5CC:
    /* 1E1CC 8001D5CC 8FB10004 */  lw         $s1, 0x4($sp)
    /* 1E1D0 8001D5D0 8FB20008 */  lw         $s2, 0x8($sp)
    /* 1E1D4 8001D5D4 8FB3000C */  lw         $s3, 0xC($sp)
    /* 1E1D8 8001D5D8 8FB40010 */  lw         $s4, 0x10($sp)
    /* 1E1DC 8001D5DC 8FB50014 */  lw         $s5, 0x14($sp)
    /* 1E1E0 8001D5E0 8FB60018 */  lw         $s6, 0x18($sp)
    /* 1E1E4 8001D5E4 8FB7001C */  lw         $s7, 0x1C($sp)
    /* 1E1E8 8001D5E8 03E00008 */  jr         $ra
    /* 1E1EC 8001D5EC 27BD0100 */   addiu     $sp, $sp, 0x100
