name: regress-validate
on:
  workflow_call:
    secrets:
      SECRET_PASSPHRASE: { required: true }
      SECRET_REPO: { required: true }
      SECRET_TOKEN: { required: true }
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        version: [ kiosk, us ]
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
  
    - name: Update Submodules
      run: git submodule update --init --recursive

    - name: Fetch Secrets
      uses: actions/checkout@v7
      with:
        repository: ${{ secrets.SECRET_REPO }}
        token: ${{ secrets.SECRET_TOKEN }}
        path: secret_repo
  
    - name: Decrypt Secrets
      working-directory: secret_repo
      run: |
        ./decrypt_secret.sh
      env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
          SECRET_BASENAME: baserom
          SECRET_VERSION: ${{ matrix.version }}

    - name: Move Baserom
      working-directory: secret_repo
      run:  mv baserom.${{ matrix.version }}.z64 ../baseroms/
  
    - name: Install Packages
      run: sudo apt-get install -y build-essential pkg-config git python3 wget python3-pip binutils-mips-linux-gnu python3-venv

    - name: Make Setup
      run: make setup

    - name: Make Extract
      run: make extract VERSION=${{ matrix.version }}

    - name: Make Build
      run: make -j4 VERSION=${{ matrix.version }}

    - name: Verify
      run: sha1sum -c ver/verification/jfg.${{ matrix.version }}.sha1

    - name: Generate objdiff report
      run: .venv/bin/python3 -m mapfile_parser objdiff_report --version ${{ matrix.version }}

    - name: Upload progress report artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/progress.json

    - name: Cleanup
      run: make clean VERSION=${{ matrix.version }}
